import Link from 'next/link'

export const metadata = {
  title: 'Insurance Claims | Denied Claim & Insurance Appeal Workflows',
  description: 'Find the right workflow for a denied insurance claim, coverage denial, roof claim, health claim, disability claim, workers compensation claim, or other insurance dispute.'
}

const workflows = [
  ['Denied Insurance Claim', 'Understand the denial, organize supporting records, and prepare a focused response or appeal.', '/workflows/denied-insurance-claim'],
  ['Appeal an Insurance Denial', 'Build an appeal around the denial reason, policy language, evidence, and requested outcome.', '/workflows/appeal-insurance-denial'],
  ['Health Insurance Denial', 'Organize medical records, explanation of benefits, medical-necessity issues, and appeal documents.', '/workflows/health-insurance-denial'],
  ['Home or Roof Claim Denial', 'Prepare a response to a denied property claim with photos, estimates, timelines, and coverage records.', '/workflows/home-roof-claim-denial'],
  ['Auto Insurance Claim Denial', 'Document the incident, denial, evidence, damages, and requested reconsideration.', '/workflows/auto-insurance-claim-denial'],
  ['Workers Compensation Denial', 'Organize a denied workers compensation claim and prepare the records needed for the next response or appeal.', '/workflows/workers-comp-denial'],
  ['Disability Claim Denial', 'Structure a response to a short- or long-term disability denial using the denial reason and supporting medical/employment records.', '/workflows/disability-claim-denial'],
  ['Life Insurance Claim Denial', 'Organize the policy, claim record, denial explanation, and supporting documents for review.', '/workflows/life-insurance-claim-denial'],
]

export default function Home() {
  return <main className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">Insurance Claims</Link><nav className="flex gap-6 text-sm text-slate-300"><a href="#workflows">Workflows</a><a href="#how">How it works</a><a href="#status">Product status</a></nav></div></header>
    <section className="mx-auto max-w-6xl px-6 py-20 md:py-28"><div className="max-w-4xl"><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">INSURANCE CLAIMS · MASTER WORKFLOW DIRECTORY</div><h1 className="mt-5 text-5xl font-semibold tracking-tight md:text-7xl">Find the insurance claim workflow that matches your problem.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Insurance search intent is specific: denied claim, coverage denial, roof claim, health insurance denial, disability denial, workers compensation, auto, and life insurance. This product organizes those jobs into focused workflows.</p></div></section>
    <section id="workflows" className="mx-auto max-w-6xl px-6 pb-20"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{workflows.map(([title, desc, href]) => <Link key={href} href={href} className="group rounded-2xl border border-white/10 bg-white/[.04] p-6 transition hover:-translate-y-1 hover:bg-white/[.07]"><div className="text-xs font-semibold uppercase tracking-widest text-cyan-300">Workflow</div><h2 className="mt-3 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{desc}</p><span className="mt-6 inline-block text-sm font-semibold text-cyan-300">Explore workflow →</span></Link>)}</div></section>
    <section id="how" className="border-y border-white/10 bg-white/[.03]"><div className="mx-auto grid max-w-6xl gap-10 px-6 py-20 md:grid-cols-4"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">01</div><h2 className="mt-3 font-semibold">Analyze</h2><p className="mt-2 text-sm leading-6 text-slate-400">Start from the claim, policy, denial, and supporting records.</p></div><div><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">02</div><h2 className="mt-3 font-semibold">Organize</h2><p className="mt-2 text-sm leading-6 text-slate-400">Build a timeline and evidence set around the actual issue.</p></div><div><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">03</div><h2 className="mt-3 font-semibold">Prepare</h2><p className="mt-2 text-sm leading-6 text-slate-400">Draft a reviewed response or appeal based on documented facts.</p></div><div><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">04</div><h2 className="mt-3 font-semibold">Deliver</h2><p className="mt-2 text-sm leading-6 text-slate-400">When mailing is enabled, hand off to MailMyPDF for physical delivery and proof.</p></div></div></section>
    <section id="status" className="mx-auto max-w-6xl px-6 py-20"><div className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-8"><div className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Foundation stage</div><h2 className="mt-3 text-2xl font-semibold">The directory is ready; the execution engine is still being built.</h2><p className="mt-3 max-w-3xl text-slate-300">These pages are the master information architecture for Insurance Claims. We are not presenting unfinished workflows as fully operational. Each workflow will become executable as its product implementation is migrated into this repository.</p></div></section>
  </main>
}
