-- Migration 005: Event Store & Relationship Engine
-- The foundational layer for FairProcess's unified information model.
-- Every change anywhere becomes an Event. Every entity knows its relationships.
-- Timeline, Audit Log, Notifications, and Activity Feed become projections of this stream.
-- Purely additive — no existing tables modified.

-- ═══════════════════════════════════════════════════════════════
-- EVENT STORE (append-only — the single source of truth for "what happened")
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  actor_type TEXT NOT NULL DEFAULT 'system',
  actor_id TEXT,
  actor_name TEXT,
  severity TEXT DEFAULT 'info',
  title TEXT,
  description TEXT,
  payload TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_events_case_id ON events(case_id);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_entity ON events(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_events_actor ON events(actor_type, actor_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity);

-- ═══════════════════════════════════════════════════════════════
-- RELATIONSHIP GRAPH (typed connections between entities)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS relationships (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  relationship_type TEXT NOT NULL,
  metadata TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_rel_case_id ON relationships(case_id);
CREATE INDEX IF NOT EXISTS idx_rel_source ON relationships(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_rel_target ON relationships(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_rel_type ON relationships(relationship_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rel_unique ON relationships(source_type, source_id, target_type, target_id, relationship_type);

-- ═══════════════════════════════════════════════════════════════
-- EVENT TYPE CATALOG (reference data for event types)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS event_types (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  is_timeline_visible INTEGER DEFAULT 1,
  is_notification_worthy INTEGER DEFAULT 0,
  is_audit_worthy INTEGER DEFAULT 1,
  default_severity TEXT DEFAULT 'info',
  icon TEXT
);

CREATE INDEX IF NOT EXISTS idx_eventtypes_code ON event_types(code);
CREATE INDEX IF NOT EXISTS idx_eventtypes_category ON event_types(category);

-- Seed event types
INSERT OR IGNORE INTO event_types (id, code, category, label, description, is_timeline_visible, is_notification_worthy, is_audit_worthy, default_severity) VALUES
  -- Evidence events
  ('etp-evi-up', 'evidence.uploaded', 'evidence', 'Evidence Uploaded', 'A new evidence document was uploaded to a case', 1, 1, 1, 'info'),
  ('etp-evi-pr', 'evidence.processed', 'evidence', 'Evidence Processed', 'OCR and extraction completed on an evidence document', 1, 0, 1, 'info'),
  ('etp-evi-fl', 'evidence.flagged', 'evidence', 'Evidence Flagged', 'Due-process flags detected on evidence', 1, 1, 1, 'warning'),
  -- Finding events
  ('etp-fnd-cr', 'finding.created', 'finding', 'Finding Created', 'A due-process finding was generated by the analysis engine', 1, 1, 1, 'warning'),
  ('etp-fnd-rs', 'finding.resolved', 'finding', 'Finding Resolved', 'A finding status was updated', 1, 0, 1, 'info'),
  -- Code enforcement events
  ('etp-ce-cr', 'ce.case_created', 'code_enforcement', 'CE Case Created', 'A code enforcement case was created', 1, 1, 1, 'info'),
  ('etp-ce-ns', 'ce.notice_served', 'code_enforcement', 'Notice Served', 'Code enforcement notice was served on property owner', 1, 1, 1, 'warning'),
  ('etp-ce-hs', 'ce.hearing_scheduled', 'code_enforcement', 'Hearing Scheduled', 'A hearing was scheduled for a CE case', 1, 1, 1, 'info'),
  ('etp-ce-cd', 'ce.compliance_deadline', 'code_enforcement', 'Compliance Deadline Set', 'A compliance deadline was set for a CE case', 1, 1, 1, 'warning'),
  ('etp-ce-ab', 'ce.abatement', 'code_enforcement', 'Abatement', 'Property was abated for a CE case', 1, 1, 1, 'critical'),
  ('etp-ce-af', 'ce.appeal_filed', 'code_enforcement', 'Appeal Filed', 'An appeal was filed for a CE case', 1, 1, 1, 'info'),
  ('etp-ce-cl', 'ce.closed', 'code_enforcement', 'CE Case Closed', 'A code enforcement case was closed', 1, 0, 1, 'info'),
  -- Permit events
  ('etp-pm-cr', 'permit.created', 'permit', 'Permit Created', 'A building permit record was created', 1, 0, 1, 'info'),
  ('etp-pm-is', 'permit.issued', 'permit', 'Permit Issued', 'A building permit was issued', 1, 1, 1, 'info'),
  ('etp-pm-in', 'permit.inspection', 'permit', 'Inspection', 'An inspection was recorded on a permit', 1, 0, 1, 'info'),
  ('etp-pm-fi', 'permit.finalized', 'permit', 'Permit Finalized', 'A building permit was finalized', 1, 0, 1, 'info'),
  ('etp-pm-ex', 'permit.expired', 'permit', 'Permit Expired', 'A building permit expired', 1, 1, 1, 'warning'),
  -- Recon & analysis events
  ('etp-rc-st', 'recon.started', 'recon', 'Recon Started', 'Property intelligence recon began', 0, 0, 1, 'info'),
  ('etp-rc-cp', 'recon.completed', 'recon', 'Recon Completed', 'Property intelligence recon finished', 1, 1, 1, 'info'),
  ('etp-an-st', 'analysis.started', 'analysis', 'Analysis Started', 'Due-process analysis began', 0, 0, 1, 'info'),
  ('etp-an-cp', 'analysis.completed', 'analysis', 'Analysis Completed', 'Due-process analysis finished and findings generated', 1, 1, 1, 'info'),
  -- Case events
  ('etp-cs-cr', 'case.created', 'case', 'Case Created', 'A new case was created', 1, 1, 1, 'info'),
  ('etp-cs-up', 'case.updated', 'case', 'Case Updated', 'Case details were updated', 0, 0, 1, 'info'),
  ('etp-cs-cl', 'case.closed', 'case', 'Case Closed', 'A case was closed', 1, 1, 1, 'info'),
  -- Relationship events
  ('etp-rel-cr', 'relationship.created', 'relationship', 'Relationship Created', 'A typed relationship was created between entities', 0, 0, 1, 'info');

-- ═══════════════════════════════════════════════════════════════
-- RELATIONSHIP TYPE CATALOG
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS relationship_types (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  source_type TEXT,
  target_type TEXT,
  is_directed INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_reltypes_code ON relationship_types(code);

-- Seed relationship types
INSERT OR IGNORE INTO relationship_types (id, code, label, description, source_type, target_type) VALUES
  ('rt-sup-by', 'supported_by', 'Supported By', 'Finding is supported by this evidence', 'finding', 'evidence'),
  ('rt-man-by', 'mandated_by', 'Mandated By', 'Finding is mandated by this statute', 'finding', 'statute'),
  ('rt-gen-from', 'generated_from', 'Generated From', 'Event was generated from this source entity', 'event', 'evidence'),
  ('rt-is-by', 'issued_by', 'Issued By', 'Action was issued by this official', 'ce_case', 'official'),
  ('rt-mem-of', 'member_of', 'Member Of', 'Official is a member of this department', 'official', 'department'),
  ('rt-del-by', 'delegated_by', 'Delegated By', 'Department derives authority from this authority', 'department', 'authority'),
  ('rt-auth-by', 'authorized_by', 'Authorized By', 'Authority is established by this statute', 'authority', 'statute'),
  ('rt-refs', 'references', 'References', 'Entity references another entity', 'any', 'any'),
  ('rt-rel-to', 'relates_to', 'Relates To', 'Generic relationship between entities', 'any', 'any'),
  ('rt-trig-by', 'triggered_by', 'Triggered By', 'Event was triggered by this entity', 'event', 'any');
