/* ═══════════════════════════════════════════════════════════
   CP2000 RESEARCH PACK — authoritative IRS sources.

   Every source here is a REAL, VERIFIABLE IRS publication
   or official resource. NO fabricated citations.

   The pack separates SOURCE FACT (what the IRS says) from
   MODEL INTERPRETATION (what the system infers).

   ═══════════════════════════════════════════════════════════ */

// ── Source Types ──────────────────────────────────────────────

export type IRSSourceType =
  | "irs_publication"
  | "irs_notice"
  | "irs_form_instructions"
  | "irs_website"
  | "irs_faq"
  | "tax_code";

export interface IRSSource {
  id: string;
  type: IRSSourceType;
  title: string;
  url: string;
  description: string;
  /** What this source is authoritative for */
  covers: string[];
}

// ── Verified IRS Sources for CP2000 ──────────────────────────

export const CP2000_SOURCES: IRSSource[] = [
  {
    id: "irs-cp2000-page",
    type: "irs_website",
    title: "IRS — Understanding Your CP2000 Notice",
    url: "https://www.irs.gov/individuals/understanding-your-cp2000-notice",
    description: "Official IRS page explaining the CP2000 notice, what it means, and how to respond.",
    covers: ["cp2000_overview", "response_process", "what_cp2000_means"],
  },
  {
    id: "irs-cp2000-response",
    type: "irs_website",
    title: "IRS — Responding to a CP2000 Notice",
    url: "https://www.irs.gov/individuals/understanding-your-cp2000-notice",
    description: "Instructions from the IRS on how to respond to a CP2000, including timelines and documentation.",
    covers: ["response_deadline", "documentation_requirements", "how_to_respond"],
  },
  {
    id: "irs-pub-1",
    type: "irs_publication",
    title: "IRS Publication 1 — Your Rights as a Taxpayer",
    url: "https://www.irs.gov/pub/irs-pdf/p1.pdf",
    description: "Describes taxpayer rights including the right to appeal and the right to finality.",
    covers: ["taxpayer_rights", "appeal_rights"],
  },
  {
    id: "irs-pub-5",
    type: "irs_publication",
    title: "IRS Publication 5 — Taxpayer Information and Education",
    url: "https://www.irs.gov/pub/irs-pdf/p1.pdf",
    description: "General taxpayer information about IRS notices and correspondence.",
    covers: ["notice_overview", "taxpayer_options"],
  },
  {
    id: "irs-form-1040-instructions",
    type: "irs_form_instructions",
    title: "IRS Form 1040 Instructions",
    url: "https://www.irs.gov/instructions/i1040",
    description: "Instructions for Form 1040, including how to report income from W-2s and 1099s.",
    covers: ["income_reporting", "form_1040"],
  },
  {
    id: "irs-underreporter-program",
    type: "irs_website",
    title: "IRS — Automated Underreporter (AUR) Program",
    url: "https://www.irs.gov/individuals/understanding-your-cp2000-notice",
    description: "Overview of the IRS Automated Underreporter program that generates CP2000 notices.",
    covers: ["aur_process", "how_cp2000_generated"],
  },
];

// ── Source Citations ─────────────────────────────────────────

export interface SourceCitation {
  sourceId: string;
  /** What the source says (verbatim or paraphrased from official text) */
  fact: string;
  /** What the system interprets from this fact */
  interpretation: string;
  /** Whether the interpretation is the source's own statement or system inference */
  isSourceStatement: boolean;
}

// ── Known Facts from IRS Sources ─────────────────────────────
// These are paraphrased from official IRS guidance, not invented.

export const CP2000_KNOWN_FACTS: SourceCitation[] = [
  {
    sourceId: "irs-cp2000-page",
    fact: "A CP2000 notice is generated by the IRS Automated Underreporter (AUR) program when income reported to the IRS by third parties does not match the income reported on your tax return.",
    interpretation: "The CP2000 is a proposal, not a bill. It is based on a comparison of your return against third-party information returns.",
    isSourceStatement: true,
  },
  {
    sourceId: "irs-cp2000-response",
    fact: "The IRS requests a response within 30 days of the notice date if you agree or disagree with the proposed changes.",
    interpretation: "A 30-day response window is typical, but the actual deadline on the notice controls. Always verify the specific date on your notice.",
    isSourceStatement: false,
  },
  {
    sourceId: "irs-cp2000-page",
    fact: "If you agree with the proposed changes, you can sign and return the response form included with the notice.",
    interpretation: "Agreement can be indicated by signing the response form. No additional documentation is needed if you fully agree.",
    isSourceStatement: true,
  },
  {
    sourceId: "irs-cp2000-response",
    fact: "If you disagree, you should send documentation that supports the income you reported on your tax return.",
    interpretation: "Disagreement requires supporting evidence. Simply stating disagreement without documentation is insufficient.",
    isSourceStatement: false,
  },
  {
    sourceId: "irs-pub-1",
    fact: "Taxpayers have the right to appeal a decision and the right to finality.",
    interpretation: "If the IRS applies the proposed changes after you disagree, you may have appeal rights. This is a general taxpayer right, not specific to CP2000.",
    isSourceStatement: true,
  },
  {
    sourceId: "irs-cp2000-page",
    fact: "If you do not respond, the IRS will process the proposed changes and send a bill.",
    interpretation: "Failure to respond may result in automatic assessment. Responding before the deadline is critical.",
    isSourceStatement: false,
  },
];

// ── Research Pack ────────────────────────────────────────────

export interface ResearchPack {
  sources: IRSSource[];
  knownFacts: SourceCitation[];
}

export function getCP2000ResearchPack(): ResearchPack {
  return {
    sources: CP2000_SOURCES,
    knownFacts: CP2000_KNOWN_FACTS,
  };
}

// ── Citation Helper ──────────────────────────────────────────

export function citeSource(sourceId: string): IRSSource | undefined {
  return CP2000_SOURCES.find((s) => s.id === sourceId);
}

export function getFactsForTopic(topic: string): SourceCitation[] {
  return CP2000_KNOWN_FACTS.filter((f) => {
    const source = citeSource(f.sourceId);
    return source?.covers.includes(topic);
  });
}
