import type { MasterWorkflowDefinition } from "./workflow-definition";

const sharedCapabilities = [
  "document-classification",
  "fact-extraction",
  "deadline-analysis",
  "requirements-analysis",
  "evidence-analysis",
  "contradiction-analysis",
  "research",
  "response-strategy",
  "drafting",
  "draft-validation",
  "submission",
  "mailing",
  "proof",
] as const;

const sharedQualityGate = {
  documentRecognition: false,
  factGrounding: true,
  deadlineVerification: true,
  requirementCoverage: true,
  evidenceGrounding: true,
  draftValidation: true,
  submissionReadiness: true,
  proofReady: true,
};

export const noticeRespondCatalog: MasterWorkflowDefinition[] = [
  {
    id: "irs-notice",
    vertical: "notice-respond",
    lifecycle: "functional",
    title: "Respond to an IRS Notice",
    description: "Analyze an IRS notice, identify what it is asking for, organize supporting evidence, prepare a response, and preserve mailing proof.",
    disclaimer: "Notice Respond is a document and correspondence tool, not a law firm, CPA firm, or tax professional.",
    searchIntent: {
      primary: "respond to an IRS notice",
      secondary: ["IRS notice response", "IRS letter response", "IRS notice deadline"],
      canonicalPath: "/workflows/irs-notice",
      informationalEntryPoints: ["IRS notice", "IRS letter", "what does my IRS notice mean"],
      actionIntents: ["respond to IRS notice", "IRS notice response letter", "mail IRS response"],
    },
    documents: [
      { name: "IRS notice or letter", identifiers: ["CP", "LTR", "Notice"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["noticeType", "noticeDate", "responseDeadline", "taxYear", "amounts", "requestedActions", "mailingAddress", "contactInformation"] },
    ],
    deadlines: [{ id: "notice-response", label: "Response deadline shown on notice", trigger: "explicit deadline in notice", sourcePriority: ["uploaded notice", "official IRS source"], notes: ["Do not infer a deadline when the notice provides one."] }],
    requirements: [
      { id: "response-content", label: "Address each requested issue", type: "response", source: "uploaded notice", required: true },
      { id: "supporting-records", label: "Include relevant supporting documents", type: "document", source: "notice + user evidence", required: true },
      { id: "recipient", label: "Use the response address specified by the notice", type: "recipient", source: "uploaded notice", required: true },
    ],
    evidence: [
      { id: "tax-records", label: "Tax and income records", purpose: "Support or refute the issue identified in the notice", required: false, examples: ["W-2", "1099", "return", "payment record"] },
      { id: "correspondence", label: "Prior IRS correspondence", purpose: "Establish context and prior agency communications", required: false, examples: ["prior notices", "response letters"] },
    ],
    analysis: { capabilities: [...sharedCapabilities], orderedChecks: ["classify notice", "extract controlling dates", "identify requested action", "compare notice claims with uploaded evidence", "identify missing evidence", "prepare response strategy"], outputSections: ["notice summary", "deadline", "requested action", "facts", "evidence gaps", "response strategy"] },
    drafting: { requiredSections: ["recipient", "subject/reference", "response to notice", "fact-by-fact explanation", "supporting evidence list", "requested outcome", "contact information"], forbiddenBehavior: ["invent facts", "invent tax conclusions", "state uncertainty as fact"], validationChecks: ["every factual claim traceable to user evidence", "every requested issue addressed", "recipient matches notice"] },
    submission: { methods: ["mail"], recipientRules: ["use address from the notice unless user explicitly overrides after review"], proofRequirements: ["mailing record", "tracking when selected", "final approved document"] },
    capabilities: [...sharedCapabilities],
    qualityGate: sharedQualityGate,
  },
  {
    id: "court-summons",
    vertical: "notice-respond",
    lifecycle: "functional",
    title: "Respond to a Court Summons",
    description: "Analyze a summons or complaint, surface deadlines and filing instructions, organize facts and exhibits, and prepare the response package.",
    disclaimer: "Court filings can have strict procedural requirements. Notice Respond is not a law firm and does not provide legal advice.",
    searchIntent: {
      primary: "respond to a court summons",
      secondary: ["court summons response", "civil summons response", "answer a summons"],
      canonicalPath: "/workflows/court-summons",
      informationalEntryPoints: ["court summons", "what is a summons"],
      actionIntents: ["respond to court summons", "answer summons", "mail summons response"],
    },
    documents: [{ name: "Summons or complaint", identifiers: ["summons", "complaint", "case number"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["court", "caseNumber", "parties", "serviceDate", "responseDeadline", "filingInstructions", "address"] }],
    deadlines: [{ id: "court-response", label: "Court response deadline", trigger: "service date + controlling court rule OR explicit deadline", sourcePriority: ["court document", "official court rules"], notes: ["Rules vary by jurisdiction and case type."] }],
    requirements: [{ id: "filing-format", label: "Follow court filing instructions", type: "format", source: "court document and official court source", required: true }],
    evidence: [{ id: "case-record", label: "Case records", purpose: "Support factual response", required: false, examples: ["contracts", "communications", "receipts", "prior filings"] }],
    analysis: { capabilities: [...sharedCapabilities], orderedChecks: ["classify court document", "extract court and case", "determine response deadline source", "extract filing instructions", "identify factual issues", "identify exhibits and missing information"], outputSections: ["case summary", "deadline", "filing instructions", "issues", "evidence", "next actions"] },
    drafting: { requiredSections: ["caption/reference", "response", "factual statements", "requested relief", "signature/contact", "exhibit index when needed"], forbiddenBehavior: ["invent procedural rules", "claim legal representation", "state legal conclusions without support"], validationChecks: ["deadline source cited", "caption matches case document", "required sections present"] },
    submission: { methods: ["mail", "user-directed filing"], recipientRules: ["use the court address and filing instructions from the governing documents"], proofRequirements: ["final filing copy", "mailing record", "tracking when selected"] },
    capabilities: [...sharedCapabilities],
    qualityGate: { ...sharedQualityGate, documentRecognition: false },
  },
  {
    id: "agency-action",
    vertical: "notice-respond",
    lifecycle: "functional",
    title: "Respond to an Agency Action",
    description: "Respond to a regulatory, licensing, administrative, or agency action with source-linked facts, deadlines, evidence, and a reviewable response.",
    disclaimer: "Agency proceedings vary by jurisdiction. Notice Respond is not a law firm and does not provide legal advice.",
    searchIntent: {
      primary: "respond to a government agency notice",
      secondary: ["agency action response", "administrative notice response", "government agency letter response"],
      canonicalPath: "/workflows/agency-action",
      informationalEntryPoints: ["agency action", "government agency notice"],
      actionIntents: ["respond to agency action", "agency response letter", "government notice response"],
    },
    documents: [{ name: "Agency notice or determination", identifiers: ["notice", "determination", "order", "licensing action"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["agency", "actionType", "caseId", "issue", "deadline", "requestedResponse", "recipient"] }],
    deadlines: [{ id: "agency-response", label: "Agency response deadline", trigger: "explicit deadline or controlling agency rule", sourcePriority: ["uploaded notice", "official agency source"] }],
    requirements: [{ id: "agency-instructions", label: "Follow agency submission instructions", type: "format", source: "agency notice", required: true }],
    evidence: [{ id: "agency-record", label: "Agency record and supporting evidence", purpose: "Support the user's factual response", required: false, examples: ["prior correspondence", "licenses", "receipts", "photographs"] }],
    analysis: { capabilities: [...sharedCapabilities], orderedChecks: ["classify agency action", "extract deadline and instructions", "identify agency assertions", "map supporting facts", "surface contradictions and gaps", "select response strategy"], outputSections: ["action summary", "deadline", "agency assertions", "supporting facts", "gaps", "strategy"] },
    drafting: { requiredSections: ["recipient", "reference", "response", "fact and evidence sections", "requested outcome", "attachments"], forbiddenBehavior: ["invent agency requirements", "invent facts"], validationChecks: ["every agency assertion addressed or explicitly marked", "evidence references are accurate", "submission route matches instructions"] },
    submission: { methods: ["mail", "user-directed submission"], recipientRules: ["preserve the agency's specified recipient and delivery method"], proofRequirements: ["approved response", "submission record", "tracking when applicable"] },
    capabilities: [...sharedCapabilities],
    qualityGate: sharedQualityGate,
  },
  {
    id: "file-appeal",
    vertical: "notice-respond",
    lifecycle: "functional",
    title: "File an Appeal",
    description: "Turn a denial or decision into a structured appeal package with facts, evidence, deadline analysis, and a reviewed response.",
    disclaimer: "Appeal procedures and deadlines vary. Notice Respond is not a law firm and does not provide legal advice.",
    searchIntent: {
      primary: "write an appeal letter",
      secondary: ["appeal a government decision", "reconsideration letter", "denied claim appeal"],
      canonicalPath: "/workflows/file-appeal",
      informationalEntryPoints: ["appeal letter", "appeal letter sample", "how to appeal a decision"],
      actionIntents: ["write an appeal letter", "appeal a decision", "prepare an appeal"],
    },
    documents: [{ name: "Denial or decision", identifiers: ["denial", "decision", "determination", "ruling"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["decisionMaker", "decisionDate", "deadline", "reason", "appealInstructions", "recipient"] }],
    deadlines: [{ id: "appeal-deadline", label: "Appeal deadline", trigger: "explicit deadline or official appeal rule", sourcePriority: ["decision document", "official agency/court source"] }],
    requirements: [{ id: "appeal-ground", label: "Identify grounds or factual basis for appeal", type: "response", source: "decision + user evidence", required: true }],
    evidence: [{ id: "appeal-evidence", label: "Evidence supporting the appeal", purpose: "Support the requested reversal or reconsideration", required: true, examples: ["records", "correspondence", "photographs", "receipts", "prior decisions"] }],
    analysis: { capabilities: [...sharedCapabilities], orderedChecks: ["classify decision", "extract appeal deadline", "identify reasons for denial", "map facts to denial reasons", "identify missing support", "construct appeal strategy"], outputSections: ["decision summary", "deadline", "reasons", "evidence", "gaps", "appeal strategy"] },
    drafting: { requiredSections: ["recipient", "decision reference", "grounds", "supporting facts", "evidence", "requested outcome", "attachments"], forbiddenBehavior: ["invent legal authority", "invent facts", "guarantee outcome"], validationChecks: ["each denial reason addressed", "facts trace to evidence", "deadline and submission method verified"] },
    submission: { methods: ["mail", "user-directed submission"], recipientRules: ["use appeal instructions in the decision unless verified otherwise"], proofRequirements: ["final appeal", "mailing record", "delivery tracking when selected"] },
    capabilities: [...sharedCapabilities],
    qualityGate: sharedQualityGate,
  },
  {
    id: "cp2000-response",
    vertical: "notice-respond",
    lifecycle: "blueprint",
    title: "Respond to an IRS CP2000",
    description: "Analyze a CP2000 mismatch notice, compare the notice against supporting tax records, identify what needs to be explained, and prepare a response package.",
    disclaimer: "This workflow is a blueprint until its CP2000-specific extraction, research, and validation tests are complete. It is not tax advice.",
    searchIntent: {
      primary: "CP2000 response",
      secondary: ["CP2000 response letter", "respond to CP2000", "CP2000 notice deadline"],
      canonicalPath: "/workflows/cp2000-response",
      informationalEntryPoints: ["what is CP2000", "CP2000 notice", "CP2000 meaning"],
      actionIntents: ["CP2000 response", "respond to CP2000", "CP2000 response letter"],
    },
    documents: [{ name: "IRS CP2000 notice", identifiers: ["CP2000", "Automated Underreporter"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["noticeDate", "responseDeadline", "taxYear", "proposedChange", "reportedIncome", "incomeSource", "responseAddress"] }, { name: "Supporting tax record", identifiers: ["W-2", "1099", "return"], acceptedFormats: ["application/pdf", "image/*"], extractionFields: ["payer", "taxYear", "incomeAmount", "withholding"] }],
    deadlines: [{ id: "cp2000-response", label: "CP2000 response deadline", trigger: "date stated on CP2000 notice", sourcePriority: ["uploaded CP2000", "official IRS source"] }],
    requirements: [{ id: "cp2000-reconcile", label: "Explain or document the income mismatch", type: "response", source: "CP2000 + supporting tax records", required: true }, { id: "cp2000-address", label: "Use the response address shown on the notice", type: "recipient", source: "CP2000", required: true }],
    evidence: [{ id: "income-records", label: "Income reporting records", purpose: "Reconcile the discrepancy identified by the notice", required: true, examples: ["W-2", "1099", "broker statement", "return transcript"] }],
    analysis: { capabilities: [...sharedCapabilities], orderedChecks: ["classify CP2000", "extract tax year and amounts", "extract deadline", "compare notice amounts to uploaded records", "identify unresolved mismatches", "prepare response strategy"], outputSections: ["CP2000 summary", "amounts at issue", "deadline", "reconciliation", "evidence gaps", "response strategy"] },
    drafting: { requiredSections: ["CP2000 reference", "mismatch explanation", "supporting records", "requested correction", "attachments"], forbiddenBehavior: ["invent tax positions", "invent income records", "state a tax conclusion without evidence"], validationChecks: ["every amount reconciles to a source", "deadline comes from the notice", "response address matches the notice"] },
    submission: { methods: ["mail"], recipientRules: ["use the exact response address on the CP2000 unless a verified source indicates otherwise"], proofRequirements: ["approved response", "mailing record", "tracking when selected"] },
    capabilities: [...sharedCapabilities],
    qualityGate: { ...sharedQualityGate, documentRecognition: false, draftValidation: false },
  },
];

export const workflowById = Object.fromEntries(noticeRespondCatalog.map((workflow) => [workflow.id, workflow])) as Record<string, MasterWorkflowDefinition>;
