import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { SSDI_APPEAL_PRICING } from "@/domain/ssdi-appeal-gold";

export const Route = createFileRoute("/api/workflows/ssdi-appeal/approve")({server:{handlers:{POST:async({request})=>{
  try{
    const user=await requireAuthenticatedUser(request); const input=await request.json() as {appealId?:string;recipient?:{name?:string;address1?:string;address2?:string;city?:string;state?:string;zip?:string};mailingMethod?:"standard"|"certified"|"registered"}; if(!input.appealId)return Response.json({error:"Appeal id is required."},{status:400}); const r=input.recipient; if(!r?.name||!r.address1||!r.city||!r.state||!r.zip)return Response.json({error:"A complete mailing recipient is required."},{status:400}); if(!input.mailingMethod)return Response.json({error:"Mailing method is required."},{status:400});
    const supabase=await getSupabaseServer(); const {data:appeal,error}=await supabase.from("appeals").select("*").eq("id",input.appealId).single(); if(error||!appeal)return Response.json({error:"Appeal case not found."},{status:404}); if(appeal.user_id!==user.id)return Response.json({error:"You do not own this appeal."},{status:403}); if(appeal.workflow_id!=="ssdi-appeal")return Response.json({error:"Workflow mismatch."},{status:409}); if(!appeal.draft?.trim())return Response.json({error:"Draft is required before approval."},{status:409});
    const decision=appeal.decision||{}; const unresolved=Array.isArray(decision.authoritySources)?decision.authoritySources.filter((s:any)=>["unverified","conflicting"].includes(s.verificationState)):[]; const gaps=Array.isArray(decision.evidenceGaps)?decision.evidenceGaps:[]; const contradictions=Array.isArray(decision.contradictions)?decision.contradictions:[]; const review={score:Math.max(0,100-unresolved.length*8-gaps.length*4-contradictions.length*4),unresolvedAuthority:unresolved,evidenceGaps:gaps,contradictions,humanApprovalRequired:true,approvedAt:new Date().toISOString()}; if(review.score<70)return Response.json({error:"SSDI appeal is not ready for approval.",review},{status:409});
    const packet={id:crypto.randomUUID(),recipientName:r.name,recipientAddress1:r.address1,recipientAddress2:r.address2,recipientCity:r.city,recipientState:r.state,recipientZip:r.zip,mailingMethod:input.mailingMethod,workflowId:"ssdi-appeal",finalDocumentType:"response-pdf",pricing:{...SSDI_APPEAL_PRICING}};
    const {error:updateError}=await supabase.from("appeals").update({status:"ready",review,packet,version:(appeal.version||1)+1,updated_at:new Date().toISOString()}).eq("id",input.appealId).eq("user_id",user.id).eq("version",appeal.version||1); if(updateError)throw new Error(updateError.message);
    return Response.json({ok:true,appealId:input.appealId,status:"ready",review,packet});
  }catch(error){const message=error instanceof Error?error.message:"Unable to approve SSDI appeal.";return Response.json({error:message},{status:/authentication|required|token/i.test(message)?401:502});}
}}}});
