import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";

export const Route=createFileRoute("/api/workflows/ssdi-appeal/validate")({server:{handlers:{POST:async({request})=>{
  try{const user=await requireAuthenticatedUser(request);const input=await request.json() as {appealId?:string};if(!input.appealId)return Response.json({error:"Appeal id is required."},{status:400});const supabase=await getSupabaseServer();const {data:appeal,error}=await supabase.from("appeals").select("*").eq("id",input.appealId).single();if(error||!appeal)return Response.json({error:"Appeal case not found."},{status:404});if(appeal.user_id!==user.id)return Response.json({error:"You do not own this appeal."},{status:403});if(!appeal.draft?.trim())return Response.json({error:"Draft is required before validation."},{status:409});
    const token=process.env.MAILMYPDF_CONTROL_PLANE_TOKEN;const base=process.env.MAILMYPDF_CONTROL_PLANE_URL||"https://mailmypdf.com";if(!token)throw new Error("MailMyPDF control-plane token is not configured.");const cfgRes=await fetch(`${base.replace(/\/$/,"")}/api/control-plane/ai`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({verticalSlug:"appeal-mail",workflowSlug:"ssdi-appeal",task:"validation"})});const cfg=await cfgRes.json().catch(()=>null) as any;if(!cfgRes.ok)throw new Error(cfg?.error||`Control plane error (${cfgRes.status}).`);if(cfg.provider!=="gemini")throw new Error("SSDI Appeal validation is currently configured for Gemini.");
    const prompt=cfg.promptOverride||["Adversarially validate this SSDI appeal draft against the supplied decision analysis.","Return strict JSON only.","Identify unsupported medical/vocational assertions, incorrect dates, unsupported deadlines, unsupported filing instructions, recipient errors, missing evidence disclosures, contradictions, and requests for relief not grounded in the record.","Do not add new facts. Treat uncertainty as a blocking issue when material.",'{"pass":true,"score":0,"blockingIssues":[],"warnings":[],"unsupportedClaims":[],"dateIssues":[],"authorityIssues":[],"evidenceIssues":[],"recipientIssues":[],"summary":""}',"DECISION ANALYSIS:\n"+JSON.stringify(appeal.decision),"DRAFT:\n"+appeal.draft].join("\n\n");
    const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(cfg.model)}:generateContent?key=${encodeURIComponent(cfg.apiKey)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",temperature:0.1}})});const body=await response.json().catch(()=>null) as any;if(!response.ok)throw new Error(body?.error?.message||`Gemini validation failed (${response.status}).`);const text=body?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||"").join("").trim();if(!text)throw new Error("Gemini returned no validation result.");const validation=JSON.parse(text);await supabase.from("appeals").update({review:{...(appeal.review||{}),validation,validatedAt:new Date().toISOString()},updated_at:new Date().toISOString()}).eq("id",input.appealId).eq("user_id",user.id);return Response.json({ok:true,appealId:input.appealId,validation,provider:"gemini",model:cfg.model});
  }catch(error){const message=error instanceof Error?error.message:"Unable to validate SSDI appeal.";return Response.json({error:message},{status:/authentication|required|token/i.test(message)?401:502});}
}}}});
