/**
 * MailMyPDF Vertical Registry
 *
 * Single source of truth for user-facing solution verticals.
 * The reusable technology lives in the platform; customer-facing routes are
 * presented as MailMyPDF workflows rather than a separate umbrella brand.
 *
 * Product `status` controls navigation/lifecycle.
 * `executionState` controls Gold Standard execution certification and is kept
 * intentionally separate so a catalog/live route cannot masquerade as a Gold workflow.
 */

import type { VerticalDefinition, VerticalCategory, VerticalStatus } from "./types";

const makeVertical = (definition: Omit<VerticalDefinition, "seo">): VerticalDefinition => ({
  ...definition,
  seo: {
    title: `${definition.name} | MailMyPDF`,
    description: definition.description,
    canonical: definition.route,
    robots: definition.status === "live" ? "index,follow" : "noindex,nofollow",
  },
});

const disputeMail = makeVertical({ id: "dispute-mail", slug: "dispute-mail", name: "DisputeMail", shortName: "DisputeMail", tagline: "Dispute anything by mail.", description: "Turn a confusing dispute into a clear written response — then print and mail it without a printer.", category: "disputes", status: "live", executionState: "domain-ready", route: "https://mycomind4-arch-dispute-mail.pages.dev", icon: "ShieldAlert", primaryCTA: "Start a dispute", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const govReply = makeVertical({ id: "gov-reply", slug: "gov-reply", name: "GovReply", shortName: "GovReply", tagline: "Respond to government letters.", description: "Understand a government letter, organize the relevant documents, prepare a response, and mail it with an appropriate delivery record.", category: "government", status: "soon", executionState: "domain-ready", route: "https://govreply.pages.dev/", icon: "Landmark", primaryCTA: "Start a GovReply", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const appealReply = makeVertical({ id: "appeal-reply", slug: "appeal-reply", name: "AppealReply", shortName: "AppealReply", tagline: "Build and mail an appeal.", description: "Organize a decision, supporting documents, deadlines, and evidence into a response you can review before mailing.", category: "appeals", status: "live", executionState: "domain-ready", route: "https://mycomind4-arch-appeal-mail.pages.dev/", icon: "Scale", primaryCTA: "Start an Appeal", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const noticeResponse = makeVertical({ id: "notice-response", slug: "notice-response", name: "NoticeResponse", shortName: "NoticeResponse", tagline: "Respond to notices before deadlines.", description: "Understand an official notice, organize the timeline, prepare your response, and mail it before the stated deadline.", category: "government", status: "live", executionState: "domain-ready", route: "https://notice-respond.pages.dev", icon: "Clock", primaryCTA: "Start a Response", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: false, supportsMailing: true } });
const claimProof = makeVertical({ id: "claim-proof", slug: "claim-proof", name: "ClaimProof", shortName: "ClaimProof", tagline: "Organize and mail claim documentation.", description: "Compile claim documents, organize supporting evidence, prepare a cover letter, and mail a complete package.", category: "appeals", status: "live", executionState: "catalog", route: "/claim-proof", icon: "FileCheck", primaryCTA: "Start a Claim", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const tenantReply = makeVertical({ id: "tenant-reply", slug: "tenant-reply", name: "TenantReply", shortName: "TenantReply", tagline: "Respond to your landlord in writing.", description: "Organize a landlord or tenant notice, prepare a formal response, and create a documented mailing.", category: "housing", status: "live", executionState: "catalog", route: "/tenant-reply", icon: "Home", primaryCTA: "Start a Reply", enabled: true, capabilities: { requiresAI: true, requiresDocuments: false, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const permitReply = makeVertical({ id: "permit-reply", slug: "permit-reply", name: "PermitReply", shortName: "PermitReply", tagline: "Respond to permit notices and applications.", description: "Organize permit-related correspondence, supporting documents, and a response for review and delivery.", category: "government", status: "live", executionState: "domain-ready", route: "/permit-reply", icon: "FileText", primaryCTA: "Start a Response", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const benefitsAppeal = makeVertical({ id: "benefits-appeal", slug: "benefits-appeal", name: "BenefitsAppeal", shortName: "BenefitsAppeal", tagline: "Appeal a benefits denial.", description: "Organize a benefits decision, deadlines, and supporting evidence into an appeal you can review and mail.", category: "appeals", status: "live", executionState: "domain-ready", route: "/benefits-appeal", icon: "HeartPulse", primaryCTA: "Start an Appeal", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const debtDefense = makeVertical({ id: "debt-defense", slug: "debt-defense", name: "DebtDefense Mail", shortName: "DebtDefense", tagline: "Respond to debt collection in writing.", description: "Organize a collection notice and supporting information, prepare a written response, and mail it with an appropriate record.", category: "disputes", status: "live", executionState: "catalog", route: "https://mycomind4-arch-dispute-mail.pages.dev", icon: "ShieldCheck", primaryCTA: "Start a Response", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const recordsRequest = makeVertical({ id: "records-request", slug: "records-request", name: "RecordsRequest", shortName: "RecordsRequest", tagline: "Request public records by mail.", description: "Prepare a focused public records request, organize the request details, and mail it with a documented delivery workflow.", category: "government", status: "live", executionState: "executable", route: "/records-request", icon: "FolderOpen", primaryCTA: "Start a Request", enabled: true, capabilities: { requiresAI: true, requiresDocuments: false, supportsDrafting: true, supportsEvidence: false, supportsMailing: true } });


const privateOffice = makeVertical({ id: "private-office", slug: "private-office", name: "Private Office", shortName: "Private Office", tagline: "Professional correspondence, provably delivered.", description: "Organize high-stakes matters — contractor disputes, property insurance claims, bank and wire transfer disputes, trust beneficiary notices — with evidence, approval gates, and certified mailing.", category: "professional", status: "live", executionState: "domain-ready", route: "https://mycomind4-arch-mailmypdf-private-office.pages.dev/", icon: "Briefcase", primaryCTA: "Start a Matter", enabled: true, capabilities: { requiresAI: true, requiresDocuments: true, supportsDrafting: true, supportsEvidence: true, supportsMailing: true } });
const smallBusinessMail = makeVertical({ id: "small-business-mail", slug: "small-business-mail", name: "Small Business Mail", shortName: "Business Mail", tagline: "Business correspondence, sent on time.", description: "Create, schedule, track, and prove the documents your business sends with team approvals, templates, and a permanent proof archive.", category: "business", status: "live", executionState: "domain-ready", route: "https://mycomind4-arch-mailmypdf-smallbusiness.pages.dev/", icon: "Building2", primaryCTA: "Start a Mailing", enabled: true, capabilities: { requiresAI: false, requiresDocuments: true, supportsDrafting: true, supportsEvidence: false, supportsMailing: true } });

export const verticals: VerticalDefinition[] = [disputeMail, govReply, appealReply, noticeResponse, claimProof, tenantReply, permitReply, benefitsAppeal, debtDefense, recordsRequest, privateOffice, smallBusinessMail];
export function getVerticalBySlug(slug: string): VerticalDefinition | undefined { return verticals.find((v) => v.slug === slug); }
export function getVerticalByRoute(route: string): VerticalDefinition | undefined { return verticals.find((v) => v.route === route); }
export function getVerticalsByCategory(category: VerticalCategory): VerticalDefinition[] { return verticals.filter((v) => v.category === category); }
export function getVerticalsByStatus(status: VerticalStatus): VerticalDefinition[] { return verticals.filter((v) => v.status === status); }
export function getNavigationVerticals(): VerticalDefinition[] { return verticals.filter((v) => v.enabled); }
export function getLiveVerticals(): VerticalDefinition[] { return verticals.filter((v) => v.status === "live"); }
export function shouldIndexVertical(slug: string): boolean { const v = getVerticalBySlug(slug); return !!v && v.status === "live"; }
export function getVerticalsByCategoryForNav(): Array<{ category: VerticalCategory; verticals: VerticalDefinition[] }> { const categories: VerticalCategory[] = ["government", "appeals", "disputes", "housing", "professional", "business"]; return categories.map((category) => ({ category, verticals: getNavigationVerticals().filter((v) => v.category === category) })).filter((group) => group.verticals.length > 0); }
export function isVerticalLive(slug: string): boolean { return getVerticalBySlug(slug)?.status === "live"; }
