import { ADMINISTRATIVE_DECISION_PRICING } from "@/domain/administrative-decision-pricing";

export function AdministrativeDecisionPricing() {
  return <section className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Transparent pricing</p><h2 className="mt-2 text-2xl font-semibold">You pay for the work and the physical packet</h2></div><div className="text-3xl font-bold">From ${ADMINISTRATIVE_DECISION_PRICING.preparationFee.toFixed(2)} + mailing</div></div>
    <div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-widest text-slate-500">Preparation</div><div className="mt-2 font-semibold">${ADMINISTRATIVE_DECISION_PRICING.preparationFee.toFixed(2)}</div><p className="mt-1 text-xs text-slate-500">Analysis, drafting, validation, readiness.</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-widest text-slate-500">Response</div><div className="mt-2 font-semibold">First {ADMINISTRATIVE_DECISION_PRICING.includedResponsePages} sheets included</div><p className="mt-1 text-xs text-slate-500">Then ${ADMINISTRATIVE_DECISION_PRICING.responsePagePrice.toFixed(2)} per response sheet.</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-widest text-slate-500">Supporting documents</div><div className="mt-2 font-semibold">${ADMINISTRATIVE_DECISION_PRICING.supportingPagePrice.toFixed(2)} / sheet</div><p className="mt-1 text-xs text-slate-500">Only physical supporting pages are charged.</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-widest text-slate-500">Mailing</div><div className="mt-2 font-semibold">${ADMINISTRATIVE_DECISION_PRICING.standardMail.toFixed(2)} standard</div><p className="mt-1 text-xs text-slate-500">Certified ${ADMINISTRATIVE_DECISION_PRICING.certifiedMail.toFixed(2)} · Registered ${ADMINISTRATIVE_DECISION_PRICING.registeredMail.toFixed(2)}</p></div></div>
    <p className="mt-5 text-xs leading-5 text-slate-500">Your exact total is calculated after the final packet is assembled. Double-sided printing is counted by physical sheet, not PDF page count.</p>
  </section>;
}
