import type { GovReplyExtraction } from "@/domain/govreply";
export interface GovReplyExtractionResult { text: string; extraction: GovReplyExtraction; method: "pdf-text" | "unavailable"; }
export class GovReplyExtractionService {
  async extract(bytes: Uint8Array): Promise<GovReplyExtractionResult> { const text = await this.extractPdfText(bytes); if (!text.trim()) return { text: "", method: "unavailable", extraction: { agency: "irs", warnings: ["No selectable text could be recovered from this PDF. It may be scanned or image-only. Verify every field manually."] } }; return { text, method: "pdf-text", extraction: this.extractIrsFields(text) }; }
  private extractIrsFields(text: string): GovReplyExtraction {
    const normalized = text.replace(/\u0000/g, " ").replace(/\s+/g, " ").trim(); const warnings: string[] = [];
    const noticeType = normalized.match(/\b(CP\s?-?\d{3,5}|LTR\s?-?\d{3,5})\b/i)?.[1]?.replace(/\s+/g, "").toUpperCase() ?? null;
    const dates = [...normalized.matchAll(/\b(?:0?[1-9]|1[0-2])[\/-](?:0?[1-9]|[12]\d|3[01])[\/-](?:20)?\d{2}\b/g)].map((m) => this.toIsoDate(m[0]));
    const noticeDate = dates[0] ?? null; const referenceMatches = normalized.match(/\b(?:TIN|SSN|EIN|ACCOUNT|REFERENCE|NOTICE|CASE|CONTROL)[\s#:.-]*[A-Z0-9-]{5,}\b/gi) ?? [];
    const referenceNumbers = [...new Set(referenceMatches.map((value) => value.trim()))].slice(0, 10);
    const deadlineMatch = normalized.match(/(?:respond|response|reply|contact).{0,100}?(?:by|before|no later than)\s+(?:[A-Za-z]+\s+)?(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})/i);
    const responseDeadline = deadlineMatch?.[1] ? this.toIsoDate(deadlineMatch[1]) : null; const actionMatch = normalized.match(/(?:you must|please|we need you to|to respond).{0,240}/i); const summary = actionMatch?.[0]?.trim() ?? null;
    if (!noticeType) warnings.push("We could not confidently identify an IRS notice number."); if (!noticeDate) warnings.push("We could not confidently identify the notice date."); if (!responseDeadline) warnings.push("We could not confidently identify a response deadline. Check the notice carefully."); warnings.push("The extracted fields are suggestions only. Confirm them against the original notice before continuing.");
    return { agency: "irs", notice_type: noticeType, notice_type_confidence: noticeType ? 0.85 : 0, notice_date: noticeDate, response_deadline: responseDeadline, deadline_source: responseDeadline ? "extracted" : "unknown", reference_numbers: referenceNumbers, requested_actions: summary ? [summary] : [], summary_plain: summary, warnings };
  }
  private toIsoDate(value: string): string | null { const match = value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/); if (!match) return null; const month = Number(match[1]); const day = Number(match[2]); let year = Number(match[3]); if (year < 100) year += year >= 70 ? 1900 : 2000; const date = new Date(Date.UTC(year, month - 1, day)); if (date.getUTCFullYear() !== year || date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day) return null; return date.toISOString().slice(0, 10); }
  private async extractPdfText(bytes: Uint8Array): Promise<string> { const source = new TextDecoder("latin1").decode(bytes); const streams: string[] = []; const streamRegex = /stream\r?\n([\s\S]*?)\r?\nendstream/g; let match: RegExpExecArray | null; while ((match = streamRegex.exec(source))) { const raw = Uint8Array.from(match[1], (char) => char.charCodeAt(0)); const candidates: Uint8Array[] = [raw]; try { const stream = new Blob([raw]).stream().pipeThrough(new DecompressionStream("deflate")); candidates.push(new Uint8Array(await new Response(stream).arrayBuffer())); } catch {} for (const candidate of candidates) { const decoded = new TextDecoder("latin1").decode(candidate); const extracted = this.extractTextOperators(decoded); if (extracted) streams.push(extracted); } } return streams.join(" ").replace(/\s+/g, " ").trim(); }
  private extractTextOperators(stream: string): string { const chunks: string[] = []; const tjRegex = /\((?:\\.|[^\\)])*\)\s*T[Jj]/g; let match: RegExpExecArray | null; while ((match = tjRegex.exec(stream))) { const token = match[0].replace(/\s*T[Jj]$/, ""); if (token.startsWith("(")) chunks.push(this.decodePdfLiteral(token.slice(1, -1))); } const arrayRegex = /\[((?:\([^)]*\)|<[^>]+>|-?\d+(?:\.\d+)?\s*)+)\]\s*TJ/g; while ((match = arrayRegex.exec(stream))) { const literals = match[1].match(/\((?:\\.|[^\\)])*\)/g) ?? []; chunks.push(...literals.map((literal) => this.decodePdfLiteral(literal.slice(1, -1)))); } return chunks.join(" "); }
  private decodePdfLiteral(value: string): string { return value.replace(/\\([\\()])/g, "$1").replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "\t").replace(/\\([0-7]{1,3})/g, (_, octal: string) => String.fromCharCode(parseInt(octal, 8))); }
}
let singleton: GovReplyExtractionService | null = null; export function getGovReplyExtractionService() { singleton ??= new GovReplyExtractionService(); return singleton; }
