import type { GovReplyCase, GovReplyResponseDraft, GovReplyResponseFacts } from "@/domain/govreply";
function clean(value: string | null | undefined): string { return (value ?? "").trim(); }
export class GovReplyResponseService {
  async getResponseContext(caseId: string, token: string) { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data, error } = await supabaseAdmin.from("govreply_cases").select("*").eq("id", caseId).eq("public_token", token).maybeSingle(); if (error) throw new Error(error.message); if (!data) return null; const { data: draft } = await supabaseAdmin.from("govreply_response_drafts").select("*").eq("case_id", caseId).order("version", { ascending: false }).limit(1).maybeSingle(); return { case: data as GovReplyCase, draft: draft ? this.mapDraft(draft) : null }; }
  async generateDraft(caseId: string, token: string, facts: GovReplyResponseFacts) { const context = await this.getResponseContext(caseId, token); if (!context) throw new Error("Case not found."); if (context.case.status !== "awaiting_response" && context.case.status !== "draft_ready") throw new Error("Confirm the notice details before drafting a response."); return this.saveDraft(caseId, token, facts, this.buildDraft(context.case, facts)); }
  async saveDraft(caseId: string, token: string, facts: GovReplyResponseFacts, content: string) { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data: current } = await supabaseAdmin.from("govreply_response_drafts").select("version").eq("case_id", caseId).order("version", { ascending: false }).limit(1).maybeSingle(); const version = (current?.version ?? 0) + 1; const { data: draft, error } = await supabaseAdmin.from("govreply_response_drafts").insert({ case_id: caseId, version, status: "draft", facts, content }).select("*").single(); if (error) throw new Error(error.message); const caseData = await this.getCase(caseId, token); const { error: caseError } = await supabaseAdmin.from("govreply_cases").update({ status: "draft_ready", response_subject: this.subjectForCase(caseData), response_content: content, response_facts: facts, response_draft_id: draft.id }).eq("id", caseId).eq("public_token", token); if (caseError) throw new Error(caseError.message); await supabaseAdmin.from("govreply_events").insert({ case_id: caseId, type: "response.draft_saved", label: `Response draft v${version} saved`, metadata: { version } }); return this.mapDraft(draft); }
  async finalizeDraft(caseId: string, token: string, draftId: string, content: string) { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data: draft, error } = await supabaseAdmin.from("govreply_response_drafts").update({ status: "finalized", content }).eq("id", draftId).eq("case_id", caseId).select("*").maybeSingle(); if (error) throw new Error(error.message); if (!draft) throw new Error("Draft not found."); const now = new Date().toISOString(); const { error: caseError } = await supabaseAdmin.from("govreply_cases").update({ status: "draft_ready", response_content: content, response_finalized_at: now }).eq("id", caseId).eq("public_token", token); if (caseError) throw new Error(caseError.message); await supabaseAdmin.from("govreply_events").insert({ case_id: caseId, type: "response.finalized", label: "Response draft finalized by user", metadata: { draftId, version: draft.version } }); return this.mapDraft(draft); }
  private async getCase(caseId: string, token: string) { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data } = await supabaseAdmin.from("govreply_cases").select("*").eq("id", caseId).eq("public_token", token).maybeSingle(); return data as GovReplyCase | null; }
  private subjectForCase(caseData: GovReplyCase | null) { if (!caseData) return "Response to IRS Notice"; const notice = clean(caseData.extracted?.notice_type) || "IRS Notice"; const refs = caseData.reference_numbers?.[0]; return refs ? `Response to ${notice} — ${refs}` : `Response to ${notice}`; }
  private buildDraft(caseData: GovReplyCase, facts: GovReplyResponseFacts): string { const notice = clean(caseData.extracted?.notice_type) || "IRS notice"; const date = clean(caseData.notice_date); const refs = caseData.reference_numbers?.filter(Boolean).join(", "); const address = [caseData.response_mail_name, caseData.response_mail_line1, caseData.response_mail_line2, [caseData.response_mail_city, caseData.response_mail_state, caseData.response_mail_postal].filter(Boolean).join(", ")].filter(Boolean).join("\n"); return [clean(facts.taxpayerName) || "[Your full name]", clean(facts.taxpayerAddress) || "[Your mailing address]", "", new Date().toLocaleDateString("en-US"), "", address || "[IRS response address — verify against the original notice]", "", `Re: Response to ${notice}${refs ? ` — Reference ${refs}` : ""}`, "", "To Whom It May Concern:", "", `I am writing in response to the IRS notice identified above${date ? `, dated ${date}` : ""}. I am requesting that the IRS review the information described below and consider the supporting information I am providing with this response.`, "", "What happened:", clean(facts.whatHappened) || "[Describe the relevant facts and timeline.]", "", "My understanding of the notice:", clean(facts.whatTheyBelieve) || clean(caseData.requested_action_summary) || "[Describe what you understand the notice to be requesting.]", "", "What I am requesting:", clean(facts.whatUserWants) || "[State the specific action or correction you are requesting.]", "", "Supporting documents:", clean(facts.supportingDocuments) || "[List the documents enclosed with this response.]", "", clean(facts.additionalDetails) ? `Additional information:\n${clean(facts.additionalDetails)}` : "", "", "Thank you for reviewing this response and the accompanying documentation. Please update your records as appropriate and provide written confirmation of the outcome.", "", "Sincerely,", clean(facts.taxpayerName) || "[Your full name]", "", "Drafting note: This response was prepared from the information you supplied and the confirmed notice fields. Review every factual statement, attachment, address, and requested outcome before sending. GovReply is not providing legal advice."].filter((line, index, all) => line !== "" || (index > 0 && all[index - 1] !== "")).join("\n"); }
  private mapDraft(row: any): GovReplyResponseDraft { return { id: row.id, caseId: row.case_id, version: row.version, status: row.status, facts: row.facts, content: row.content, createdAt: row.created_at, updatedAt: row.updated_at }; }
}
let singleton: GovReplyResponseService | null = null; export function getGovReplyResponseService() { singleton ??= new GovReplyResponseService(); return singleton; }
