import { analyzeDisputeWorkflowInput, canApproveDispute, canAuthorizeDisputeMail, canCompleteDisputeProof, type DisputeAnalysis, type EvidenceItem } from "./gold-standard";
import { getWorkflowProfile } from "./workflow-profiles";
import type { WorkflowId } from "./workflows";

export interface WorkflowExecutionInput { workflowId: WorkflowId; documentId: string; text: string; facts?: Record<string, string | undefined>; evidenceStatuses?: Record<string, EvidenceItem["status"]>; objective?: string; }
export interface WorkflowConsequentialState { draftValidated: boolean; humanApproved: boolean; recipientComplete: boolean; paymentComplete: boolean; mailingSubmitted: boolean; trackingNumber: string | null; proofReady: boolean; }
export interface WorkflowExecutionResult { workflowId: WorkflowId; analysis: DisputeAnalysis; draft: string; stages: Array<{ stage: string; status: "passed" | "failed" | "blocked" | "skipped"; detail?: string; error?: string }>; ready: boolean; blocked: boolean; errors: string[]; warnings: string[]; }

function generateDraft(input: WorkflowExecutionInput, analysis: DisputeAnalysis): string {
  const profile = getWorkflowProfile(input.workflowId); const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const confirmedFacts = analysis.facts.map((fact) => `- ${fact.label}: ${fact.value}`).join("\n") || "- [Facts to be completed]";
  const evidence = analysis.evidence.map((item) => `- ${item.description} (${item.status})`).join("\n") || "- [Evidence to be supplied]";
  const strategy = analysis.strategy.map((item) => `- ${item}`).join("\n");
  return `[DRAFT — REVIEW BEFORE SENDING]\n\n${date}\n\n${profile.recipientRole}\n\nRe: ${profile.draftSubject}\n\nTo Whom It May Concern:\n\nI am writing regarding the matter described below. This correspondence is intended to create a clear factual record and request the following outcome:\n\n${input.objective ?? profile.objectivePrompt}\n\nRelevant facts:\n${confirmedFacts}\n\nSupporting evidence:\n${evidence}\n\nRequested resolution:\n${input.objective ?? profile.outcome}\n\nWorkflow guidance:\n${strategy}\n\nPlease review the enclosed information and provide a written response addressing the disputed issue and requested resolution.\n\nSincerely,\n[Your Name]\n[Your Address]\n[Your Phone]\n[Your Email]\n\n---\nDisclaimer: ${profile.disclaimer}\n`;
}

function validateDraft(draft: string, profileId: WorkflowId): { passed: boolean; errors: string[]; warnings: string[] } {
  const errors: string[] = []; const warnings: string[] = [];
  if (!draft.includes("Re:")) errors.push("Draft missing subject line"); if (!draft.includes("[Your Name]")) errors.push("Draft missing sender placeholder"); if (!draft.includes("Requested resolution")) errors.push(`Draft structure missing for workflow ${profileId}`); if (draft.includes("[Facts to be completed]") || draft.includes("[Evidence to be supplied]")) warnings.push("Draft contains incomplete intake placeholders");
  return { passed: errors.length === 0, errors, warnings };
}

export function runProfiledDisputeWorkflow(input: WorkflowExecutionInput, consequential?: WorkflowConsequentialState | null): WorkflowExecutionResult {
  const profile = getWorkflowProfile(input.workflowId); const stages: WorkflowExecutionResult["stages"] = []; const errors: string[] = []; const warnings: string[] = []; let blocked = false;
  stages.push({ stage: "secure-ingest", status: input.text.trim() ? "passed" : "failed", detail: input.text.trim() ? "source document available" : undefined, error: input.text.trim() ? undefined : "Source document required" }); if (!input.text.trim()) { blocked = true; errors.push("secure-ingest: source document required"); }
  const analysis = analyzeDisputeWorkflowInput({ documentId: input.documentId, text: input.text, profile, workflowFacts: input.facts, evidenceStatuses: input.evidenceStatuses, objective: input.objective });
  stages.push({ stage: "classify", status: analysis.classification.confidence > 0 ? "passed" : "failed", detail: profile.problem }); stages.push({ stage: "extract", status: analysis.facts.length > 0 ? "passed" : "failed", detail: `${analysis.facts.length} supplied facts` }); stages.push({ stage: "facts-provenance", status: analysis.facts.length > 0 ? "passed" : "failed", detail: "facts retain source excerpts when supplied" }); stages.push({ stage: "timeline-deadlines", status: "passed", detail: profile.deadlinePolicy }); stages.push({ stage: "issues-discrepancies", status: analysis.findings.length > 0 ? "passed" : "failed", detail: `${analysis.findings.length} findings` }); stages.push({ stage: "evidence", status: analysis.evidence.length > 0 ? "passed" : "failed", detail: `${analysis.evidence.length} evidence requirements` }); stages.push({ stage: "strategy", status: analysis.strategy.length > 0 ? "passed" : "failed", detail: `${analysis.strategy.length} strategy points` });
  if (analysis.blockingIssues.length > 0) { blocked = true; errors.push(...analysis.blockingIssues.map((issue) => `blocking: ${issue}`)); stages.push({ stage: "blocking-gates", status: "failed", error: analysis.blockingIssues.join("; ") }); } else stages.push({ stage: "blocking-gates", status: "passed", detail: "no blocking intake issues" });
  let draft = "";
  if (!blocked) { draft = generateDraft(input, analysis); stages.push({ stage: "draft", status: "passed", detail: `${draft.length} chars` }); stages.push({ stage: "draft-provenance", status: "passed", detail: `${analysis.facts.length} source facts` }); const validation = validateDraft(draft, input.workflowId); stages.push({ stage: "validate", status: validation.passed ? "passed" : "failed", detail: `${validation.errors.length} errors, ${validation.warnings.length} warnings`, error: validation.passed ? undefined : validation.errors.join("; ") }); if (!validation.passed) { blocked = true; errors.push(...validation.errors.map((error) => `validation: ${error}`)); } warnings.push(...validation.warnings); } else { stages.push({ stage: "draft", status: "blocked" }); stages.push({ stage: "draft-provenance", status: "blocked" }); stages.push({ stage: "validate", status: "blocked" }); }
  if (blocked) { stages.push({ stage: "human-review", status: "blocked" }); stages.push({ stage: "approval", status: "blocked" }); stages.push({ stage: "authorized-mail", status: "blocked" }); stages.push({ stage: "track", status: "blocked" }); stages.push({ stage: "prove-audit", status: "blocked" }); }
  else if (!consequential) { stages.push({ stage: "human-review", status: "skipped", detail: "consequential state not supplied" }); stages.push({ stage: "approval", status: "skipped", detail: "consequential state not supplied" }); stages.push({ stage: "authorized-mail", status: "skipped", detail: "consequential state not supplied" }); stages.push({ stage: "track", status: "skipped", detail: "consequential state not supplied" }); stages.push({ stage: "prove-audit", status: "skipped", detail: "consequential state not supplied" }); }
  else { const canApprove = canApproveDispute(analysis); stages.push({ stage: "human-review", status: canApprove ? "passed" : "failed", error: canApprove ? undefined : "Unresolved evidence or findings block review" }); if (!canApprove) { blocked = true; errors.push("human-review: unresolved evidence or findings"); stages.push({ stage: "approval", status: "blocked" }); stages.push({ stage: "authorized-mail", status: "blocked" }); stages.push({ stage: "track", status: "blocked" }); stages.push({ stage: "prove-audit", status: "blocked" }); } else { stages.push({ stage: "approval", status: consequential.humanApproved ? "passed" : "failed", error: consequential.humanApproved ? undefined : "Explicit human approval required" }); if (!consequential.humanApproved) { blocked = true; errors.push("approval: explicit human approval required"); stages.push({ stage: "authorized-mail", status: "blocked" }); stages.push({ stage: "track", status: "blocked" }); stages.push({ stage: "prove-audit", status: "blocked" }); } else { const authorized = canAuthorizeDisputeMail({ analysis, draftValidated: consequential.draftValidated, humanApproved: consequential.humanApproved, recipientComplete: consequential.recipientComplete, paymentComplete: consequential.paymentComplete }); const submissionOk = authorized && consequential.mailingSubmitted; stages.push({ stage: "authorized-mail", status: submissionOk ? "passed" : "failed", error: submissionOk ? undefined : "Validation, approval, recipient, payment, or provider submission incomplete" }); if (!submissionOk) { blocked = true; errors.push("authorized-mail: fulfillment prerequisites incomplete"); stages.push({ stage: "track", status: "blocked" }); stages.push({ stage: "prove-audit", status: "blocked" }); } else { const tracked = Boolean(consequential.trackingNumber); stages.push({ stage: "track", status: tracked ? "passed" : "failed", detail: tracked ? `tracking=${consequential.trackingNumber}` : undefined, error: tracked ? undefined : "Tracking number missing" }); const proofOk = canCompleteDisputeProof({ trackingNumber: consequential.trackingNumber, proofReady: consequential.proofReady }); stages.push({ stage: "prove-audit", status: proofOk ? "passed" : "failed", error: proofOk ? undefined : "Proof of mailing is not ready" }); if (!proofOk) { blocked = true; errors.push("prove-audit: tracking or proof missing"); } } } } }
  return { workflowId: input.workflowId, analysis, draft, stages, ready: !blocked && errors.length === 0, blocked, errors, warnings };
}
