/* ═══════════════════════════════════════════════════════════
   WORKFLOW MASTER REGISTRY

   The canonical database of every workflow in the MailMyPDF
   ecosystem — across all verticals, engines, and domain packs.

   Each entry contains:
   - vertical/category classification
   - engine assignment
   - lifecycle status
   - priority metrics (NEVER invented — keyword metrics are null/TBD)
   - test status
   - deployment status

   Workflows are added here as blueprints first, then promoted to
   functional and authority as they are actually implemented.

   ═══════════════════════════════════════════════════════════ */

import type { WorkflowEngine, WorkflowLifecycle } from "./workflow-definition";

export interface WorkflowRegistryEntry {
  id: string;
  vertical: string;
  category: string;
  engine: WorkflowEngine;
  lifecycle: WorkflowLifecycle;
  title: string;
  canonicalKeyword: string;
  keywordCluster: string[];
  /** Keyword.com metrics — NEVER invented. null = not yet researched */
  msv: number | null;
  cpc: number | null;
  competition: number | null;
  /** SEO URL */
  seoUrl: string;
  /** Repository owning the implementation */
  repo: string;
  /** Product status */
  productStatus: "planned" | "scaffolded" | "functional" | "authority";
  /** Test status */
  testStatus: "none" | "partial" | "passing";
  /** Deployment status */
  deploymentStatus: "none" | "staging" | "production";
  /** Factory reuse score (0-1): how much reuses existing engine capabilities */
  factoryReuseScore: number;
  /** Implementation difficulty (1-5) */
  implementationDifficulty: number;
  /** Priority in build queue */
  priority: "critical" | "high" | "medium" | "low";
  /** Whether keyword research is still required */
  researchRequired: boolean;
}

// ── Registry ──────────────────────────────────────────────────

export const WORKFLOW_REGISTRY: WorkflowRegistryEntry[] = [
  // ═══ ENGINE A: Document → Action ═══

  // — IRS Notices (existing, implemented in notice-respond) —
  {
    id: "cp2000-response",
    vertical: "notice-respond",
    category: "IRS notices",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an IRS CP2000 Notice",
    canonicalKeyword: "CP2000",
    keywordCluster: ["CP2000", "IRS CP2000", "CP2000 notice", "respond to CP2000", "CP2000 response", "CP2000 response letter", "how to respond to CP2000", "CP2000 discrepancy"],
    msv: 1900,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/cp2000-response",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 3,
    priority: "critical",
    researchRequired: true,
  },
  {
    id: "cp14-response",
    vertical: "notice-respond",
    category: "IRS notices",
    engine: "document-action",
    lifecycle: "authority",
    title: "Respond to an IRS CP14 Notice",
    canonicalKeyword: "CP14",
    keywordCluster: ["CP14", "IRS CP14", "CP14 notice", "respond to CP14"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/cp14-response",
    repo: "notice-respond",
    productStatus: "authority",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.85,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "irs-notice",
    vertical: "notice-respond",
    category: "IRS notices",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an IRS Notice",
    canonicalKeyword: "IRS notice response",
    keywordCluster: ["IRS notice", "IRS letter", "respond to IRS notice"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/irs-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.95,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "court-summons",
    vertical: "notice-respond",
    category: "Court notices",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a Court Summons",
    canonicalKeyword: "respond to court summons",
    keywordCluster: ["court summons", "summons response", "answer summons"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/court-summons",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.8,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "agency-action",
    vertical: "notice-respond",
    category: "Agency notices",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an Agency Action",
    canonicalKeyword: "agency action response",
    keywordCluster: ["agency action", "agency notice", "government notice response"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/agency-action",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "file-appeal",
    vertical: "notice-respond",
    category: "Appeals",
    engine: "appeal",
    lifecycle: "functional",
    title: "File an Appeal",
    canonicalKeyword: "appeal letter",
    keywordCluster: ["appeal letter", "file an appeal", "appeal a decision"],
    msv: 1300,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/file-appeal",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.7,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },

  // — Immigration (Engine A: document-action) —
  {
    id: "i-797-analysis",
    vertical: "immigration-mail",
    category: "Immigration",
    engine: "document-action",
    lifecycle: "blueprint",
    title: "I-797 Analysis",
    canonicalKeyword: "I-797",
    keywordCluster: ["I-797", "Form I-797", "I-797 notice", "I-797 approval"],
    msv: 18100,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/i-797-analysis",
    repo: "immigration-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "i-797c-analysis",
    vertical: "immigration-mail",
    category: "Immigration",
    engine: "document-action",
    lifecycle: "blueprint",
    title: "I-797C Analysis",
    canonicalKeyword: "I-797C",
    keywordCluster: ["I-797C", "I-797C notice", "I-797C notice of action"],
    msv: 8100,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/i-797c-analysis",
    repo: "immigration-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "uscis-rfe-response",
    vertical: "immigration-mail",
    category: "Immigration",
    engine: "document-action",
    lifecycle: "blueprint",
    title: "USCIS RFE Response",
    canonicalKeyword: "USCIS RFE",
    keywordCluster: ["USCIS RFE", "request for evidence", "RFE response"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/uscis-rfe-response",
    repo: "immigration-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.65,
    implementationDifficulty: 4,
    priority: "high",
    researchRequired: true,
  },

  // ═══ ENGINE B: Dispute ═══

  // — Credit Report Disputes —
  {
    id: "transunion-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "functional",
    title: "TransUnion Dispute",
    canonicalKeyword: "TransUnion dispute",
    keywordCluster: ["TransUnion dispute", "dispute TransUnion", "TransUnion credit dispute"],
    msv: 12100,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/transunion-dispute",
    repo: "dispute-mail",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "critical",
    researchRequired: true,
  },
  {
    id: "experian-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "functional",
    title: "Experian Dispute",
    canonicalKeyword: "Experian dispute",
    keywordCluster: ["Experian dispute", "dispute Experian", "Experian credit dispute"],
    msv: 8100,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/experian-dispute",
    repo: "dispute-mail",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 1,
    priority: "critical",
    researchRequired: true,
  },
  {
    id: "equifax-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "functional",
    title: "Equifax Dispute",
    canonicalKeyword: "Equifax dispute",
    keywordCluster: ["Equifax dispute", "dispute Equifax", "Equifax credit dispute"],
    msv: 6600,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/equifax-dispute",
    repo: "dispute-mail",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.95,
    implementationDifficulty: 1,
    priority: "critical",
    researchRequired: true,
  },
  {
    id: "credit-report-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Credit Report Dispute",
    canonicalKeyword: "credit report dispute",
    keywordCluster: ["credit report dispute", "dispute credit report", "credit report errors"],
    msv: 6600,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/credit/credit-report-dispute",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.9,
    implementationDifficulty: 3,
    priority: "critical",
    researchRequired: true,
  },
  {
    id: "lexisnexis-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "LexisNexis Dispute",
    canonicalKeyword: "LexisNexis dispute",
    keywordCluster: ["LexisNexis dispute", "dispute LexisNexis"],
    msv: 1900,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/credit/lexisnexis",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "hard-inquiry-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Hard Inquiry Dispute",
    canonicalKeyword: "hard inquiry removal",
    keywordCluster: ["hard inquiry removal", "dispute hard inquiry", "remove hard inquiry"],
    msv: 880,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/credit/hard-inquiry",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "collection-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Collection Dispute",
    canonicalKeyword: "dispute collection",
    keywordCluster: ["dispute collection", "collection dispute", "dispute collection agency"],
    msv: 1300,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/credit/collection-dispute",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "fcra-dispute",
    vertical: "dispute-mail",
    category: "Credit disputes",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "FCRA Dispute",
    canonicalKeyword: "FCRA dispute",
    keywordCluster: ["FCRA dispute", "Fair Credit Reporting Act dispute"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/credit/fcra-dispute",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },

  // ═══ ENGINE B: Dispute — Debt Collection Defense ═══

  {
    id: "debt-collection-dispute",
    vertical: "dispute-mail",
    category: "Debt defense",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Debt Collection Dispute",
    canonicalKeyword: "debt collection dispute",
    keywordCluster: ["debt collection dispute", "dispute debt collection", "debt dispute"],
    msv: 1300,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/debt/debt-collection-dispute",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "debt-validation",
    vertical: "dispute-mail",
    category: "Debt defense",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Debt Validation Letter",
    canonicalKeyword: "debt validation letter",
    keywordCluster: ["debt validation letter", "debt validation", "validate debt"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/debt/debt-validation",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "fdcpa-dispute",
    vertical: "dispute-mail",
    category: "Debt defense",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "FDCPA Dispute",
    canonicalKeyword: "FDCPA dispute",
    keywordCluster: ["FDCPA dispute", "FDCPA dispute letter", "Fair Debt Collection Practices Act"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/debt/fdcpa-dispute",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "debt-lawsuit-response",
    vertical: "dispute-mail",
    category: "Debt defense",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Debt Lawsuit Response",
    canonicalKeyword: "debt lawsuit response",
    keywordCluster: ["debt lawsuit response", "answer debt lawsuit", "respond to debt lawsuit"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/debt/debt-lawsuit-response",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 4,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "collection-cease-contact",
    vertical: "dispute-mail",
    category: "Debt defense",
    engine: "dispute",
    lifecycle: "blueprint",
    title: "Collection Cease Contact Letter",
    canonicalKeyword: "collection cease contact",
    keywordCluster: ["cease contact", "cease and desist collection", "stop collection calls"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/dispute-mail/debt/cease-contact",
    repo: "dispute-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 1,
    priority: "medium",
    researchRequired: true,
  },

  // ═══ ENGINE D: Appeal — Insurance ═══

  {
    id: "insurance-claim-denied",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Insurance Claim Denied",
    canonicalKeyword: "insurance claim denied",
    keywordCluster: ["insurance claim denied", "denied insurance claim", "insurance denial"],
    msv: 1300,
    cpc: 47,
    competition: null,
    seoUrl: "/appeal-mail/insurance/claim-denied",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "insurance-claim-appeal",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Insurance Claim Appeal",
    canonicalKeyword: "appealing insurance denial",
    keywordCluster: ["appealing insurance denial", "insurance appeal", "insurance appeal letter"],
    msv: 260,
    cpc: 34,
    competition: null,
    seoUrl: "/appeal-mail/insurance/claim-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "health-insurance-denial",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Health Insurance Denial Appeal",
    canonicalKeyword: "health insurance denial",
    keywordCluster: ["health insurance denial", "medical insurance denial", "health insurance appeal"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/insurance/health-denial",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "roof-claim-denied",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Roof Insurance Claim Denied",
    canonicalKeyword: "roof insurance claim denied",
    keywordCluster: ["roof insurance claim denied", "roof claim denial", "roof damage insurance"],
    msv: 320,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/insurance/roof-claim-denied",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "workers-comp-denied",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Workers Compensation Denied",
    canonicalKeyword: "workers comp denied claim",
    keywordCluster: ["workers comp denied", "workers compensation denied", "workers comp appeal"],
    msv: 210,
    cpc: 45,
    competition: null,
    seoUrl: "/appeal-mail/insurance/workers-comp-denied",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "life-insurance-claim-denied",
    vertical: "appeal-mail",
    category: "Insurance appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Life Insurance Claim Denied",
    canonicalKeyword: "life insurance claim denied",
    keywordCluster: ["life insurance claim denied", "life insurance denial", "life insurance appeal"],
    msv: 210,
    cpc: 18,
    competition: null,
    seoUrl: "/appeal-mail/insurance/life-claim-denied",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },

  // ═══ ENGINE D: Appeal — Financial Aid / Government ═══

  {
    id: "financial-aid-appeal",
    vertical: "appeal-mail",
    category: "Financial aid appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Financial Aid Appeal",
    canonicalKeyword: "financial aid appeal letter",
    keywordCluster: ["financial aid appeal", "financial aid appeal letter", "FAFSA appeal"],
    msv: 1000,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/financial-aid/appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "sap-appeal",
    vertical: "appeal-mail",
    category: "Financial aid appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "SAP Appeal",
    canonicalKeyword: "SAP appeal",
    keywordCluster: ["SAP appeal", "satisfactory academic progress appeal", "SAP appeal sample"],
    msv: 390,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/financial-aid/sap-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "ssdi-appeal",
    vertical: "appeal-mail",
    category: "Government appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "SSDI Appeal",
    canonicalKeyword: "appeal SSDI denial",
    keywordCluster: ["appeal SSDI denial", "SSDI appeal", "social security disability appeal"],
    msv: 260,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/government/ssdi-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "ssi-appeal",
    vertical: "appeal-mail",
    category: "Government appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "SSI Appeal",
    canonicalKeyword: "SSI denial",
    keywordCluster: ["SSI denial", "SSI appeal", "supplemental security income appeal"],
    msv: 210,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/government/ssi-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "unemployment-appeal",
    vertical: "appeal-mail",
    category: "Government appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Unemployment Appeal",
    canonicalKeyword: "unemployment appeal",
    keywordCluster: ["unemployment appeal", "unemployment denial appeal", "unemployment appeal letter"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/government/unemployment-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "medicaid-appeal",
    vertical: "appeal-mail",
    category: "Government appeals",
    engine: "appeal",
    lifecycle: "blueprint",
    title: "Medicaid Appeal",
    canonicalKeyword: "Medicaid appeal",
    keywordCluster: ["Medicaid appeal", "Medicaid denial appeal", "Medicaid fair hearing"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/appeal-mail/government/medicaid-appeal",
    repo: "appeal-mail",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.75,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },

  // ═══ ENGINE C: Records ═══

  {
    id: "police-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Police Records Request",
    canonicalKeyword: "police records request",
    keywordCluster: ["police records request", "police report request", "get police report"],
    msv: 1600,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/police-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "police-report-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Police Report Request",
    canonicalKeyword: "how to get police reports",
    keywordCluster: ["how to get police reports", "police report request", "get police report"],
    msv: 6600,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/police-report-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "public-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Public Records Request",
    canonicalKeyword: "public records request",
    keywordCluster: ["public records request", "public records", "government records request"],
    msv: 3600,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/public-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "open-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Open Records Request",
    canonicalKeyword: "open records request",
    keywordCluster: ["open records request", "open records", "open records law"],
    msv: 1900,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/open-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "foia-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "FOIA Request",
    canonicalKeyword: "FOIA request",
    keywordCluster: ["FOIA request", "Freedom of Information Act", "FOIA letter"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/foia-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "court-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Court Records Request",
    canonicalKeyword: "court records request",
    keywordCluster: ["court records", "court records request", "get court records"],
    msv: 1900,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/court-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.8,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "arrest-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Arrest Records Request",
    canonicalKeyword: "arrest records request",
    keywordCluster: ["arrest records", "arrest records request", "get arrest records"],
    msv: 1600,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/arrest-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "birth-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Birth Records Request",
    canonicalKeyword: "birth records request",
    keywordCluster: ["birth records", "birth certificate request", "get birth records"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/birth-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "marriage-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Marriage Records Request",
    canonicalKeyword: "marriage records request",
    keywordCluster: ["marriage records", "marriage certificate request", "get marriage records"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/marriage-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "property-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Property Records Request",
    canonicalKeyword: "property records request",
    keywordCluster: ["property records", "property records request", "get property records"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/property-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "low",
    researchRequired: true,
  },
  {
    id: "permit-records-request",
    vertical: "records-requests",
    category: "Records requests",
    engine: "records",
    lifecycle: "blueprint",
    title: "Permit Records Request",
    canonicalKeyword: "permit records request",
    keywordCluster: ["permit records", "permit records request", "get permit records"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/records-requests/permit-records-request",
    repo: "records-requests",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "low",
    researchRequired: true,
  },

  // ═══ ENGINE E: Jurisdictional Correspondence ═══

  {
    id: "code-enforcement-notice",
    vertical: "code-enforcement",
    category: "Jurisdictional",
    engine: "jurisdictional",
    lifecycle: "blueprint",
    title: "Respond to a Code Enforcement Notice",
    canonicalKeyword: "code enforcement notice",
    keywordCluster: ["code enforcement notice", "code violation notice", "respond to code enforcement"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/code-enforcement/respond-to-notice",
    repo: "code-enforcement",
    productStatus: "scaffolded",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "medium",
    researchRequired: true,
  },
  {
    id: "tenant-notice-response",
    vertical: "tenant-reply",
    category: "Jurisdictional",
    engine: "jurisdictional",
    lifecycle: "blueprint",
    title: "Respond to a Tenant Notice",
    canonicalKeyword: "tenant notice response",
    keywordCluster: ["tenant notice", "landlord notice response", "eviction notice response"],
    msv: null,
    cpc: null,
    competition: null,
    seoUrl: "/workflows/tenant-notice-response",
    repo: "tenant-reply",
    productStatus: "planned",
    testStatus: "none",
    deploymentStatus: "none",
    factoryReuseScore: 0.7,
    implementationDifficulty: 3,
    priority: "low",
    researchRequired: true,
  },
  {
    id: "cp504-response",
    vertical: "notice-respond",
    category: "Tax",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an IRS CP504 Notice (Intent to Levy)",
    canonicalKeyword: "CP504 response",
    keywordCluster: ["CP504", "IRS intent to levy", "CP504 CDP hearing", "IRS levy notice"],
    msv: 1900,
    cpc: 13,
    competition: "medium",
    seoUrl: "/workflows/cp504-response",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: false,
  },
  {
    id: "cp523-response",
    vertical: "notice-respond",
    category: "Tax",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an IRS CP523 Notice (Installment Agreement Default)",
    canonicalKeyword: "CP523 notice",
    keywordCluster: ["CP523", "IRS CP523", "installment agreement default", "intent to levy", "CP523 response"],
    msv: 390,
    cpc: 26,
    competition: "low",
    seoUrl: "/workflows/cp523-response",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.85,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: false,
  },  {
    id: "tax-notice",
    vertical: "notice-respond",
    category: "Tax",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a Tax Notice",
    canonicalKeyword: "respond to tax notice",
    keywordCluster: ["tax notice", "tax authority letter", "tax correspondence response"],
    msv: 2900,
    cpc: 14,
    competition: "medium",
    seoUrl: "/workflows/tax-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: false,
  },
  {
    id: "code-enforcement",
    vertical: "notice-respond",
    category: "Property & local government",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a Code Enforcement Notice",
    canonicalKeyword: "respond to code enforcement notice",
    keywordCluster: ["code enforcement", "municipal violation", "property compliance notice"],
    msv: 720,
    cpc: 8,
    competition: "low",
    seoUrl: "/workflows/code-enforcement",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: false,
  },
  {
    id: "permit-correction",
    vertical: "notice-respond",
    category: "Property & local government",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a Permit Correction Notice",
    canonicalKeyword: "respond to permit correction notice",
    keywordCluster: ["permit correction", "planning department notice", "building permit resubmission"],
    msv: 480,
    cpc: 7,
    competition: "low",
    seoUrl: "/workflows/permit-correction",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: false,
  },
  {
    id: "dmv-notice",
    vertical: "notice-respond",
    category: "State agencies",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a DMV Notice",
    canonicalKeyword: "respond to DMV notice",
    keywordCluster: ["DMV notice", "license suspension", "vehicle registration notice"],
    msv: 1600,
    cpc: 9,
    competition: "medium",
    seoUrl: "/workflows/dmv-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: false,
  },
  {
    id: "ssa-notice",
    vertical: "notice-respond",
    category: "Benefits & identity",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to an SSA Notice",
    canonicalKeyword: "respond to SSA notice",
    keywordCluster: ["SSA notice", "Social Security determination", "benefits appeal"],
    msv: 1300,
    cpc: 11,
    competition: "medium",
    seoUrl: "/workflows/ssa-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: false,
  },
  {
    id: "uscis-notice",
    vertical: "notice-respond",
    category: "Immigration",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a USCIS Notice",
    canonicalKeyword: "respond to USCIS notice",
    keywordCluster: ["USCIS RFE", "USCIS notice", "immigration evidence request"],
    msv: 880,
    cpc: 18,
    competition: "medium",
    seoUrl: "/workflows/uscis-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: false,
  },
  {
    id: "benefits-notice",
    vertical: "notice-respond",
    category: "Benefits & identity",
    engine: "document-action",
    lifecycle: "functional",
    title: "Respond to a Benefits Notice",
    canonicalKeyword: "respond to benefits notice",
    keywordCluster: ["benefits notice", "overpayment notice", "eligibility determination"],
    msv: 1100,
    cpc: 10,
    competition: "medium",
    seoUrl: "/workflows/benefits-notice",
    repo: "notice-respond",
    productStatus: "functional",
    testStatus: "passing",
    deploymentStatus: "production",
    factoryReuseScore: 0.9,
    implementationDifficulty: 2,
    priority: "medium",
    researchRequired: false,
  },

];

// ── Registry Lookups ──────────────────────────────────────────

export const registryByEngine: Record<WorkflowEngine, WorkflowRegistryEntry[]> = (() => {
  const result: Record<WorkflowEngine, WorkflowRegistryEntry[]> = {
    "document-action": [],
    "dispute": [],
    "records": [],
    "appeal": [],
    "jurisdictional": [],
  };
  for (const entry of WORKFLOW_REGISTRY) {
    result[entry.engine].push(entry);
  }
  return result;
})();

export const registryByVertical: Record<string, WorkflowRegistryEntry[]> = (() => {
  const result: Record<string, WorkflowRegistryEntry[]> = {};
  for (const entry of WORKFLOW_REGISTRY) {
    if (!result[entry.vertical]) result[entry.vertical] = [
  // ═══ Tenant Reply workflows ═══
  {
    id: "tenant-eviction-response",
    vertical: "tenant-reply",
    category: "Housing",
    engine: "jurisdictional",
    lifecycle: "functional",
    title: "Respond to an Eviction Notice",
    canonicalKeyword: "respond to an eviction notice",
    keywordCluster: ["eviction notice response", "pay or quit response", "cure or quit response"],
    msv: null, cpc: null, competition: null,
    seoUrl: "/workflows/tenant-eviction-response",
    repo: "tenant-reply",
    productStatus: "functional",
    testStatus: "partial",
    deploymentStatus: "staging",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },
  {
    id: "tenant-repair-demand",
    vertical: "tenant-reply",
    category: "Housing",
    engine: "jurisdictional",
    lifecycle: "functional",
    title: "Respond to a Repair Demand or Habitability Issue",
    canonicalKeyword: "tenant repair demand letter",
    keywordCluster: ["habitability complaint", "repair request letter to landlord"],
    msv: null, cpc: null, competition: null,
    seoUrl: "/workflows/tenant-repair-demand",
    repo: "tenant-reply",
    productStatus: "functional",
    testStatus: "partial",
    deploymentStatus: "staging",
    factoryReuseScore: 0.85,
    implementationDifficulty: 2,
    priority: "high",
    researchRequired: true,
  },

  // ═══ Claim Proof workflows ═══
  {
    id: "claim-proof-package",
    vertical: "claim-proof",
    category: "Appeals / Claims",
    engine: "appeal",
    lifecycle: "functional",
    title: "Build a Claim Proof Package",
    canonicalKeyword: "build a claim proof package",
    keywordCluster: ["insurance claim documentation", "disability claim evidence", "VA claim proof package"],
    msv: null, cpc: null, competition: null,
    seoUrl: "/workflows/claim-proof-package",
    repo: "claim-proof",
    productStatus: "functional",
    testStatus: "partial",
    deploymentStatus: "staging",
    factoryReuseScore: 0.80,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },

  // ═══ Permit Reply workflows ═══
  {
    id: "permit-denial-response",
    vertical: "permit-reply",
    category: "Regulatory / Permit / Rights",
    engine: "jurisdictional",
    lifecycle: "functional",
    title: "Respond to a Permit Denial",
    canonicalKeyword: "respond to a permit denial",
    keywordCluster: ["permit denial appeal", "building permit reconsideration", "permit denial response letter"],
    msv: null, cpc: null, competition: null,
    seoUrl: "/workflows/permit-denial-response",
    repo: "permit-reply",
    productStatus: "functional",
    testStatus: "partial",
    deploymentStatus: "staging",
    factoryReuseScore: 0.88,
    implementationDifficulty: 3,
    priority: "high",
    researchRequired: true,
  },
];
    result[entry.vertical].push(entry);
  }
  return result;
})();

export const registryById: Record<string, WorkflowRegistryEntry> = (() => {
  const result: Record<string, WorkflowRegistryEntry> = {};
  for (const entry of WORKFLOW_REGISTRY) {
    result[entry.id] = entry;
  }
  return result;
})();

// ── Statistics ────────────────────────────────────────────────

export function registryStats() {
  const total = WORKFLOW_REGISTRY.length;
  const byLifecycle: Record<string, number> = {};
  const byEngine: Record<string, number> = {};
  const byVertical: Record<string, number> = {};
  const byStatus: Record<string, number> = {};

  for (const entry of WORKFLOW_REGISTRY) {
    byLifecycle[entry.lifecycle] = (byLifecycle[entry.lifecycle] || 0) + 1;
    byEngine[entry.engine] = (byEngine[entry.engine] || 0) + 1;
    byVertical[entry.vertical] = (byVertical[entry.vertical] || 0) + 1;
    byStatus[entry.productStatus] = (byStatus[entry.productStatus] || 0) + 1;
  }

  const researchRequired = WORKFLOW_REGISTRY.filter((e) => e.researchRequired).length;
  const withMsv = WORKFLOW_REGISTRY.filter((e) => e.msv !== null).length;

  return {
    total,
    byLifecycle,
    byEngine,
    byVertical,
    byStatus,
    researchRequired,
    withMsv,
    withoutMsv: total - withMsv,
  };
}
