/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MailAPdfRouteImport } from './routes/mail-a-pdf'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RespondToAUscisNoticeRouteImport } from './routes/respond-to-a-uscis-notice'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AppealIndexRouteImport } from './routes/appeal/index'
import { Route as AppealSlugRouteImport } from './routes/appeal/$slug'
import { Route as I130IndexRouteImport } from './routes/i-130/index'
import { Route as I130SlugRouteImport } from './routes/i-130/$slug'
import { Route as I797NoticeIndexRouteImport } from './routes/i-797-notice/index'
import { Route as NoidIndexRouteImport } from './routes/noid/index'
import { Route as NoidSlugRouteImport } from './routes/noid/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as RfeIndexRouteImport } from './routes/rfe/index'
import { Route as RfeSlugRouteImport } from './routes/rfe/$slug'
import { Route as UscisDenialIndexRouteImport } from './routes/uscis-denial/index'
import { Route as UscisFoiaIndexRouteImport } from './routes/uscis-foia/index'
import { Route as VisaRefusalIndexRouteImport } from './routes/visa-refusal/index'
import { Route as VisaRefusalSlugRouteImport } from './routes/visa-refusal/$slug'
import { Route as WorkflowsWorkflowSlugRouteImport } from './routes/workflows/$workflowSlug'
import { Route as WorkflowsExplanationLetterRouteImport } from './routes/workflows/explanation-letter'
import { Route as WorkflowsRespondToNoticeRouteImport } from './routes/workflows/respond-to-notice'
import { Route as WorkflowsSupportingDocumentsRouteImport } from './routes/workflows/supporting-documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAPdfRoute = MailAPdfRouteImport.update({
  id: '/mail-a-pdf',
  path: '/mail-a-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondToAUscisNoticeRoute = RespondToAUscisNoticeRouteImport.update({
  id: '/respond-to-a-uscis-notice',
  path: '/respond-to-a-uscis-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealIndexRoute = AppealIndexRouteImport.update({
  id: '/appeal/',
  path: '/appeal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealSlugRoute = AppealSlugRouteImport.update({
  id: '/appeal/$slug',
  path: '/appeal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const I130IndexRoute = I130IndexRouteImport.update({
  id: '/i-130/',
  path: '/i-130/',
  getParentRoute: () => rootRouteImport,
} as any)
const I130SlugRoute = I130SlugRouteImport.update({
  id: '/i-130/$slug',
  path: '/i-130/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const I797NoticeIndexRoute = I797NoticeIndexRouteImport.update({
  id: '/i-797-notice/',
  path: '/i-797-notice/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoidIndexRoute = NoidIndexRouteImport.update({
  id: '/noid/',
  path: '/noid/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoidSlugRoute = NoidSlugRouteImport.update({
  id: '/noid/$slug',
  path: '/noid/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RfeIndexRoute = RfeIndexRouteImport.update({
  id: '/rfe/',
  path: '/rfe/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfeSlugRoute = RfeSlugRouteImport.update({
  id: '/rfe/$slug',
  path: '/rfe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UscisDenialIndexRoute = UscisDenialIndexRouteImport.update({
  id: '/uscis-denial/',
  path: '/uscis-denial/',
  getParentRoute: () => rootRouteImport,
} as any)
const UscisFoiaIndexRoute = UscisFoiaIndexRouteImport.update({
  id: '/uscis-foia/',
  path: '/uscis-foia/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRefusalIndexRoute = VisaRefusalIndexRouteImport.update({
  id: '/visa-refusal/',
  path: '/visa-refusal/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRefusalSlugRoute = VisaRefusalSlugRouteImport.update({
  id: '/visa-refusal/$slug',
  path: '/visa-refusal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowSlugRoute = WorkflowsWorkflowSlugRouteImport.update({
  id: '/$workflowSlug',
  path: '/$workflowSlug',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsExplanationLetterRoute =
  WorkflowsExplanationLetterRouteImport.update({
    id: '/explanation-letter',
    path: '/explanation-letter',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsRespondToNoticeRoute =
  WorkflowsRespondToNoticeRouteImport.update({
    id: '/respond-to-notice',
    path: '/respond-to-notice',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsSupportingDocumentsRoute =
  WorkflowsSupportingDocumentsRouteImport.update({
    id: '/supporting-documents',
    path: '/supporting-documents',
    getParentRoute: () => WorkflowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-uscis-notice': typeof RespondToAUscisNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/i-130/$slug': typeof I130SlugRoute
  '/noid/$slug': typeof NoidSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rfe/$slug': typeof RfeSlugRoute
  '/visa-refusal/$slug': typeof VisaRefusalSlugRoute
  '/workflows/$workflowSlug': typeof WorkflowsWorkflowSlugRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
  '/appeal/': typeof AppealIndexRoute
  '/i-130/': typeof I130IndexRoute
  '/i-797-notice/': typeof I797NoticeIndexRoute
  '/noid/': typeof NoidIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/rfe/': typeof RfeIndexRoute
  '/uscis-denial/': typeof UscisDenialIndexRoute
  '/uscis-foia/': typeof UscisFoiaIndexRoute
  '/visa-refusal/': typeof VisaRefusalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-uscis-notice': typeof RespondToAUscisNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/i-130/$slug': typeof I130SlugRoute
  '/noid/$slug': typeof NoidSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rfe/$slug': typeof RfeSlugRoute
  '/visa-refusal/$slug': typeof VisaRefusalSlugRoute
  '/workflows/$workflowSlug': typeof WorkflowsWorkflowSlugRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
  '/appeal': typeof AppealIndexRoute
  '/i-130': typeof I130IndexRoute
  '/i-797-notice': typeof I797NoticeIndexRoute
  '/noid': typeof NoidIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/rfe': typeof RfeIndexRoute
  '/uscis-denial': typeof UscisDenialIndexRoute
  '/uscis-foia': typeof UscisFoiaIndexRoute
  '/visa-refusal': typeof VisaRefusalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-uscis-notice': typeof RespondToAUscisNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/appeal/$slug': typeof AppealSlugRoute
  '/i-130/$slug': typeof I130SlugRoute
  '/noid/$slug': typeof NoidSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rfe/$slug': typeof RfeSlugRoute
  '/visa-refusal/$slug': typeof VisaRefusalSlugRoute
  '/workflows/$workflowSlug': typeof WorkflowsWorkflowSlugRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
  '/appeal/': typeof AppealIndexRoute
  '/i-130/': typeof I130IndexRoute
  '/i-797-notice/': typeof I797NoticeIndexRoute
  '/noid/': typeof NoidIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/rfe/': typeof RfeIndexRoute
  '/uscis-denial/': typeof UscisDenialIndexRoute
  '/uscis-foia/': typeof UscisFoiaIndexRoute
  '/visa-refusal/': typeof VisaRefusalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-uscis-notice'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/i-130/$slug'
    | '/noid/$slug'
    | '/resources/$slug'
    | '/rfe/$slug'
    | '/visa-refusal/$slug'
    | '/workflows/$workflowSlug'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
    | '/appeal/'
    | '/i-130/'
    | '/i-797-notice/'
    | '/noid/'
    | '/resources/'
    | '/rfe/'
    | '/uscis-denial/'
    | '/uscis-foia/'
    | '/visa-refusal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-uscis-notice'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/i-130/$slug'
    | '/noid/$slug'
    | '/resources/$slug'
    | '/rfe/$slug'
    | '/visa-refusal/$slug'
    | '/workflows/$workflowSlug'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
    | '/appeal'
    | '/i-130'
    | '/i-797-notice'
    | '/noid'
    | '/resources'
    | '/rfe'
    | '/uscis-denial'
    | '/uscis-foia'
    | '/visa-refusal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-uscis-notice'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/appeal/$slug'
    | '/i-130/$slug'
    | '/noid/$slug'
    | '/resources/$slug'
    | '/rfe/$slug'
    | '/visa-refusal/$slug'
    | '/workflows/$workflowSlug'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
    | '/appeal/'
    | '/i-130/'
    | '/i-797-notice/'
    | '/noid/'
    | '/resources/'
    | '/rfe/'
    | '/uscis-denial/'
    | '/uscis-foia/'
    | '/visa-refusal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MailAPdfRoute: typeof MailAPdfRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RespondToAUscisNoticeRoute: typeof RespondToAUscisNoticeRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  AppealSlugRoute: typeof AppealSlugRoute
  I130SlugRoute: typeof I130SlugRoute
  NoidSlugRoute: typeof NoidSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  RfeSlugRoute: typeof RfeSlugRoute
  VisaRefusalSlugRoute: typeof VisaRefusalSlugRoute
  AppealIndexRoute: typeof AppealIndexRoute
  I130IndexRoute: typeof I130IndexRoute
  I797NoticeIndexRoute: typeof I797NoticeIndexRoute
  NoidIndexRoute: typeof NoidIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  RfeIndexRoute: typeof RfeIndexRoute
  UscisDenialIndexRoute: typeof UscisDenialIndexRoute
  UscisFoiaIndexRoute: typeof UscisFoiaIndexRoute
  VisaRefusalIndexRoute: typeof VisaRefusalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-pdf': {
      id: '/mail-a-pdf'
      path: '/mail-a-pdf'
      fullPath: '/mail-a-pdf'
      preLoaderRoute: typeof MailAPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respond-to-a-uscis-notice': {
      id: '/respond-to-a-uscis-notice'
      path: '/respond-to-a-uscis-notice'
      fullPath: '/respond-to-a-uscis-notice'
      preLoaderRoute: typeof RespondToAUscisNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/': {
      id: '/appeal/'
      path: '/appeal'
      fullPath: '/appeal/'
      preLoaderRoute: typeof AppealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/$slug': {
      id: '/appeal/$slug'
      path: '/appeal/$slug'
      fullPath: '/appeal/$slug'
      preLoaderRoute: typeof AppealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-130/': {
      id: '/i-130/'
      path: '/i-130'
      fullPath: '/i-130/'
      preLoaderRoute: typeof I130IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-130/$slug': {
      id: '/i-130/$slug'
      path: '/i-130/$slug'
      fullPath: '/i-130/$slug'
      preLoaderRoute: typeof I130SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-797-notice/': {
      id: '/i-797-notice/'
      path: '/i-797-notice'
      fullPath: '/i-797-notice/'
      preLoaderRoute: typeof I797NoticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noid/': {
      id: '/noid/'
      path: '/noid'
      fullPath: '/noid/'
      preLoaderRoute: typeof NoidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noid/$slug': {
      id: '/noid/$slug'
      path: '/noid/$slug'
      fullPath: '/noid/$slug'
      preLoaderRoute: typeof NoidSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfe/': {
      id: '/rfe/'
      path: '/rfe'
      fullPath: '/rfe/'
      preLoaderRoute: typeof RfeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfe/$slug': {
      id: '/rfe/$slug'
      path: '/rfe/$slug'
      fullPath: '/rfe/$slug'
      preLoaderRoute: typeof RfeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uscis-denial/': {
      id: '/uscis-denial/'
      path: '/uscis-denial'
      fullPath: '/uscis-denial/'
      preLoaderRoute: typeof UscisDenialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uscis-foia/': {
      id: '/uscis-foia/'
      path: '/uscis-foia'
      fullPath: '/uscis-foia/'
      preLoaderRoute: typeof UscisFoiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-refusal/': {
      id: '/visa-refusal/'
      path: '/visa-refusal'
      fullPath: '/visa-refusal/'
      preLoaderRoute: typeof VisaRefusalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-refusal/$slug': {
      id: '/visa-refusal/$slug'
      path: '/visa-refusal/$slug'
      fullPath: '/visa-refusal/$slug'
      preLoaderRoute: typeof VisaRefusalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowSlug': {
      id: '/workflows/$workflowSlug'
      path: '/$workflowSlug'
      fullPath: '/workflows/$workflowSlug'
      preLoaderRoute: typeof WorkflowsWorkflowSlugRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/explanation-letter': {
      id: '/workflows/explanation-letter'
      path: '/explanation-letter'
      fullPath: '/workflows/explanation-letter'
      preLoaderRoute: typeof WorkflowsExplanationLetterRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/respond-to-notice': {
      id: '/workflows/respond-to-notice'
      path: '/respond-to-notice'
      fullPath: '/workflows/respond-to-notice'
      preLoaderRoute: typeof WorkflowsRespondToNoticeRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/supporting-documents': {
      id: '/workflows/supporting-documents'
      path: '/supporting-documents'
      fullPath: '/workflows/supporting-documents'
      preLoaderRoute: typeof WorkflowsSupportingDocumentsRouteImport
      parentRoute: typeof WorkflowsRoute
    }
  }
}

interface WorkflowsRouteChildren {
  WorkflowsWorkflowSlugRoute: typeof WorkflowsWorkflowSlugRoute
  WorkflowsExplanationLetterRoute: typeof WorkflowsExplanationLetterRoute
  WorkflowsRespondToNoticeRoute: typeof WorkflowsRespondToNoticeRoute
  WorkflowsSupportingDocumentsRoute: typeof WorkflowsSupportingDocumentsRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowSlugRoute: WorkflowsWorkflowSlugRoute,
  WorkflowsExplanationLetterRoute: WorkflowsExplanationLetterRoute,
  WorkflowsRespondToNoticeRoute: WorkflowsRespondToNoticeRoute,
  WorkflowsSupportingDocumentsRoute: WorkflowsSupportingDocumentsRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AnalyzeRoute: AnalyzeRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MailAPdfRoute: MailAPdfRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RespondToAUscisNoticeRoute: RespondToAUscisNoticeRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  AppealSlugRoute: AppealSlugRoute,
  I130SlugRoute: I130SlugRoute,
  NoidSlugRoute: NoidSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  RfeSlugRoute: RfeSlugRoute,
  VisaRefusalSlugRoute: VisaRefusalSlugRoute,
  AppealIndexRoute: AppealIndexRoute,
  I130IndexRoute: I130IndexRoute,
  I797NoticeIndexRoute: I797NoticeIndexRoute,
  NoidIndexRoute: NoidIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  RfeIndexRoute: RfeIndexRoute,
  UscisDenialIndexRoute: UscisDenialIndexRoute,
  UscisFoiaIndexRoute: UscisFoiaIndexRoute,
  VisaRefusalIndexRoute: VisaRefusalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
