/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as CertifiedMailGuideRouteImport } from './routes/certified-mail-guide'
import { Route as FutureSelfRouteImport } from './routes/future-self'
import { Route as MailAContractOnlineRouteImport } from './routes/mail-a-contract-online'
import { Route as MailAPdfRouteImport } from './routes/mail-a-pdf'
import { Route as MailDocumentsWithoutPrinterRouteImport } from './routes/mail-documents-without-printer'
import { Route as MailFormsOnlineRouteImport } from './routes/mail-forms-online'
import { Route as MailPaperworkOnlineRouteImport } from './routes/mail-paperwork-online'
import { Route as MailTaxDocumentsOnlineRouteImport } from './routes/mail-tax-documents-online'
import { Route as PrintAndMailADocumentOnlineRouteImport } from './routes/print-and-mail-a-document-online'
import { Route as PrintAndMailPdfOnlineRouteImport } from './routes/print-and-mail-pdf-online'
import { Route as PrintAndPostDocumentsOnlineRouteImport } from './routes/print-and-post-documents-online'
import { Route as ProRouteImport } from './routes/pro'
import { Route as SendRouteImport } from './routes/send'
import { Route as SendALetterWithoutAPrinterRouteImport } from './routes/send-a-letter-without-a-printer'
import { Route as SendBusinessDocumentsByMailRouteImport } from './routes/send-business-documents-by-mail'
import { Route as SendBusinessLetterOnlineRouteImport } from './routes/send-business-letter-online'
import { Route as SendCancellationLetterOnlineRouteImport } from './routes/send-cancellation-letter-online'
import { Route as SendCeaseAndDesistLetterRouteImport } from './routes/send-cease-and-desist-letter'
import { Route as SendComplaintLetterOnlineRouteImport } from './routes/send-complaint-letter-online'
import { Route as SendDemandLetterOnlineRouteImport } from './routes/send-demand-letter-online'
import { Route as SendDocumentsByMailOnlineRouteImport } from './routes/send-documents-by-mail-online'
import { Route as SendInsuranceDocumentsByMailRouteImport } from './routes/send-insurance-documents-by-mail'
import { Route as SendInvoiceByMailRouteImport } from './routes/send-invoice-by-mail'
import { Route as SendLetterOnlineRouteImport } from './routes/send-letter-online'
import { Route as SendLetterToBankRouteImport } from './routes/send-letter-to-bank'
import { Route as SendLetterToClientRouteImport } from './routes/send-letter-to-client'
import { Route as SendLetterToCompanyRouteImport } from './routes/send-letter-to-company'
import { Route as SendLetterToCountyClerkRouteImport } from './routes/send-letter-to-county-clerk'
import { Route as SendLetterToCourtRouteImport } from './routes/send-letter-to-court'
import { Route as SendLetterToCourtClerkRouteImport } from './routes/send-letter-to-court-clerk'
import { Route as SendLetterToDmvRouteImport } from './routes/send-letter-to-dmv'
import { Route as SendLetterToInsuranceCompanyRouteImport } from './routes/send-letter-to-insurance-company'
import { Route as SendLetterToIrsRouteImport } from './routes/send-letter-to-irs'
import { Route as SendLetterToLandlordRouteImport } from './routes/send-letter-to-landlord'
import { Route as SendLetterToSocialSecurityRouteImport } from './routes/send-letter-to-social-security'
import { Route as SendLetterToTenantRouteImport } from './routes/send-letter-to-tenant'
import { Route as SendLetterToUscisRouteImport } from './routes/send-letter-to-uscis'
import { Route as SendMedicalRecordsRequestByMailRouteImport } from './routes/send-medical-records-request-by-mail'
import { Route as SendPdfByPostRouteImport } from './routes/send-pdf-by-post'
import { Route as SendResignationLetterByMailRouteImport } from './routes/send-resignation-letter-by-mail'
import { Route as SendSchoolDocumentsByMailRouteImport } from './routes/send-school-documents-by-mail'
import { Route as SendSignedDocumentOnlineRouteImport } from './routes/send-signed-document-online'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ApiAiAssistRouteImport } from './routes/api/ai-assist'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiInternalCleanupDraftsRouteImport } from './routes/api/internal/cleanup-drafts'
import { Route as ApiInternalHealthRouteImport } from './routes/api/internal/health'
import { Route as ApiInternalProcessScheduledRouteImport } from './routes/api/internal/process-scheduled'
import { Route as ApiPublicLobWebhookRouteImport } from './routes/api/public/lob-webhook'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin/orders/$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifiedMailGuideRoute = CertifiedMailGuideRouteImport.update({
  id: '/certified-mail-guide',
  path: '/certified-mail-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureSelfRoute = FutureSelfRouteImport.update({
  id: '/future-self',
  path: '/future-self',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAContractOnlineRoute = MailAContractOnlineRouteImport.update({
  id: '/mail-a-contract-online',
  path: '/mail-a-contract-online',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAPdfRoute = MailAPdfRouteImport.update({
  id: '/mail-a-pdf',
  path: '/mail-a-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MailDocumentsWithoutPrinterRoute =
  MailDocumentsWithoutPrinterRouteImport.update({
    id: '/mail-documents-without-printer',
    path: '/mail-documents-without-printer',
    getParentRoute: () => rootRouteImport,
  } as any)
const MailFormsOnlineRoute = MailFormsOnlineRouteImport.update({
  id: '/mail-forms-online',
  path: '/mail-forms-online',
  getParentRoute: () => rootRouteImport,
} as any)
const MailPaperworkOnlineRoute = MailPaperworkOnlineRouteImport.update({
  id: '/mail-paperwork-online',
  path: '/mail-paperwork-online',
  getParentRoute: () => rootRouteImport,
} as any)
const MailTaxDocumentsOnlineRoute = MailTaxDocumentsOnlineRouteImport.update({
  id: '/mail-tax-documents-online',
  path: '/mail-tax-documents-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintAndMailADocumentOnlineRoute =
  PrintAndMailADocumentOnlineRouteImport.update({
    id: '/print-and-mail-a-document-online',
    path: '/print-and-mail-a-document-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintAndMailPdfOnlineRoute = PrintAndMailPdfOnlineRouteImport.update({
  id: '/print-and-mail-pdf-online',
  path: '/print-and-mail-pdf-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintAndPostDocumentsOnlineRoute =
  PrintAndPostDocumentsOnlineRouteImport.update({
    id: '/print-and-post-documents-online',
    path: '/print-and-post-documents-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SendALetterWithoutAPrinterRoute =
  SendALetterWithoutAPrinterRouteImport.update({
    id: '/send-a-letter-without-a-printer',
    path: '/send-a-letter-without-a-printer',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendBusinessDocumentsByMailRoute =
  SendBusinessDocumentsByMailRouteImport.update({
    id: '/send-business-documents-by-mail',
    path: '/send-business-documents-by-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendBusinessLetterOnlineRoute =
  SendBusinessLetterOnlineRouteImport.update({
    id: '/send-business-letter-online',
    path: '/send-business-letter-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendCancellationLetterOnlineRoute =
  SendCancellationLetterOnlineRouteImport.update({
    id: '/send-cancellation-letter-online',
    path: '/send-cancellation-letter-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendCeaseAndDesistLetterRoute =
  SendCeaseAndDesistLetterRouteImport.update({
    id: '/send-cease-and-desist-letter',
    path: '/send-cease-and-desist-letter',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendComplaintLetterOnlineRoute =
  SendComplaintLetterOnlineRouteImport.update({
    id: '/send-complaint-letter-online',
    path: '/send-complaint-letter-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendDemandLetterOnlineRoute = SendDemandLetterOnlineRouteImport.update({
  id: '/send-demand-letter-online',
  path: '/send-demand-letter-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SendDocumentsByMailOnlineRoute =
  SendDocumentsByMailOnlineRouteImport.update({
    id: '/send-documents-by-mail-online',
    path: '/send-documents-by-mail-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendInsuranceDocumentsByMailRoute =
  SendInsuranceDocumentsByMailRouteImport.update({
    id: '/send-insurance-documents-by-mail',
    path: '/send-insurance-documents-by-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendInvoiceByMailRoute = SendInvoiceByMailRouteImport.update({
  id: '/send-invoice-by-mail',
  path: '/send-invoice-by-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterOnlineRoute = SendLetterOnlineRouteImport.update({
  id: '/send-letter-online',
  path: '/send-letter-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToBankRoute = SendLetterToBankRouteImport.update({
  id: '/send-letter-to-bank',
  path: '/send-letter-to-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToClientRoute = SendLetterToClientRouteImport.update({
  id: '/send-letter-to-client',
  path: '/send-letter-to-client',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToCompanyRoute = SendLetterToCompanyRouteImport.update({
  id: '/send-letter-to-company',
  path: '/send-letter-to-company',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToCountyClerkRoute = SendLetterToCountyClerkRouteImport.update({
  id: '/send-letter-to-county-clerk',
  path: '/send-letter-to-county-clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToCourtRoute = SendLetterToCourtRouteImport.update({
  id: '/send-letter-to-court',
  path: '/send-letter-to-court',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToCourtClerkRoute = SendLetterToCourtClerkRouteImport.update({
  id: '/send-letter-to-court-clerk',
  path: '/send-letter-to-court-clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToDmvRoute = SendLetterToDmvRouteImport.update({
  id: '/send-letter-to-dmv',
  path: '/send-letter-to-dmv',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToInsuranceCompanyRoute =
  SendLetterToInsuranceCompanyRouteImport.update({
    id: '/send-letter-to-insurance-company',
    path: '/send-letter-to-insurance-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendLetterToIrsRoute = SendLetterToIrsRouteImport.update({
  id: '/send-letter-to-irs',
  path: '/send-letter-to-irs',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToLandlordRoute = SendLetterToLandlordRouteImport.update({
  id: '/send-letter-to-landlord',
  path: '/send-letter-to-landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToSocialSecurityRoute =
  SendLetterToSocialSecurityRouteImport.update({
    id: '/send-letter-to-social-security',
    path: '/send-letter-to-social-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendLetterToTenantRoute = SendLetterToTenantRouteImport.update({
  id: '/send-letter-to-tenant',
  path: '/send-letter-to-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SendLetterToUscisRoute = SendLetterToUscisRouteImport.update({
  id: '/send-letter-to-uscis',
  path: '/send-letter-to-uscis',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMedicalRecordsRequestByMailRoute =
  SendMedicalRecordsRequestByMailRouteImport.update({
    id: '/send-medical-records-request-by-mail',
    path: '/send-medical-records-request-by-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendPdfByPostRoute = SendPdfByPostRouteImport.update({
  id: '/send-pdf-by-post',
  path: '/send-pdf-by-post',
  getParentRoute: () => rootRouteImport,
} as any)
const SendResignationLetterByMailRoute =
  SendResignationLetterByMailRouteImport.update({
    id: '/send-resignation-letter-by-mail',
    path: '/send-resignation-letter-by-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendSchoolDocumentsByMailRoute =
  SendSchoolDocumentsByMailRouteImport.update({
    id: '/send-school-documents-by-mail',
    path: '/send-school-documents-by-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendSignedDocumentOnlineRoute =
  SendSignedDocumentOnlineRouteImport.update({
    id: '/send-signed-document-online',
    path: '/send-signed-document-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistRoute = ApiAiAssistRouteImport.update({
  id: '/api/ai-assist',
  path: '/api/ai-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiInternalCleanupDraftsRoute =
  ApiInternalCleanupDraftsRouteImport.update({
    id: '/api/internal/cleanup-drafts',
    path: '/api/internal/cleanup-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalHealthRoute = ApiInternalHealthRouteImport.update({
  id: '/api/internal/health',
  path: '/api/internal/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalProcessScheduledRoute =
  ApiInternalProcessScheduledRouteImport.update({
    id: '/api/internal/process-scheduled',
    path: '/api/internal/process-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLobWebhookRoute = ApiPublicLobWebhookRouteImport.update({
  id: '/api/public/lob-webhook',
  path: '/api/public/lob-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/admin/orders/$id',
    path: '/admin/orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/certified-mail-guide': typeof CertifiedMailGuideRoute
  '/future-self': typeof FutureSelfRoute
  '/mail-a-contract-online': typeof MailAContractOnlineRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/mail-documents-without-printer': typeof MailDocumentsWithoutPrinterRoute
  '/mail-forms-online': typeof MailFormsOnlineRoute
  '/mail-paperwork-online': typeof MailPaperworkOnlineRoute
  '/mail-tax-documents-online': typeof MailTaxDocumentsOnlineRoute
  '/print-and-mail-a-document-online': typeof PrintAndMailADocumentOnlineRoute
  '/print-and-mail-pdf-online': typeof PrintAndMailPdfOnlineRoute
  '/print-and-post-documents-online': typeof PrintAndPostDocumentsOnlineRoute
  '/pro': typeof ProRoute
  '/send': typeof SendRoute
  '/send-a-letter-without-a-printer': typeof SendALetterWithoutAPrinterRoute
  '/send-business-documents-by-mail': typeof SendBusinessDocumentsByMailRoute
  '/send-business-letter-online': typeof SendBusinessLetterOnlineRoute
  '/send-cancellation-letter-online': typeof SendCancellationLetterOnlineRoute
  '/send-cease-and-desist-letter': typeof SendCeaseAndDesistLetterRoute
  '/send-complaint-letter-online': typeof SendComplaintLetterOnlineRoute
  '/send-demand-letter-online': typeof SendDemandLetterOnlineRoute
  '/send-documents-by-mail-online': typeof SendDocumentsByMailOnlineRoute
  '/send-insurance-documents-by-mail': typeof SendInsuranceDocumentsByMailRoute
  '/send-invoice-by-mail': typeof SendInvoiceByMailRoute
  '/send-letter-online': typeof SendLetterOnlineRoute
  '/send-letter-to-bank': typeof SendLetterToBankRoute
  '/send-letter-to-client': typeof SendLetterToClientRoute
  '/send-letter-to-company': typeof SendLetterToCompanyRoute
  '/send-letter-to-county-clerk': typeof SendLetterToCountyClerkRoute
  '/send-letter-to-court': typeof SendLetterToCourtRoute
  '/send-letter-to-court-clerk': typeof SendLetterToCourtClerkRoute
  '/send-letter-to-dmv': typeof SendLetterToDmvRoute
  '/send-letter-to-insurance-company': typeof SendLetterToInsuranceCompanyRoute
  '/send-letter-to-irs': typeof SendLetterToIrsRoute
  '/send-letter-to-landlord': typeof SendLetterToLandlordRoute
  '/send-letter-to-social-security': typeof SendLetterToSocialSecurityRoute
  '/send-letter-to-tenant': typeof SendLetterToTenantRoute
  '/send-letter-to-uscis': typeof SendLetterToUscisRoute
  '/send-medical-records-request-by-mail': typeof SendMedicalRecordsRequestByMailRoute
  '/send-pdf-by-post': typeof SendPdfByPostRoute
  '/send-resignation-letter-by-mail': typeof SendResignationLetterByMailRoute
  '/send-school-documents-by-mail': typeof SendSchoolDocumentsByMailRoute
  '/send-signed-document-online': typeof SendSignedDocumentOnlineRoute
  '/templates': typeof TemplatesRoute
  '/write': typeof WriteRoute
  '/api/ai-assist': typeof ApiAiAssistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/internal/cleanup-drafts': typeof ApiInternalCleanupDraftsRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/internal/process-scheduled': typeof ApiInternalProcessScheduledRoute
  '/api/public/lob-webhook': typeof ApiPublicLobWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/certified-mail-guide': typeof CertifiedMailGuideRoute
  '/future-self': typeof FutureSelfRoute
  '/mail-a-contract-online': typeof MailAContractOnlineRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/mail-documents-without-printer': typeof MailDocumentsWithoutPrinterRoute
  '/mail-forms-online': typeof MailFormsOnlineRoute
  '/mail-paperwork-online': typeof MailPaperworkOnlineRoute
  '/mail-tax-documents-online': typeof MailTaxDocumentsOnlineRoute
  '/print-and-mail-a-document-online': typeof PrintAndMailADocumentOnlineRoute
  '/print-and-mail-pdf-online': typeof PrintAndMailPdfOnlineRoute
  '/print-and-post-documents-online': typeof PrintAndPostDocumentsOnlineRoute
  '/pro': typeof ProRoute
  '/send': typeof SendRoute
  '/send-a-letter-without-a-printer': typeof SendALetterWithoutAPrinterRoute
  '/send-business-documents-by-mail': typeof SendBusinessDocumentsByMailRoute
  '/send-business-letter-online': typeof SendBusinessLetterOnlineRoute
  '/send-cancellation-letter-online': typeof SendCancellationLetterOnlineRoute
  '/send-cease-and-desist-letter': typeof SendCeaseAndDesistLetterRoute
  '/send-complaint-letter-online': typeof SendComplaintLetterOnlineRoute
  '/send-demand-letter-online': typeof SendDemandLetterOnlineRoute
  '/send-documents-by-mail-online': typeof SendDocumentsByMailOnlineRoute
  '/send-insurance-documents-by-mail': typeof SendInsuranceDocumentsByMailRoute
  '/send-invoice-by-mail': typeof SendInvoiceByMailRoute
  '/send-letter-online': typeof SendLetterOnlineRoute
  '/send-letter-to-bank': typeof SendLetterToBankRoute
  '/send-letter-to-client': typeof SendLetterToClientRoute
  '/send-letter-to-company': typeof SendLetterToCompanyRoute
  '/send-letter-to-county-clerk': typeof SendLetterToCountyClerkRoute
  '/send-letter-to-court': typeof SendLetterToCourtRoute
  '/send-letter-to-court-clerk': typeof SendLetterToCourtClerkRoute
  '/send-letter-to-dmv': typeof SendLetterToDmvRoute
  '/send-letter-to-insurance-company': typeof SendLetterToInsuranceCompanyRoute
  '/send-letter-to-irs': typeof SendLetterToIrsRoute
  '/send-letter-to-landlord': typeof SendLetterToLandlordRoute
  '/send-letter-to-social-security': typeof SendLetterToSocialSecurityRoute
  '/send-letter-to-tenant': typeof SendLetterToTenantRoute
  '/send-letter-to-uscis': typeof SendLetterToUscisRoute
  '/send-medical-records-request-by-mail': typeof SendMedicalRecordsRequestByMailRoute
  '/send-pdf-by-post': typeof SendPdfByPostRoute
  '/send-resignation-letter-by-mail': typeof SendResignationLetterByMailRoute
  '/send-school-documents-by-mail': typeof SendSchoolDocumentsByMailRoute
  '/send-signed-document-online': typeof SendSignedDocumentOnlineRoute
  '/templates': typeof TemplatesRoute
  '/write': typeof WriteRoute
  '/api/ai-assist': typeof ApiAiAssistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders': typeof OrdersIndexRoute
  '/api/internal/cleanup-drafts': typeof ApiInternalCleanupDraftsRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/internal/process-scheduled': typeof ApiInternalProcessScheduledRoute
  '/api/public/lob-webhook': typeof ApiPublicLobWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/certified-mail-guide': typeof CertifiedMailGuideRoute
  '/future-self': typeof FutureSelfRoute
  '/mail-a-contract-online': typeof MailAContractOnlineRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/mail-documents-without-printer': typeof MailDocumentsWithoutPrinterRoute
  '/mail-forms-online': typeof MailFormsOnlineRoute
  '/mail-paperwork-online': typeof MailPaperworkOnlineRoute
  '/mail-tax-documents-online': typeof MailTaxDocumentsOnlineRoute
  '/print-and-mail-a-document-online': typeof PrintAndMailADocumentOnlineRoute
  '/print-and-mail-pdf-online': typeof PrintAndMailPdfOnlineRoute
  '/print-and-post-documents-online': typeof PrintAndPostDocumentsOnlineRoute
  '/pro': typeof ProRoute
  '/send': typeof SendRoute
  '/send-a-letter-without-a-printer': typeof SendALetterWithoutAPrinterRoute
  '/send-business-documents-by-mail': typeof SendBusinessDocumentsByMailRoute
  '/send-business-letter-online': typeof SendBusinessLetterOnlineRoute
  '/send-cancellation-letter-online': typeof SendCancellationLetterOnlineRoute
  '/send-cease-and-desist-letter': typeof SendCeaseAndDesistLetterRoute
  '/send-complaint-letter-online': typeof SendComplaintLetterOnlineRoute
  '/send-demand-letter-online': typeof SendDemandLetterOnlineRoute
  '/send-documents-by-mail-online': typeof SendDocumentsByMailOnlineRoute
  '/send-insurance-documents-by-mail': typeof SendInsuranceDocumentsByMailRoute
  '/send-invoice-by-mail': typeof SendInvoiceByMailRoute
  '/send-letter-online': typeof SendLetterOnlineRoute
  '/send-letter-to-bank': typeof SendLetterToBankRoute
  '/send-letter-to-client': typeof SendLetterToClientRoute
  '/send-letter-to-company': typeof SendLetterToCompanyRoute
  '/send-letter-to-county-clerk': typeof SendLetterToCountyClerkRoute
  '/send-letter-to-court': typeof SendLetterToCourtRoute
  '/send-letter-to-court-clerk': typeof SendLetterToCourtClerkRoute
  '/send-letter-to-dmv': typeof SendLetterToDmvRoute
  '/send-letter-to-insurance-company': typeof SendLetterToInsuranceCompanyRoute
  '/send-letter-to-irs': typeof SendLetterToIrsRoute
  '/send-letter-to-landlord': typeof SendLetterToLandlordRoute
  '/send-letter-to-social-security': typeof SendLetterToSocialSecurityRoute
  '/send-letter-to-tenant': typeof SendLetterToTenantRoute
  '/send-letter-to-uscis': typeof SendLetterToUscisRoute
  '/send-medical-records-request-by-mail': typeof SendMedicalRecordsRequestByMailRoute
  '/send-pdf-by-post': typeof SendPdfByPostRoute
  '/send-resignation-letter-by-mail': typeof SendResignationLetterByMailRoute
  '/send-school-documents-by-mail': typeof SendSchoolDocumentsByMailRoute
  '/send-signed-document-online': typeof SendSignedDocumentOnlineRoute
  '/templates': typeof TemplatesRoute
  '/write': typeof WriteRoute
  '/api/ai-assist': typeof ApiAiAssistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/internal/cleanup-drafts': typeof ApiInternalCleanupDraftsRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/internal/process-scheduled': typeof ApiInternalProcessScheduledRoute
  '/api/public/lob-webhook': typeof ApiPublicLobWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk'
    | '/certified-mail-guide'
    | '/future-self'
    | '/mail-a-contract-online'
    | '/mail-a-pdf'
    | '/mail-documents-without-printer'
    | '/mail-forms-online'
    | '/mail-paperwork-online'
    | '/mail-tax-documents-online'
    | '/print-and-mail-a-document-online'
    | '/print-and-mail-pdf-online'
    | '/print-and-post-documents-online'
    | '/pro'
    | '/send'
    | '/send-a-letter-without-a-printer'
    | '/send-business-documents-by-mail'
    | '/send-business-letter-online'
    | '/send-cancellation-letter-online'
    | '/send-cease-and-desist-letter'
    | '/send-complaint-letter-online'
    | '/send-demand-letter-online'
    | '/send-documents-by-mail-online'
    | '/send-insurance-documents-by-mail'
    | '/send-invoice-by-mail'
    | '/send-letter-online'
    | '/send-letter-to-bank'
    | '/send-letter-to-client'
    | '/send-letter-to-company'
    | '/send-letter-to-county-clerk'
    | '/send-letter-to-court'
    | '/send-letter-to-court-clerk'
    | '/send-letter-to-dmv'
    | '/send-letter-to-insurance-company'
    | '/send-letter-to-irs'
    | '/send-letter-to-landlord'
    | '/send-letter-to-social-security'
    | '/send-letter-to-tenant'
    | '/send-letter-to-uscis'
    | '/send-medical-records-request-by-mail'
    | '/send-pdf-by-post'
    | '/send-resignation-letter-by-mail'
    | '/send-school-documents-by-mail'
    | '/send-signed-document-online'
    | '/templates'
    | '/write'
    | '/api/ai-assist'
    | '/orders/$id'
    | '/orders/'
    | '/api/internal/cleanup-drafts'
    | '/api/internal/health'
    | '/api/internal/process-scheduled'
    | '/api/public/lob-webhook'
    | '/admin/'
    | '/admin/orders/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk'
    | '/certified-mail-guide'
    | '/future-self'
    | '/mail-a-contract-online'
    | '/mail-a-pdf'
    | '/mail-documents-without-printer'
    | '/mail-forms-online'
    | '/mail-paperwork-online'
    | '/mail-tax-documents-online'
    | '/print-and-mail-a-document-online'
    | '/print-and-mail-pdf-online'
    | '/print-and-post-documents-online'
    | '/pro'
    | '/send'
    | '/send-a-letter-without-a-printer'
    | '/send-business-documents-by-mail'
    | '/send-business-letter-online'
    | '/send-cancellation-letter-online'
    | '/send-cease-and-desist-letter'
    | '/send-complaint-letter-online'
    | '/send-demand-letter-online'
    | '/send-documents-by-mail-online'
    | '/send-insurance-documents-by-mail'
    | '/send-invoice-by-mail'
    | '/send-letter-online'
    | '/send-letter-to-bank'
    | '/send-letter-to-client'
    | '/send-letter-to-company'
    | '/send-letter-to-county-clerk'
    | '/send-letter-to-court'
    | '/send-letter-to-court-clerk'
    | '/send-letter-to-dmv'
    | '/send-letter-to-insurance-company'
    | '/send-letter-to-irs'
    | '/send-letter-to-landlord'
    | '/send-letter-to-social-security'
    | '/send-letter-to-tenant'
    | '/send-letter-to-uscis'
    | '/send-medical-records-request-by-mail'
    | '/send-pdf-by-post'
    | '/send-resignation-letter-by-mail'
    | '/send-school-documents-by-mail'
    | '/send-signed-document-online'
    | '/templates'
    | '/write'
    | '/api/ai-assist'
    | '/orders/$id'
    | '/orders'
    | '/api/internal/cleanup-drafts'
    | '/api/internal/health'
    | '/api/internal/process-scheduled'
    | '/api/public/lob-webhook'
    | '/admin'
    | '/admin/orders/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bulk'
    | '/certified-mail-guide'
    | '/future-self'
    | '/mail-a-contract-online'
    | '/mail-a-pdf'
    | '/mail-documents-without-printer'
    | '/mail-forms-online'
    | '/mail-paperwork-online'
    | '/mail-tax-documents-online'
    | '/print-and-mail-a-document-online'
    | '/print-and-mail-pdf-online'
    | '/print-and-post-documents-online'
    | '/pro'
    | '/send'
    | '/send-a-letter-without-a-printer'
    | '/send-business-documents-by-mail'
    | '/send-business-letter-online'
    | '/send-cancellation-letter-online'
    | '/send-cease-and-desist-letter'
    | '/send-complaint-letter-online'
    | '/send-demand-letter-online'
    | '/send-documents-by-mail-online'
    | '/send-insurance-documents-by-mail'
    | '/send-invoice-by-mail'
    | '/send-letter-online'
    | '/send-letter-to-bank'
    | '/send-letter-to-client'
    | '/send-letter-to-company'
    | '/send-letter-to-county-clerk'
    | '/send-letter-to-court'
    | '/send-letter-to-court-clerk'
    | '/send-letter-to-dmv'
    | '/send-letter-to-insurance-company'
    | '/send-letter-to-irs'
    | '/send-letter-to-landlord'
    | '/send-letter-to-social-security'
    | '/send-letter-to-tenant'
    | '/send-letter-to-uscis'
    | '/send-medical-records-request-by-mail'
    | '/send-pdf-by-post'
    | '/send-resignation-letter-by-mail'
    | '/send-school-documents-by-mail'
    | '/send-signed-document-online'
    | '/templates'
    | '/write'
    | '/api/ai-assist'
    | '/orders/$id'
    | '/orders/'
    | '/api/internal/cleanup-drafts'
    | '/api/internal/health'
    | '/api/internal/process-scheduled'
    | '/api/public/lob-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BulkRoute: typeof BulkRoute
  CertifiedMailGuideRoute: typeof CertifiedMailGuideRoute
  FutureSelfRoute: typeof FutureSelfRoute
  MailAContractOnlineRoute: typeof MailAContractOnlineRoute
  MailAPdfRoute: typeof MailAPdfRoute
  MailDocumentsWithoutPrinterRoute: typeof MailDocumentsWithoutPrinterRoute
  MailFormsOnlineRoute: typeof MailFormsOnlineRoute
  MailPaperworkOnlineRoute: typeof MailPaperworkOnlineRoute
  MailTaxDocumentsOnlineRoute: typeof MailTaxDocumentsOnlineRoute
  PrintAndMailADocumentOnlineRoute: typeof PrintAndMailADocumentOnlineRoute
  PrintAndMailPdfOnlineRoute: typeof PrintAndMailPdfOnlineRoute
  PrintAndPostDocumentsOnlineRoute: typeof PrintAndPostDocumentsOnlineRoute
  ProRoute: typeof ProRoute
  SendRoute: typeof SendRoute
  SendALetterWithoutAPrinterRoute: typeof SendALetterWithoutAPrinterRoute
  SendBusinessDocumentsByMailRoute: typeof SendBusinessDocumentsByMailRoute
  SendBusinessLetterOnlineRoute: typeof SendBusinessLetterOnlineRoute
  SendCancellationLetterOnlineRoute: typeof SendCancellationLetterOnlineRoute
  SendCeaseAndDesistLetterRoute: typeof SendCeaseAndDesistLetterRoute
  SendComplaintLetterOnlineRoute: typeof SendComplaintLetterOnlineRoute
  SendDemandLetterOnlineRoute: typeof SendDemandLetterOnlineRoute
  SendDocumentsByMailOnlineRoute: typeof SendDocumentsByMailOnlineRoute
  SendInsuranceDocumentsByMailRoute: typeof SendInsuranceDocumentsByMailRoute
  SendInvoiceByMailRoute: typeof SendInvoiceByMailRoute
  SendLetterOnlineRoute: typeof SendLetterOnlineRoute
  SendLetterToBankRoute: typeof SendLetterToBankRoute
  SendLetterToClientRoute: typeof SendLetterToClientRoute
  SendLetterToCompanyRoute: typeof SendLetterToCompanyRoute
  SendLetterToCountyClerkRoute: typeof SendLetterToCountyClerkRoute
  SendLetterToCourtRoute: typeof SendLetterToCourtRoute
  SendLetterToCourtClerkRoute: typeof SendLetterToCourtClerkRoute
  SendLetterToDmvRoute: typeof SendLetterToDmvRoute
  SendLetterToInsuranceCompanyRoute: typeof SendLetterToInsuranceCompanyRoute
  SendLetterToIrsRoute: typeof SendLetterToIrsRoute
  SendLetterToLandlordRoute: typeof SendLetterToLandlordRoute
  SendLetterToSocialSecurityRoute: typeof SendLetterToSocialSecurityRoute
  SendLetterToTenantRoute: typeof SendLetterToTenantRoute
  SendLetterToUscisRoute: typeof SendLetterToUscisRoute
  SendMedicalRecordsRequestByMailRoute: typeof SendMedicalRecordsRequestByMailRoute
  SendPdfByPostRoute: typeof SendPdfByPostRoute
  SendResignationLetterByMailRoute: typeof SendResignationLetterByMailRoute
  SendSchoolDocumentsByMailRoute: typeof SendSchoolDocumentsByMailRoute
  SendSignedDocumentOnlineRoute: typeof SendSignedDocumentOnlineRoute
  TemplatesRoute: typeof TemplatesRoute
  WriteRoute: typeof WriteRoute
  ApiAiAssistRoute: typeof ApiAiAssistRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiInternalCleanupDraftsRoute: typeof ApiInternalCleanupDraftsRoute
  ApiInternalHealthRoute: typeof ApiInternalHealthRoute
  ApiInternalProcessScheduledRoute: typeof ApiInternalProcessScheduledRoute
  ApiPublicLobWebhookRoute: typeof ApiPublicLobWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certified-mail-guide': {
      id: '/certified-mail-guide'
      path: '/certified-mail-guide'
      fullPath: '/certified-mail-guide'
      preLoaderRoute: typeof CertifiedMailGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-self': {
      id: '/future-self'
      path: '/future-self'
      fullPath: '/future-self'
      preLoaderRoute: typeof FutureSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-contract-online': {
      id: '/mail-a-contract-online'
      path: '/mail-a-contract-online'
      fullPath: '/mail-a-contract-online'
      preLoaderRoute: typeof MailAContractOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-pdf': {
      id: '/mail-a-pdf'
      path: '/mail-a-pdf'
      fullPath: '/mail-a-pdf'
      preLoaderRoute: typeof MailAPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-documents-without-printer': {
      id: '/mail-documents-without-printer'
      path: '/mail-documents-without-printer'
      fullPath: '/mail-documents-without-printer'
      preLoaderRoute: typeof MailDocumentsWithoutPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-forms-online': {
      id: '/mail-forms-online'
      path: '/mail-forms-online'
      fullPath: '/mail-forms-online'
      preLoaderRoute: typeof MailFormsOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-paperwork-online': {
      id: '/mail-paperwork-online'
      path: '/mail-paperwork-online'
      fullPath: '/mail-paperwork-online'
      preLoaderRoute: typeof MailPaperworkOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-tax-documents-online': {
      id: '/mail-tax-documents-online'
      path: '/mail-tax-documents-online'
      fullPath: '/mail-tax-documents-online'
      preLoaderRoute: typeof MailTaxDocumentsOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-and-mail-a-document-online': {
      id: '/print-and-mail-a-document-online'
      path: '/print-and-mail-a-document-online'
      fullPath: '/print-and-mail-a-document-online'
      preLoaderRoute: typeof PrintAndMailADocumentOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-and-mail-pdf-online': {
      id: '/print-and-mail-pdf-online'
      path: '/print-and-mail-pdf-online'
      fullPath: '/print-and-mail-pdf-online'
      preLoaderRoute: typeof PrintAndMailPdfOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-and-post-documents-online': {
      id: '/print-and-post-documents-online'
      path: '/print-and-post-documents-online'
      fullPath: '/print-and-post-documents-online'
      preLoaderRoute: typeof PrintAndPostDocumentsOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-a-letter-without-a-printer': {
      id: '/send-a-letter-without-a-printer'
      path: '/send-a-letter-without-a-printer'
      fullPath: '/send-a-letter-without-a-printer'
      preLoaderRoute: typeof SendALetterWithoutAPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-business-documents-by-mail': {
      id: '/send-business-documents-by-mail'
      path: '/send-business-documents-by-mail'
      fullPath: '/send-business-documents-by-mail'
      preLoaderRoute: typeof SendBusinessDocumentsByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-business-letter-online': {
      id: '/send-business-letter-online'
      path: '/send-business-letter-online'
      fullPath: '/send-business-letter-online'
      preLoaderRoute: typeof SendBusinessLetterOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-cancellation-letter-online': {
      id: '/send-cancellation-letter-online'
      path: '/send-cancellation-letter-online'
      fullPath: '/send-cancellation-letter-online'
      preLoaderRoute: typeof SendCancellationLetterOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-cease-and-desist-letter': {
      id: '/send-cease-and-desist-letter'
      path: '/send-cease-and-desist-letter'
      fullPath: '/send-cease-and-desist-letter'
      preLoaderRoute: typeof SendCeaseAndDesistLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-complaint-letter-online': {
      id: '/send-complaint-letter-online'
      path: '/send-complaint-letter-online'
      fullPath: '/send-complaint-letter-online'
      preLoaderRoute: typeof SendComplaintLetterOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-demand-letter-online': {
      id: '/send-demand-letter-online'
      path: '/send-demand-letter-online'
      fullPath: '/send-demand-letter-online'
      preLoaderRoute: typeof SendDemandLetterOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-documents-by-mail-online': {
      id: '/send-documents-by-mail-online'
      path: '/send-documents-by-mail-online'
      fullPath: '/send-documents-by-mail-online'
      preLoaderRoute: typeof SendDocumentsByMailOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-insurance-documents-by-mail': {
      id: '/send-insurance-documents-by-mail'
      path: '/send-insurance-documents-by-mail'
      fullPath: '/send-insurance-documents-by-mail'
      preLoaderRoute: typeof SendInsuranceDocumentsByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-invoice-by-mail': {
      id: '/send-invoice-by-mail'
      path: '/send-invoice-by-mail'
      fullPath: '/send-invoice-by-mail'
      preLoaderRoute: typeof SendInvoiceByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-online': {
      id: '/send-letter-online'
      path: '/send-letter-online'
      fullPath: '/send-letter-online'
      preLoaderRoute: typeof SendLetterOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-bank': {
      id: '/send-letter-to-bank'
      path: '/send-letter-to-bank'
      fullPath: '/send-letter-to-bank'
      preLoaderRoute: typeof SendLetterToBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-client': {
      id: '/send-letter-to-client'
      path: '/send-letter-to-client'
      fullPath: '/send-letter-to-client'
      preLoaderRoute: typeof SendLetterToClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-company': {
      id: '/send-letter-to-company'
      path: '/send-letter-to-company'
      fullPath: '/send-letter-to-company'
      preLoaderRoute: typeof SendLetterToCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-county-clerk': {
      id: '/send-letter-to-county-clerk'
      path: '/send-letter-to-county-clerk'
      fullPath: '/send-letter-to-county-clerk'
      preLoaderRoute: typeof SendLetterToCountyClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-court': {
      id: '/send-letter-to-court'
      path: '/send-letter-to-court'
      fullPath: '/send-letter-to-court'
      preLoaderRoute: typeof SendLetterToCourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-court-clerk': {
      id: '/send-letter-to-court-clerk'
      path: '/send-letter-to-court-clerk'
      fullPath: '/send-letter-to-court-clerk'
      preLoaderRoute: typeof SendLetterToCourtClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-dmv': {
      id: '/send-letter-to-dmv'
      path: '/send-letter-to-dmv'
      fullPath: '/send-letter-to-dmv'
      preLoaderRoute: typeof SendLetterToDmvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-insurance-company': {
      id: '/send-letter-to-insurance-company'
      path: '/send-letter-to-insurance-company'
      fullPath: '/send-letter-to-insurance-company'
      preLoaderRoute: typeof SendLetterToInsuranceCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-irs': {
      id: '/send-letter-to-irs'
      path: '/send-letter-to-irs'
      fullPath: '/send-letter-to-irs'
      preLoaderRoute: typeof SendLetterToIrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-landlord': {
      id: '/send-letter-to-landlord'
      path: '/send-letter-to-landlord'
      fullPath: '/send-letter-to-landlord'
      preLoaderRoute: typeof SendLetterToLandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-social-security': {
      id: '/send-letter-to-social-security'
      path: '/send-letter-to-social-security'
      fullPath: '/send-letter-to-social-security'
      preLoaderRoute: typeof SendLetterToSocialSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-tenant': {
      id: '/send-letter-to-tenant'
      path: '/send-letter-to-tenant'
      fullPath: '/send-letter-to-tenant'
      preLoaderRoute: typeof SendLetterToTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-letter-to-uscis': {
      id: '/send-letter-to-uscis'
      path: '/send-letter-to-uscis'
      fullPath: '/send-letter-to-uscis'
      preLoaderRoute: typeof SendLetterToUscisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-medical-records-request-by-mail': {
      id: '/send-medical-records-request-by-mail'
      path: '/send-medical-records-request-by-mail'
      fullPath: '/send-medical-records-request-by-mail'
      preLoaderRoute: typeof SendMedicalRecordsRequestByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-pdf-by-post': {
      id: '/send-pdf-by-post'
      path: '/send-pdf-by-post'
      fullPath: '/send-pdf-by-post'
      preLoaderRoute: typeof SendPdfByPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-resignation-letter-by-mail': {
      id: '/send-resignation-letter-by-mail'
      path: '/send-resignation-letter-by-mail'
      fullPath: '/send-resignation-letter-by-mail'
      preLoaderRoute: typeof SendResignationLetterByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-school-documents-by-mail': {
      id: '/send-school-documents-by-mail'
      path: '/send-school-documents-by-mail'
      fullPath: '/send-school-documents-by-mail'
      preLoaderRoute: typeof SendSchoolDocumentsByMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-signed-document-online': {
      id: '/send-signed-document-online'
      path: '/send-signed-document-online'
      fullPath: '/send-signed-document-online'
      preLoaderRoute: typeof SendSignedDocumentOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-assist': {
      id: '/api/ai-assist'
      path: '/api/ai-assist'
      fullPath: '/api/ai-assist'
      preLoaderRoute: typeof ApiAiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/cleanup-drafts': {
      id: '/api/internal/cleanup-drafts'
      path: '/api/internal/cleanup-drafts'
      fullPath: '/api/internal/cleanup-drafts'
      preLoaderRoute: typeof ApiInternalCleanupDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/health': {
      id: '/api/internal/health'
      path: '/api/internal/health'
      fullPath: '/api/internal/health'
      preLoaderRoute: typeof ApiInternalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/process-scheduled': {
      id: '/api/internal/process-scheduled'
      path: '/api/internal/process-scheduled'
      fullPath: '/api/internal/process-scheduled'
      preLoaderRoute: typeof ApiInternalProcessScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lob-webhook': {
      id: '/api/public/lob-webhook'
      path: '/api/public/lob-webhook'
      fullPath: '/api/public/lob-webhook'
      preLoaderRoute: typeof ApiPublicLobWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BulkRoute: BulkRoute,
  CertifiedMailGuideRoute: CertifiedMailGuideRoute,
  FutureSelfRoute: FutureSelfRoute,
  MailAContractOnlineRoute: MailAContractOnlineRoute,
  MailAPdfRoute: MailAPdfRoute,
  MailDocumentsWithoutPrinterRoute: MailDocumentsWithoutPrinterRoute,
  MailFormsOnlineRoute: MailFormsOnlineRoute,
  MailPaperworkOnlineRoute: MailPaperworkOnlineRoute,
  MailTaxDocumentsOnlineRoute: MailTaxDocumentsOnlineRoute,
  PrintAndMailADocumentOnlineRoute: PrintAndMailADocumentOnlineRoute,
  PrintAndMailPdfOnlineRoute: PrintAndMailPdfOnlineRoute,
  PrintAndPostDocumentsOnlineRoute: PrintAndPostDocumentsOnlineRoute,
  ProRoute: ProRoute,
  SendRoute: SendRoute,
  SendALetterWithoutAPrinterRoute: SendALetterWithoutAPrinterRoute,
  SendBusinessDocumentsByMailRoute: SendBusinessDocumentsByMailRoute,
  SendBusinessLetterOnlineRoute: SendBusinessLetterOnlineRoute,
  SendCancellationLetterOnlineRoute: SendCancellationLetterOnlineRoute,
  SendCeaseAndDesistLetterRoute: SendCeaseAndDesistLetterRoute,
  SendComplaintLetterOnlineRoute: SendComplaintLetterOnlineRoute,
  SendDemandLetterOnlineRoute: SendDemandLetterOnlineRoute,
  SendDocumentsByMailOnlineRoute: SendDocumentsByMailOnlineRoute,
  SendInsuranceDocumentsByMailRoute: SendInsuranceDocumentsByMailRoute,
  SendInvoiceByMailRoute: SendInvoiceByMailRoute,
  SendLetterOnlineRoute: SendLetterOnlineRoute,
  SendLetterToBankRoute: SendLetterToBankRoute,
  SendLetterToClientRoute: SendLetterToClientRoute,
  SendLetterToCompanyRoute: SendLetterToCompanyRoute,
  SendLetterToCountyClerkRoute: SendLetterToCountyClerkRoute,
  SendLetterToCourtRoute: SendLetterToCourtRoute,
  SendLetterToCourtClerkRoute: SendLetterToCourtClerkRoute,
  SendLetterToDmvRoute: SendLetterToDmvRoute,
  SendLetterToInsuranceCompanyRoute: SendLetterToInsuranceCompanyRoute,
  SendLetterToIrsRoute: SendLetterToIrsRoute,
  SendLetterToLandlordRoute: SendLetterToLandlordRoute,
  SendLetterToSocialSecurityRoute: SendLetterToSocialSecurityRoute,
  SendLetterToTenantRoute: SendLetterToTenantRoute,
  SendLetterToUscisRoute: SendLetterToUscisRoute,
  SendMedicalRecordsRequestByMailRoute: SendMedicalRecordsRequestByMailRoute,
  SendPdfByPostRoute: SendPdfByPostRoute,
  SendResignationLetterByMailRoute: SendResignationLetterByMailRoute,
  SendSchoolDocumentsByMailRoute: SendSchoolDocumentsByMailRoute,
  SendSignedDocumentOnlineRoute: SendSignedDocumentOnlineRoute,
  TemplatesRoute: TemplatesRoute,
  WriteRoute: WriteRoute,
  ApiAiAssistRoute: ApiAiAssistRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiInternalCleanupDraftsRoute: ApiInternalCleanupDraftsRoute,
  ApiInternalHealthRoute: ApiInternalHealthRoute,
  ApiInternalProcessScheduledRoute: ApiInternalProcessScheduledRoute,
  ApiPublicLobWebhookRoute: ApiPublicLobWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
