import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export const Route = createFileRoute("/respond-to-a-government-notice")({ head: () => ({ meta: [
  { title: "Respond to a Government Notice | MailMyPDF" },
  { name: "description", content: "Received a government notice? Organize the notice, understand the requested action and deadline, prepare a response, and create a documented mailing." },
], links: [{ rel: "canonical", href: "/respond-to-a-government-notice" }] }), component: Page });

function Page() { return <div className="min-h-screen"><SiteHeader /><main>
  <section className="border-b border-rule/60"><div className="mx-auto max-w-5xl px-6 py-20 md:py-28"><div className="postmark w-fit">Government notices</div><h1 className="mt-6 max-w-4xl text-5xl leading-[1.02] md:text-7xl">Received a government notice? Start with what it actually says.</h1><p className="mt-7 max-w-2xl text-xl text-ink-soft">Organize the notice, identify its dates and requested action, gather the documents that matter, and prepare a response you can review before mailing.</p><Link to="/send" className="mt-8 inline-flex rounded-full bg-cobalt px-7 py-3.5 font-medium text-white">Start with your document →</Link></div></section>
  <section className="bg-paper-deep/40 border-b border-rule/60"><div className="mx-auto max-w-6xl px-6 py-20"><h2 className="text-3xl md:text-4xl">A response workflow built around the notice</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{[["Read","Identify the sender, reference number, dates, requested action, and stated deadline."],["Organize","Keep the notice and supporting documents together."],["Prepare","Build a focused response that addresses the actual request."],["Send","Choose an appropriate mailing method and preserve the available mailing record."]].map(([t,d],i)=><div className="envelope-card p-6" key={t}><div className="font-mono text-xs text-cobalt">0{i+1}</div><h3 className="mt-3 font-serif text-2xl">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></div>)}</div></div></section>
  <section><div className="mx-auto max-w-5xl px-6 py-20"><h2 className="text-3xl md:text-4xl">Common government correspondence</h2><div className="mt-8 grid gap-x-10 md:grid-cols-2">{["Agency notices","Tax correspondence","Code enforcement notices","Compliance notices","Administrative decisions","Permit correspondence","Benefits decisions","Records and information requests"].map(x=><div key={x} className="border-b border-rule/70 py-4 text-lg">{x}</div>)}</div><p className="mt-8 text-sm text-muted-foreground">Mailing a response does not by itself establish that a particular legal or administrative filing requirement has been satisfied. Follow the instructions in the notice and any applicable rules.</p></div></section>
  <section className="border-y border-rule/60 bg-paper-deep/40"><div className="mx-auto max-w-4xl px-6 py-20 text-center"><h2 className="text-3xl md:text-4xl">Already have your response?</h2><p className="mt-4 text-lg text-ink-soft">Upload the final document and move directly to mailing.</p><Link to="/send" className="mt-7 inline-flex rounded-full bg-cobalt px-7 py-3.5 font-medium text-white">Upload response →</Link></div></section>
</main><SiteFooter /></div>; }
