export type RecordsRequestWorkflow = {
  id: string;
  name: string;
  category: "federal" | "state" | "local" | "public-safety" | "property" | "education" | "environment" | "elections" | "immigration" | "courts";
  requestType: string;
  description: string;
  audience: string;
  recordScope: string[];
  requiredInputs: string[];
  evidenceChecklist: string[];
  reviewWarnings: string[];
  promptContext: string;
  defaultMailType: "certified" | "certified_return_receipt" | "registered";
};

export const RECORDS_REQUEST_WORKFLOWS: readonly RecordsRequestWorkflow[] = [
  {
    id: "federal-foia",
    name: "Federal FOIA Request",
    category: "federal",
    requestType: "Federal FOIA request",
    description: "Request records held by a federal executive agency under the Freedom of Information Act.",
    audience: "Individuals, journalists, researchers, businesses, and advocates seeking federal agency records.",
    recordScope: ["agency records", "communications", "policies", "reports", "datasets", "case files"],
    requiredInputs: ["agency", "records description", "time frame", "requester identity", "contact information"],
    evidenceChecklist: ["specific record description", "date/time range", "known case or reference number", "fee preference", "expedited-processing basis if requested"],
    reviewWarnings: ["Do not promise a statutory deadline without identifying the agency and applicable rule.", "Do not request records that are clearly exempt without warning the requester about possible withholding/redaction."],
    promptContext: "Treat this as a federal FOIA request. Distinguish FOIA from agency-specific privacy or records procedures. Never invent a federal response deadline or exemption conclusion; flag uncertainty.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "state-public-records",
    name: "State Public Records Request",
    category: "state",
    requestType: "State public records request",
    description: "Prepare a state-level public records request using the identified state's public-records law and agency process.",
    audience: "Residents, journalists, businesses, researchers, and advocates requesting state-government records.",
    recordScope: ["state agency records", "emails", "reports", "contracts", "policies", "datasets"],
    requiredInputs: ["state", "agency", "records description", "time frame", "requester identity"],
    evidenceChecklist: ["state identified", "agency identified", "precise records description", "time frame", "known exemption-sensitive content"],
    reviewWarnings: ["State deadlines and fee rules vary. Verify the identified state's current rule before relying on timing language.", "Do not invent a statutory citation."],
    promptContext: "Treat this as a state public-records request. The state must be identified before giving deadline or fee guidance. Never fabricate a statute or statewide response period.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "local-government-records",
    name: "Local Government Records Request",
    category: "local",
    requestType: "Local/municipal records request",
    description: "Request records from a city, county, township, district, or other local government body.",
    audience: "Residents, businesses, property owners, journalists, and advocates.",
    recordScope: ["municipal records", "county records", "meeting materials", "permits", "contracts", "inspection records"],
    requiredInputs: ["jurisdiction", "custodian/agency", "records description", "time frame"],
    evidenceChecklist: ["jurisdiction", "custodian name or office if known", "specific record types", "date range"],
    reviewWarnings: ["Local custodians and procedures differ. Do not assume a state-wide process applies.", "Avoid broad, vague requests that are difficult to search."],
    promptContext: "Treat this as a local-government public-records request. Optimize for a specific custodian, department, record type, and date range. Do not invent local rules.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "police-incident-records",
    name: "Police Incident Records",
    category: "public-safety",
    requestType: "Police incident records request",
    description: "Request incident reports, supplements, dispatch records, and related law-enforcement records.",
    audience: "Individuals, victims, authorized representatives, journalists, and researchers.",
    recordScope: ["incident reports", "supplemental reports", "dispatch logs", "CAD records", "related correspondence"],
    requiredInputs: ["law-enforcement agency", "incident date", "location or case number", "requester identity"],
    evidenceChecklist: ["incident/case number", "date range", "location", "names if known", "authorization or identity proof where relevant"],
    reviewWarnings: ["Law-enforcement exemptions and privacy restrictions may limit disclosure.", "Do not promise release of protected investigative information."],
    promptContext: "Treat this as a law-enforcement records request. Be explicit about possible exemptions, privacy restrictions, and investigative withholding without asserting that a particular exemption applies unless established.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "body-camera-records",
    name: "Body Camera / Video Records",
    category: "public-safety",
    requestType: "Body-camera or video records request",
    description: "Request body-camera, dash-camera, surveillance, or other government-held video records.",
    audience: "Individuals, attorneys, journalists, researchers, and authorized representatives.",
    recordScope: ["body-camera video", "dash-camera video", "surveillance video", "related metadata", "incident indexes"],
    requiredInputs: ["agency", "incident/event", "date/time", "location", "requester identity"],
    evidenceChecklist: ["exact date/time window", "location", "incident/case number", "officer/unit identifiers if known"],
    reviewWarnings: ["Video may contain privacy-protected or investigative material.", "Ask for preservation when deletion/retention timing is a material concern, but do not state a legal preservation duty without authority."],
    promptContext: "Treat this as a government video-records request. Prioritize exact time windows, location, incident number, and preservation language where the user wants it. Do not invent retention periods.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "911-dispatch-records",
    name: "911 / Dispatch Records",
    category: "public-safety",
    requestType: "911 or dispatch records request",
    description: "Request 911 call records, dispatch logs, CAD records, and related communications.",
    audience: "Callers, involved parties, journalists, researchers, and authorized representatives.",
    recordScope: ["911 audio", "CAD logs", "dispatch notes", "radio traffic", "call metadata"],
    requiredInputs: ["agency or dispatch center", "date", "approximate time", "location", "incident details"],
    evidenceChecklist: ["date", "time window", "location", "incident/call description", "caller name if known"],
    reviewWarnings: ["Emergency communications can contain protected personal information or sensitive operational data.", "Do not claim that audio is releasable without confirming the applicable local rule."],
    promptContext: "Treat this as a 911/dispatch records request. Require a narrow time window and location. Flag sensitive-personal-information concerns without inventing a disclosure rule.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "public-employee-records",
    name: "Public Employee Records",
    category: "state",
    requestType: "Public employee records request",
    description: "Request records concerning a government employee when those records are subject to disclosure.",
    audience: "Journalists, researchers, individuals, and organizations with a legitimate records request.",
    recordScope: ["employment records", "disciplinary records", "complaints", "training records", "policies and assignments"],
    requiredInputs: ["agency", "employee name or identifier", "record categories", "time frame"],
    evidenceChecklist: ["employee identity", "agency", "record categories", "date range", "purpose/context"],
    reviewWarnings: ["Personnel privacy restrictions can be substantial.", "Do not assume disciplinary or medical records are public."],
    promptContext: "Treat this as a public-employee-records request. Avoid overclaiming availability of personnel, medical, or disciplinary records. Suggest narrower public-facing categories when appropriate.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "procurement-contract-records",
    name: "Procurement & Contract Records",
    category: "state",
    requestType: "Procurement and contract records request",
    description: "Request bids, contracts, amendments, invoices, procurement evaluations, and award records.",
    audience: "Businesses, journalists, watchdogs, researchers, and competitors.",
    recordScope: ["RFP/RFQ materials", "bids", "contracts", "amendments", "invoices", "evaluation records", "award documents"],
    requiredInputs: ["agency", "procurement/project", "date range", "vendor or contract identifier"],
    evidenceChecklist: ["solicitation number", "contract number", "vendor", "award date", "records sought"],
    reviewWarnings: ["Bid and procurement materials may contain protected information before/after award depending on jurisdiction.", "Separate active procurement material from historical contract records."],
    promptContext: "Treat this as a procurement/contract records request. Prioritize solicitation and contract identifiers and distinguish active procurement material from completed contracts.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "permits-licenses-records",
    name: "Permits, Licenses & Inspections",
    category: "local",
    requestType: "Permits, licenses, and inspection records request",
    description: "Request permits, inspection reports, code-enforcement records, and professional or business licensing records held by government.",
    audience: "Property owners, buyers, businesses, journalists, researchers, and residents.",
    recordScope: ["building permits", "inspection reports", "code-enforcement records", "business licenses", "professional licenses"],
    requiredInputs: ["jurisdiction", "property/person/business", "record type", "time range"],
    evidenceChecklist: ["address or license number", "jurisdiction", "record type", "date range"],
    reviewWarnings: ["Some licensing or code-enforcement material may contain protected personal information.", "Use a property address or license number where possible."],
    promptContext: "Treat this as a permits/licenses/inspection request. Make the request searchable by address, permit number, license number, or case number.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "property-assessment-records",
    name: "Property & Assessment Records",
    category: "property",
    requestType: "Property and assessment records request",
    description: "Request appraisal, assessment, tax-lot, permit-history, and related public property records.",
    audience: "Property owners, buyers, researchers, businesses, and journalists.",
    recordScope: ["assessments", "appraisal records", "parcel records", "tax-lot history", "permit history"],
    requiredInputs: ["jurisdiction", "property address or parcel number", "record categories", "time range"],
    evidenceChecklist: ["parcel/APN", "property address", "assessment year or date range", "specific record category"],
    reviewWarnings: ["Property and tax records may be provided through established public portals rather than a formal request process.", "Do not imply a records request is necessary when the agency already offers direct public access."],
    promptContext: "Treat this as a property/assessment records request. First consider whether the record is already available through a public portal; if so, flag that before drafting.",
    defaultMailType: "certified",
  },
  {
    id: "education-school-records",
    name: "Education & School Records",
    category: "education",
    requestType: "Education or school records request",
    description: "Request records held by a public school district, education agency, or other public educational body.",
    audience: "Parents, students, journalists, researchers, and authorized representatives.",
    recordScope: ["board records", "policies", "contracts", "communications", "budgets", "non-privileged administrative records"],
    requiredInputs: ["school/district/agency", "record categories", "time range", "requester identity"],
    evidenceChecklist: ["district/agency", "record categories", "time frame", "specific meeting/project if known"],
    reviewWarnings: ["Student education records can be subject to significant privacy protections.", "Do not treat personally identifiable student records as ordinary public records."],
    promptContext: "Treat this as a public-education records request. Prefer administrative/public records and explicitly flag student privacy concerns when the request could implicate education records.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "environmental-records",
    name: "Environmental & Regulatory Records",
    category: "environment",
    requestType: "Environmental or regulatory records request",
    description: "Request permits, inspection, enforcement, monitoring, and environmental compliance records.",
    audience: "Residents, businesses, environmental groups, journalists, and researchers.",
    recordScope: ["permits", "inspection reports", "enforcement records", "monitoring data", "complaints", "compliance reports"],
    requiredInputs: ["agency", "site/facility", "record type", "time range"],
    evidenceChecklist: ["facility/address", "permit number if known", "time frame", "specific environmental medium or program"],
    reviewWarnings: ["Industrial/confidential information may be protected.", "Do not invent agency program names or enforcement authority."],
    promptContext: "Treat this as an environmental/regulatory records request. Make the request site-specific and program-specific where possible and flag confidentiality concerns.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "election-records",
    name: "Election & Campaign Records",
    category: "elections",
    requestType: "Election or campaign records request",
    description: "Request public election-administration and campaign-finance records held by the responsible public office.",
    audience: "Candidates, campaigns, journalists, watchdog groups, researchers, and voters.",
    recordScope: ["campaign filings", "ballot materials", "election administration records", "audit materials", "official correspondence"],
    requiredInputs: ["jurisdiction", "office/agency", "election or campaign", "record categories", "time range"],
    evidenceChecklist: ["election date", "candidate/campaign", "office", "record type", "jurisdiction"],
    reviewWarnings: ["Campaign-finance records may already be available through online databases.", "Do not assume a local clerk is the correct custodian for every election record."],
    promptContext: "Treat this as an election/campaign records request. First identify the likely custodian and whether the requested data is already published online.",
    defaultMailType: "certified",
  },
  {
    id: "immigration-foia-pa",
    name: "Immigration FOIA / Privacy Act Records",
    category: "immigration",
    requestType: "Immigration records (FOIA/PA)",
    description: "Prepare a request for immigration records from the appropriate federal component, including agency-record and Privacy Act considerations.",
    audience: "Individuals, attorneys, representatives, and authorized requesters seeking immigration records.",
    recordScope: ["immigration history", "A-files", "agency correspondence", "case records", "adjudication records"],
    requiredInputs: ["agency/component", "subject identity", "A-number or identifier if known", "records sought", "requester authorization"],
    evidenceChecklist: ["full name", "date of birth", "A-number or other identifier", "agency/component", "signed authorization where required"],
    reviewWarnings: ["Privacy Act and identity/authorization requirements may apply.", "Do not claim that a signature or identity document is universally required without identifying the agency process."],
    promptContext: "Treat this as an immigration FOIA/Privacy Act request. Separate the subject's own records from third-party records and flag identity/authorization requirements without inventing them.",
    defaultMailType: "certified_return_receipt",
  },
  {
    id: "court-public-access",
    name: "Court & Judicial Public Access Request",
    category: "courts",
    requestType: "Court/public-access records request",
    description: "Prepare a request to a court or judicial records custodian when records are obtained through a request process rather than the normal case portal.",
    audience: "Litigants, researchers, journalists, and members of the public.",
    recordScope: ["dockets", "administrative court records", "case files where publicly accessible", "orders", "transcripts where available"],
    requiredInputs: ["court/jurisdiction", "case number or record type", "records sought", "time frame"],
    evidenceChecklist: ["court", "case number", "record type", "date range", "requester contact information"],
    reviewWarnings: ["Court-access rules are separate from federal FOIA and state public-records laws.", "Do not label a court request as FOIA unless the custodian and governing process actually support that treatment."],
    promptContext: "Treat this as a court/judicial public-access request, not automatically as FOIA. Identify the court and record type first and avoid asserting access rights without jurisdiction-specific support.",
    defaultMailType: "certified",
  },
] as const;

export const recordsRequestWorkflowMap = Object.fromEntries(RECORDS_REQUEST_WORKFLOWS.map((workflow) => [workflow.id, workflow])) as Record<string, RecordsRequestWorkflow>;

export function getRecordsRequestWorkflow(id: string): RecordsRequestWorkflow | null {
  return recordsRequestWorkflowMap[id] ?? null;
}
