import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { confirmGovReplyExtraction, getGovReplyCase } from "@/lib/govreply.functions";
export const Route = createFileRoute("/govreply/cases/$id/review")({ validateSearch: (search: Record<string, unknown>) => ({ token: typeof search.token === "string" ? search.token : "" }), head: () => ({ meta: [{ title: "Review your IRS notice — GovReply" }] }), component: ExtractionReview });
type Address = { name: string; line1: string; line2: string; city: string; state: string; postal: string };
function ExtractionReview() { const { id } = Route.useParams(); const { token } = Route.useSearch(); const navigate = useNavigate(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [noticeType, setNoticeType] = useState(""); const [noticeDate, setNoticeDate] = useState(""); const [deadline, setDeadline] = useState(""); const [references, setReferences] = useState(""); const [summary, setSummary] = useState(""); const [address, setAddress] = useState<Address>({ name: "", line1: "", line2: "", city: "", state: "", postal: "" }); const [warnings, setWarnings] = useState<string[]>([]); const [saving, setSaving] = useState(false);
useEffect(() => { if (!token) { setError("This case link is missing its recovery token."); setLoading(false); return; } getGovReplyCase({ data: { caseId: id, token } }).then((result) => { if (!result) throw new Error("Case not found."); const extraction = result.extracted ?? {}; setNoticeType(extraction.notice_type ?? ""); setNoticeDate(extraction.notice_date ?? result.notice_date ?? ""); setDeadline(extraction.response_deadline ?? result.response_deadline ?? ""); setReferences((extraction.reference_numbers ?? result.reference_numbers ?? []).join(", ")); setSummary(extraction.summary_plain ?? result.requested_action_summary ?? ""); if (extraction.response_address) setAddress({ line2: "", ...extraction.response_address }); setWarnings(extraction.warnings ?? []); }).catch((err) => setError(err instanceof Error ? err.message : "Could not load the case.")).finally(() => setLoading(false)); }, [id, token]);
async function confirm() { setError(null); setSaving(true); try { const result = await confirmGovReplyExtraction({ data: { caseId: id, token, extraction: { agency: "irs", notice_type: noticeType || null, notice_type_confidence: null, notice_date: noticeDate || null, response_deadline: deadline || null, reference_numbers: references.split(",").map((v) => v.trim()).filter(Boolean), tax_year: null, response_address: address, requested_actions: [], summary_plain: summary || null, warnings } } }); if (!result) throw new Error("The case could not be confirmed."); navigate({ to: "/govreply/cases/$id", params: { id }, search: { token } }); } catch (err) { setError(err instanceof Error ? err.message : "Could not confirm the extraction."); } finally { setSaving(false); } }
if (loading) return <PageShell><p className="text-muted-foreground">Loading your notice…</p></PageShell>;
return <PageShell><div className="postmark w-fit">Step 2 · Review</div><h1 className="mt-6 font-serif text-4xl md:text-5xl">Check what we found.</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Review every important field before we use it. If you can&apos;t find a deadline or address in your notice, leave it blank rather than guessing.</p><div className="mt-10 space-y-6"><section className="rounded-2xl border border-rule bg-card p-6"><h2 className="font-serif text-2xl">Notice details</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Notice type" value={noticeType} onChange={setNoticeType} placeholder="e.g. CP2000" /><Field label="Notice date" type="date" value={noticeDate} onChange={setNoticeDate} /><Field label="Response deadline" type="date" value={deadline} onChange={setDeadline} /><Field label="Reference number(s)" value={references} onChange={setReferences} placeholder="Separate multiple with commas" /></div><label className="mt-5 block"><span className="text-sm font-medium">What the notice is asking</span><textarea value={summary} onChange={(e) => setSummary(e.target.value)} rows={4} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm" /></label></section><section className="rounded-2xl border border-rule bg-card p-6"><h2 className="font-serif text-2xl">Response mailing address</h2><p className="mt-2 text-sm text-muted-foreground">This is the address we would use later for the mailed response.</p><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Name / unit" value={address.name} onChange={(v) => setAddress({ ...address, name: v })} /><Field label="Street" value={address.line1} onChange={(v) => setAddress({ ...address, line1: v })} /><Field label="Line 2" value={address.line2} onChange={(v) => setAddress({ ...address, line2: v })} /><Field label="City" value={address.city} onChange={(v) => setAddress({ ...address, city: v })} /><Field label="State" value={address.state} onChange={(v) => setAddress({ ...address, state: v.toUpperCase().slice(0, 2) })} /><Field label="ZIP" value={address.postal} onChange={(v) => setAddress({ ...address, postal: v })} /></div></section>{warnings.length > 0 && <section className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-6"><h2 className="font-semibold">Review notes</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></section>}{error && <p className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}<button onClick={confirm} disabled={saving} className="w-full rounded-full bg-cobalt px-6 py-3 text-sm font-semibold text-white hover:opacity-90 disabled:opacity-50">{saving ? "Confirming…" : "Confirm notice details"}</button></div></PageShell>; }
function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="block"><span className="text-sm font-medium">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm" /></label>; }
function PageShell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen"><SiteHeader /><main className="mx-auto max-w-4xl px-6 py-16 md:py-24">{children}</main><SiteFooter /></div>; }
