/**
 * GitHub Factory Adapter — real implementation of VerticalFactoryAdapter.
 *
 * Uses the GitHubRepositoryProvider to:
 * 1. Validate the target repository exists
 * 2. Create a branch for the vertical
 * 3. Generate the vertical code
 * 4. Commit all files in a single tree
 * 5. Optionally create a pull request
 *
 * The original MailMyPDF repository is never used as a build target.
 */

import type { FoundryRun, VerticalCandidate } from './foundry-contract.js'
import type { VerticalBuildRequest, VerticalBuildResult } from './factory-adapter.js'
import type { VerticalFactoryAdapter } from './factory-adapter.js'
import type { RepositoryProvider } from './provider-contracts.js'
import { generateVerticalCode } from './vertical-code-generator.js'
import { createManifest, validateManifest, type VerticalManifest } from './vertical-manifest.js'

const ORIGINAL_REPO = 'mycomind4-arch/mailmypdf'

export interface GitHubFactoryConfig {
  repository: RepositoryProvider
  framework: 'next' | 'astro' | 'vite' | 'static'
  createPR: boolean
  domainTemplate: (id: string) => string
}

export class GitHubFactoryAdapter implements VerticalFactoryAdapter {
  private repo: RepositoryProvider
  private framework: GitHubFactoryConfig['framework']
  private createPR: boolean
  private domainTemplate: GitHubFactoryConfig['domainTemplate']

  constructor(config: GitHubFactoryConfig) {
    this.repo = config.repository
    this.framework = config.framework
    this.createPR = config.createPR
    this.domainTemplate = config.domainTemplate
  }

  async createBuild(request: VerticalBuildRequest): Promise<VerticalBuildResult> {
    const { candidate, repository, branch } = request

    // Guard: never build into the original MailMyPDF repository
    if (repository === ORIGINAL_REPO || repository.includes('/mailmypdf')) {
      throw new Error('Cannot create vertical build in the original MailMyPDF repository')
    }

    // Validate the repository exists
    const repoInfo = await this.repo.validateRepository(repository)
    if (!repoInfo.exists) {
      throw new Error(`Repository ${repository} does not exist or is not accessible`)
    }

    // Create the branch
    const branchResult = await this.repo.createBranch(repository, branch)

    // Generate the vertical code
    const domain = this.domainTemplate(candidate.id)
    const codeGen = generateVerticalCode({ candidate, framework: this.framework, domain })

    // Create a manifest for the vertical
    const manifest: VerticalManifest = createManifest({
      id: candidate.id,
      name: candidate.name,
      domain,
      repository,
      branch,
      capabilities: candidate.findings.map((f) => f.source),
      buildConfig: codeGen.buildConfig,
      excludedRepositories: [ORIGINAL_REPO],
    })

    // Validate the manifest
    validateManifest(manifest)

    // Include the manifest as a file in the commit
    const allFiles = [
      ...codeGen.files,
      {
        path: 'vertical-manifest.json',
        content: JSON.stringify(manifest, null, 2),
        description: 'Vertical manifest',
      },
    ]

    // Commit all files in a single tree
    const commitMessage = `feat: generate vertical ${candidate.name} (${candidate.id})\n\nOpportunity score: ${candidate.score.overall}/100\nFramework: ${this.framework}\n\nGenerated by MailMyPDF Vertical Foundry`

    const commit = await this.repo.createTree(
      repository,
      branch,
      allFiles,
      commitMessage,
    )

    // Optionally create a pull request
    if (this.createPR) {
      await this.repo.createPullRequest(
        repository,
        branch,
        repoInfo.defaultBranch,
        `feat: new vertical — ${candidate.name}`,
        `## New Vertical: ${candidate.name}\n\n${candidate.description}\n\n- **Vertical ID:** ${candidate.id}\n- **Opportunity Score:** ${candidate.score.overall}/100\n- **Framework:** ${this.framework}\n- **Commit:** ${commit.commitSha}\n\nGenerated by MailMyPDF Vertical Foundry`,
      )
    }

    return { repository, branch, status: 'CREATED' }
  }
}

/**
 * Stub Factory Adapter — dry-run mode that doesn't touch GitHub.
 * Produces the same result shape for testing and CI.
 */
export class StubFactoryAdapter implements VerticalFactoryAdapter {
  async createBuild(request: VerticalBuildRequest): Promise<VerticalBuildResult> {
    const { repository, branch } = request
    if (repository === ORIGINAL_REPO || repository.includes('/mailmypdf')) {
      throw new Error('Cannot create vertical build in the original MailMyPDF repository')
    }
    return { repository, branch, status: 'PLANNED' }
  }
}
