/**
 * Vertical Code Generator — produces the file set for a generated vertical.
 *
 * Given a VerticalCandidate and build configuration, generates a complete
 * static site (or framework project) that can be deployed to Cloudflare Pages.
 *
 * Generated code never contains credentials, API keys, or secrets.
 * All configuration is injected at deployment time via environment variables.
 */

import type { VerticalCandidate } from './foundry-contract.js'
import type { BuildFile, BuildConfig, BuildFramework } from './vertical-manifest.js'

export interface CodeGenRequest {
  candidate: VerticalCandidate
  framework: BuildFramework
  domain: string
}

export interface CodeGenResult {
  files: BuildFile[]
  buildConfig: BuildConfig
}

export function generateVerticalCode(request: CodeGenRequest): CodeGenResult {
  const { candidate, framework, domain } = request

  switch (framework) {
    case 'static':
      return generateStaticSite(candidate, domain)
    case 'astro':
      return generateAstroSite(candidate, domain)
    case 'next':
      return generateNextSite(candidate, domain)
    case 'vite':
      return generateViteSite(candidate, domain)
    default:
      return generateStaticSite(candidate, domain)
  }
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}

function generateStaticSite(candidate: VerticalCandidate, domain: string): CodeGenResult {
  const files: BuildFile[] = [
    {
      path: 'index.html',
      description: 'Landing page',
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${candidate.name}</title>
  <meta name="description" content="${candidate.description}">
  <link rel="canonical" href="https://${domain}">
  <style>
    :root { --primary: #4f46e5; --bg: #ffffff; --fg: #1f2937; --muted: #6b7280; }
    @media (prefers-color-scheme: dark) { :root { --bg: #111827; --fg: #f3f4f6; --muted: #9ca3af; } }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--fg); min-height: 100vh; display: flex; flex-direction: column; }
    .hero { padding: 4rem 2rem; text-align: center; }
    .hero h1 { font-size: 3rem; font-weight: 800; margin-bottom: 1rem; }
    .hero p { font-size: 1.25rem; color: var(--muted); max-width: 600px; margin: 0 auto 2rem; }
    .cta { display: inline-block; background: var(--primary); color: white; padding: 0.75rem 2rem; border-radius: 0.5rem; text-decoration: none; font-weight: 600; }
    .features { max-width: 960px; margin: 0 auto; padding: 2rem; display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem; }
    .feature { padding: 1.5rem; border: 1px solid var(--muted); border-radius: 0.5rem; }
    .feature h3 { margin-bottom: 0.5rem; }
    .feature p { color: var(--muted); }
    footer { margin-top: auto; padding: 2rem; text-align: center; color: var(--muted); font-size: 0.875rem; }
  </style>
</head>
<body>
  <section class="hero">
    <h1>${candidate.name}</h1>
    <p>${candidate.description}</p>
    <a href="#features" class="cta">Get Started</a>
  </section>
  <section id="features" class="features">
    ${candidate.findings.slice(0, 6).map((f, i) => `<div class="feature"><h3>${escapeHtml(f.source)}</h3><p>${escapeHtml(f.claim)}</p></div>`).join('\n    ')}
  </section>
  <footer>
    <p>&copy; ${new Date().getFullYear()} ${candidate.name}. All rights reserved.</p>
    <p>Generated by MailMyPDF Vertical Foundry</p>
  </footer>
</body>
</html>
`,
    },
    {
      path: 'README.md',
      description: 'Project documentation',
      content: `# ${candidate.name}

${candidate.description}

## Overview

This vertical was generated by the MailMyPDF Vertical Foundry.

- **Vertical ID:** ${candidate.id}
- **Domain:** ${domain}
- **Opportunity Score:** ${candidate.score.overall}/100

## Development

This is a static site. To preview locally:

\`\`\`bash
npx serve .
\`\`\`

## Deployment

Deploy to Cloudflare Pages by connecting this repository and setting the
build output directory to the root.
`,
    },
    {
      path: '_headers',
      description: 'Cloudflare Pages security headers',
      content: `/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains
`,
    },
    {
      path: '_redirects',
      description: 'Cloudflare Pages redirects',
      content: `# SPA fallback (if needed in future)
# /*    /index.html   200
`,
    },
  ]

  const buildConfig: BuildConfig = {
    framework: 'static',
    entryPoint: 'index.html',
    files,
    dependencies: {},
    buildCommand: 'echo "Static site, no build step required"',
    outputDir: '.',
  }

  return { files, buildConfig }
}

function generateAstroSite(candidate: VerticalCandidate, domain: string): CodeGenResult {
  // For now, generate a static site with an astro.config.mjs stub
  const staticResult = generateStaticSite(candidate, domain)
  return {
    files: [
      ...staticResult.files,
      {
        path: 'astro.config.mjs',
        description: 'Astro configuration',
        content: `import { defineConfig } from 'astro/config'\n\nexport default defineConfig({\n  site: 'https://${domain}',\n  output: 'static',\n})\n`,
      },
    ],
    buildConfig: {
      framework: 'astro',
      entryPoint: 'src/pages/index.astro',
      files: staticResult.files,
      dependencies: { astro: '^4.0.0' },
      buildCommand: 'astro build',
      outputDir: 'dist',
    },
  }
}

function generateNextSite(candidate: VerticalCandidate, domain: string): CodeGenResult {
  const staticResult = generateStaticSite(candidate, domain)
  return {
    files: [
      ...staticResult.files,
      {
        path: 'next.config.js',
        description: 'Next.js configuration',
        content: `/** @type {import('next').NextConfig} */\nmodule.exports = {\n  output: 'export',\n  reactStrictMode: true,\n}\n`,
      },
    ],
    buildConfig: {
      framework: 'next',
      entryPoint: 'pages/index.js',
      files: staticResult.files,
      dependencies: { next: '^14.0.0', react: '^18.0.0', 'react-dom': '^18.0.0' },
      buildCommand: 'next build',
      outputDir: 'out',
    },
  }
}

function generateViteSite(candidate: VerticalCandidate, domain: string): CodeGenResult {
  const staticResult = generateStaticSite(candidate, domain)
  return {
    files: [
      ...staticResult.files,
      {
        path: 'vite.config.js',
        description: 'Vite configuration',
        content: `import { defineConfig } from 'vite'\n\nexport default defineConfig({\n  build: { outDir: 'dist' },\n})\n`,
      },
    ],
    buildConfig: {
      framework: 'vite',
      entryPoint: 'index.html',
      files: staticResult.files,
      dependencies: { vite: '^5.0.0' },
      buildCommand: 'vite build',
      outputDir: 'dist',
    },
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
