import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { PRIOR_AUTHORIZATION_DENIAL_PRICING } from "@/domain/prior-authorization-denial-gold";

function calculateTotal(packet: any, method: "standard"|"certified"|"registered") {
  const totalSheets=Math.max(1,Number(packet?.pageCount||1));
  const responseSheets=Math.min(totalSheets,PRIOR_AUTHORIZATION_DENIAL_PRICING.includedResponsePages);
  const supportingSheets=Math.max(0,totalSheets-responseSheets);
  const extraResponse=Math.max(0,responseSheets-PRIOR_AUTHORIZATION_DENIAL_PRICING.includedResponsePages);
  const mailing=method==="standard"?PRIOR_AUTHORIZATION_DENIAL_PRICING.standardMail:method==="certified"?PRIOR_AUTHORIZATION_DENIAL_PRICING.certifiedMail:PRIOR_AUTHORIZATION_DENIAL_PRICING.registeredMail;
  const large=totalSheets>=PRIOR_AUTHORIZATION_DENIAL_PRICING.largePacketThresholdSheets?PRIOR_AUTHORIZATION_DENIAL_PRICING.largePacketFee:0;
  return Number((PRIOR_AUTHORIZATION_DENIAL_PRICING.preparationFee+extraResponse*PRIOR_AUTHORIZATION_DENIAL_PRICING.responsePagePrice+supportingSheets*PRIOR_AUTHORIZATION_DENIAL_PRICING.supportingPagePrice+mailing+large).toFixed(2));
}

export const Route=createFileRoute("/api/workflows/prior-authorization-denial/checkout")({server:{handlers:{POST:async({request})=>{try{const user=await requireAuthenticatedUser(request);const input=await request.json() as {appealId?:string};if(!input.appealId)return Response.json({error:"Appeal id is required."},{status:400});const s=await getSupabaseServer();const {data:a,error}=await s.from("appeals").select("*").eq("id",input.appealId).single();if(error||!a)return Response.json({error:"Appeal case not found."},{status:404});if(a.user_id!==user.id)return Response.json({error:"You do not own this appeal case."},{status:403});if(a.workflow_id!=="prior-authorization-denial")return Response.json({error:"Appeal workflow mismatch."},{status:409});if(a.status!=="ready"||!a.review||!a.packet)return Response.json({error:"Appeal is not approved and ready for payment."},{status:409});const method=a.packet.mailingMethod as "standard"|"certified"|"registered";const total=calculateTotal(a.packet,method);const {default:Stripe}=await import("stripe");const key=process.env.STRIPE_SECRET_KEY;if(!key)return Response.json({error:"Stripe is not configured."},{status:503});const stripe=new Stripe(key,{apiVersion:"2024-06-20" as Stripe.LatestApiVersion});const appUrl=process.env.APP_URL||"https://appeal-mail.pages.dev";const session=await stripe.checkout.sessions.create({mode:"payment",payment_method_types:["card"],line_items:[{price_data:{currency:"usd",product_data:{name:"Prior Authorization Appeal Packet",description:`Preparation + physical packet + ${method} mailing`},unit_amount:Math.round(total*100)},quantity:1}],metadata:{appeal_id:a.id,workflow_id:"prior-authorization-denial",mailing_method:method,packet_sheets:String(a.packet.pageCount||1),owner_user_id:user.id},success_url:`${appUrl}/workflows/prior-authorization-denial?checkout=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${appUrl}/workflows/prior-authorization-denial?checkout=cancelled`});return Response.json({ok:true,total,sessionId:session.id,url:session.url,breakdown:{preparation:PRIOR_AUTHORIZATION_DENIAL_PRICING.preparationFee,sheets:a.packet.pageCount||1,mailing:method}});}catch(error){const message=error instanceof Error?error.message:"Unable to create checkout session.";return Response.json({error:message},{status:/authentication|required|token/i.test(message)?401:502});}}}}});