import { Link } from "@tanstack/react-router";
import { getWorkflowById } from "@/domain/workflow-catalog";
import { NOTICE_WORKFLOWS } from "@/components/notice-workflow-directory";
import type { NoticeWorkflow } from "@/components/notice-workflow-directory";

export function AuthorityWorkflowPage({ workflow }: { workflow: NoticeWorkflow }) {
  const definition = getWorkflowById(workflow.slug);
  const faqs = definition?.seo?.faq ?? [
    { question: `What is ${workflow.title.toLowerCase()}?`, answer: workflow.description },
    { question: "What should I gather before starting?", answer: "Start with the complete source document, the identifiers and dates shown on it, relevant supporting records, and the submission instructions provided by the issuing agency or court." },
    { question: "What should I review before sending?", answer: "Review the notice, factual statements, dates, reference numbers, attachments, recipient information, and the exact response draft. Notice Respond is not a law firm and does not provide legal advice." },
    { question: "How does mailing work?", answer: "After the required workflow and approval steps are complete, the response can move into the MailMyPDF fulfillment flow with available tracking and mailing proof." },
  ];
  const related = NOTICE_WORKFLOWS.filter((item) => item.slug !== workflow.slug && item.category === workflow.category).slice(0, 4);

  return (
    <main className="min-h-screen">
      <section className="border-b border-rule/60 bg-paper-deep/20"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-16">
        <nav aria-label="Breadcrumb" className="text-xs text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Notice Respond</Link></li><li aria-hidden="true">/</li><li><Link to="/workflows">Workflows</Link></li><li aria-hidden="true">/</li><li className="text-ink" aria-current="page">{workflow.title}</li></ol></nav>
        <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_.72fr] lg:items-start"><div className="max-w-3xl">
          <div className="postmark w-fit">{workflow.category}</div><h1 className="mt-5 font-serif text-4xl leading-[1.08] sm:text-5xl md:text-6xl">{workflow.title}</h1>
          <p className="mt-5 text-base leading-7 text-ink-soft sm:text-lg">{workflow.description}</p><p className="mt-4 text-sm leading-6 text-muted-foreground">Search intent: <span className="font-medium text-ink">{workflow.searchIntent}</span></p>
          <div className="mt-7 flex flex-wrap gap-3"><Link to={workflow.canonicalPath ?? workflow.route} className="inline-flex rounded-full bg-ink px-6 py-3.5 text-sm font-medium text-paper shadow-card transition-transform hover:-translate-y-0.5">Start this workflow →</Link><Link to="/workflows" className="inline-flex rounded-full border border-rule bg-card px-6 py-3.5 text-sm font-medium hover:border-ink/30">Browse all workflows</Link></div>
        </div><aside className="border border-rule bg-card p-6 sm:p-7"><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Best for</div><p className="mt-3 text-sm leading-6">{workflow.bestFor}</p><div className="mt-6 border-t border-rule/60 pt-6"><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Workflow path</div><p className="mt-3 text-sm leading-6 text-muted-foreground">Identify → Understand → Prepare → Review → Send → Document</p></div></aside></div>
      </div></section>

      <section><div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 sm:px-6 sm:py-20 lg:grid-cols-[1.1fr_.9fr]"><div>
        <Eyebrow text="Overview"/><h2 className="mt-3 font-serif text-3xl">Start with the source document and the actual issue.</h2><p className="mt-5 text-base leading-7 text-muted-foreground">This page is for people who have received the kind of notice or correspondence described above and need to understand it, organize the relevant information, and prepare the next written step. It does not replace the issuing agency's instructions, court rules, or professional advice.</p>
        <div className="mt-8 space-y-5"><Point title="Use the source document" text="Treat the actual notice, letter, determination, summons, or other source as the starting point for dates, identifiers, instructions, and requested action."/><Point title="Separate facts from suggestions" text="Keep document-extracted facts and user-provided facts distinguishable from AI suggestions and unresolved assumptions."/><Point title="Answer the real request" text="A strong response addresses what the notice is actually asking for rather than filling the page with generic language."/></div>
      </div><aside className="border border-rule bg-paper p-6 sm:p-7"><Eyebrow text="When not to rely on this page alone"/><ul className="mt-4 space-y-3 text-sm leading-6 text-muted-foreground"><li>The notice gives requirements that differ from general guidance.</li><li>A deadline or procedural rule is unclear or jurisdiction-specific.</li><li>You need legal, tax, immigration, financial, or other professional advice.</li><li>The document is outside the workflow's supported scope.</li></ul></aside></div></section>

      <section className="border-y border-rule/60 bg-paper-deep/20"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><Eyebrow text="Preparation"/><h2 className="mt-3 font-serif text-3xl">What to gather before you start</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">The exact requirements vary by notice. Begin with material that keeps the response grounded in the document and your records.</p>
        <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{workflow.documents.map((document)=><div key={document} className="border border-rule bg-card p-5"><h3 className="font-serif text-xl">{document}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Use the version that actually applies to this matter.</p></div>)}</div>
        <div className="mt-8 grid gap-4 md:grid-cols-3"><Preparation title="Identifiers" text="Notice, case, account, receipt, property, or other reference numbers shown on the source."/><Preparation title="Dates" text="Dates explicitly shown on the source document or verified official instructions."/><Preparation title="Supporting records" text="Documents that confirm, explain, contradict, or otherwise support the facts you plan to communicate."/></div>
      </div></section>

      <section><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><div className="grid gap-10 lg:grid-cols-2"><div><Eyebrow text="Process"/><h2 className="mt-3 font-serif text-3xl">How the workflow works</h2><div className="mt-7 divide-y divide-rule border-y border-rule">{workflow.steps.map((step,index)=><div key={step} className="flex gap-4 py-4"><span className="font-mono text-xs text-stamp">{String(index+1).padStart(2,"0")}</span><span className="text-sm leading-6">{step}</span></div>)}</div></div><div><Eyebrow text="Quality checks"/><h2 className="mt-3 font-serif text-3xl">Keep the response tied to the record.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><Check title="Notice details" text="Type, agency, identifiers, action, and instructions."/><Check title="Dates" text="Explicit dates and their sources."/><Check title="Requirements" text="What must be answered, attached, signed, or submitted."/><Check title="Evidence" text="What records exist, what is missing, and what each record supports."/><Check title="Draft quality" text="Factual grounding, addressed issues, recipient, and consistency."/><Check title="Submission readiness" text="Approval, required information, mailing details, and proof."/></div></div></div></div></section>

      <section className="border-y border-rule/60 bg-ink text-paper"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><Eyebrow text="Review before sending" dark/><h2 className="mt-3 max-w-3xl font-serif text-3xl sm:text-4xl">The system assists. You review the important decisions.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-paper/70 sm:text-base">Review the source document, factual statements, dates, reference numbers, evidence, recipient information, attachments, and exact response draft before approval. AI suggestions should remain distinguishable from source facts.</p><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><DarkCheck text="Facts trace to source material."/><DarkCheck text="Uncertain information stays visible."/><DarkCheck text="The exact draft is the approval object."/><DarkCheck text="Mailing and proof remain separate from drafting."/></div></div></section>

      <section><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><Eyebrow text="Common failure modes"/><h2 className="mt-3 font-serif text-3xl">What can make a response weaker</h2><div className="mt-8 grid gap-4 md:grid-cols-2"><Failure title="Missing the actual request" text="A detailed response can still fail to answer the specific action or information requested."/><Failure title="Using unsupported facts" text="Do not add dates, amounts, events, identifiers, or conclusions that are not supported by the record or user-provided facts."/><Failure title="Overlooking submission instructions" text="The source may specify the recipient, format, attachments, method, or other requirements."/><Failure title="Treating a draft as final" text="The mailed response should match the exact version the user reviewed and approved."/></div></div></section>

      <section className="border-y border-rule/60 bg-paper-deep/20"><div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-20"><Eyebrow text="FAQ"/><h2 className="mt-3 font-serif text-3xl">Frequently asked questions about {workflow.title.toLowerCase()}</h2><div className="mt-8 divide-y divide-rule border-y border-rule">{faqs.map((faq)=><details key={faq.question} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-serif text-xl">{faq.question}<span className="float-right text-muted-foreground" aria-hidden="true">+</span></summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{faq.answer}</p></details>)}</div></div></section>

      <section><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><div className="grid gap-10 lg:grid-cols-[1fr_.9fr]"><div><Eyebrow text="Related workflows"/><h2 className="mt-3 font-serif text-3xl">Other notices you may encounter</h2><div className="mt-7 divide-y divide-rule border-y border-rule">{related.map((item)=><Link key={item.slug} to={item.route} className="group flex items-center justify-between py-4"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">{item.category}</div><div className="mt-1 font-serif text-xl">{item.title}</div></div><span aria-hidden="true" className="transition-transform group-hover:translate-x-1">→</span></Link>)}</div><Link to="/workflows" className="mt-6 inline-flex text-sm font-semibold underline decoration-rule underline-offset-4 hover:decoration-ink">Return to the full workflow library →</Link></div><aside className="border border-rule bg-card p-6 sm:p-7"><Eyebrow text="Mailing, tracking, and proof"/><p className="mt-4 text-sm leading-6 text-muted-foreground">After the workflow requirements are satisfied and the user approves the exact draft, the response can move into the MailMyPDF fulfillment flow. Mailing records and available tracking/proof remain separate from the content analysis.</p></aside></div></div></section>

      <section className="border-t border-rule/60"><div className="mx-auto max-w-4xl px-4 py-12 text-center sm:px-6 sm:py-16"><Eyebrow text="Ready to begin"/><h2 className="mt-3 font-serif text-3xl sm:text-4xl">Start with the document you received.</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Notice Respond helps organize the notice, evidence, response draft, review, and mailing record. It does not replace professional legal, tax, immigration, financial, or other specialized advice.</p><Link to={workflow.canonicalPath ?? workflow.route} className="mt-6 inline-flex rounded-full bg-ink px-6 py-3 text-sm font-medium text-paper shadow-card transition-transform hover:-translate-y-0.5">Start this workflow →</Link></div></section>
    </main>
  );
}

function Eyebrow({ text, dark=false }: { text:string; dark?:boolean }) { return <div className={`font-mono text-[10px] uppercase tracking-[0.18em] ${dark ? "text-paper/50" : "text-muted-foreground"}`}>{text}</div>; }
function Point({ title, text }: { title:string; text:string }) { return <div className="border-l-2 border-stamp pl-4"><h3 className="font-serif text-xl">{title}</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Preparation({ title, text }: { title:string; text:string }) { return <div className="border border-rule bg-card p-5"><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Check({ title, text }: { title:string; text:string }) { return <div className="border border-rule p-5"><h3 className="font-serif text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function DarkCheck({ text }: { text:string }) { return <div className="border border-paper/10 bg-paper/5 p-4 text-sm leading-6 text-paper/80">{text}</div>; }
function Failure({ title, text }: { title:string; text:string }) { return <div className="border border-rule bg-card p-5"><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }

export function AuthorityWorkflowHead({ workflow }: { workflow: NoticeWorkflow }) { const definition=getWorkflowById(workflow.slug); return { meta:[{title:definition?.seo?.title ?? `${workflow.title} | Notice Respond`},{name:"description",content:definition?.seo?.description ?? workflow.description},{property:"og:title",content:definition?.seo?.openGraph?.title ?? workflow.title},{property:"og:description",content:definition?.seo?.openGraph?.description ?? workflow.description},{property:"og:type",content:"website"}] }; }

export function AuthorityWorkflowStructuredData({ workflow }: { workflow: NoticeWorkflow }) { const definition=getWorkflowById(workflow.slug); const faqs=definition?.seo?.faq ?? []; const origin="https://notice-respond.pages.dev"; const url=`${origin}${workflow.route}`; const graph:Record<string,unknown>[]=[{ "@type":"WebPage", "@id":url, name:workflow.title, description:definition?.seo?.description ?? workflow.description, url, about:workflow.searchIntent, isPartOf:{"@type":"WebSite",name:"Notice Respond",url:origin}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Notice Respond",item:origin},{"@type":"ListItem",position:2,name:"Workflows",item:`${origin}/workflows`},{"@type":"ListItem",position:3,name:workflow.title,item:url}]}]; if(faqs.length) graph.push({"@type":"FAQPage",mainEntity:faqs.map((faq)=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))}); return {type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@graph":graph})}; }
