import React from 'react'
import { ArrowUpRight, CalendarClock, FileText, Sparkles, Wand2 } from 'lucide-react'
import './command-center.css'

const suggestions = ['Prepare reminders for customers with invoices over 30 days overdue','Show me everything waiting for approval','Draft a certified response to an important customer notice']
export function CommandCenter({ onCreateMailing }: { onCreateMailing: () => void }) {
  const [prompt,setPrompt]=React.useState(''); const [submitted,setSubmitted]=React.useState(false)
  return <div className="command-center"><div className="command-hero"><div className="command-kicker"><Sparkles size={13}/> Business correspondence intelligence</div><h2 className="serif">Tell MailMyPDF what<br/>needs to happen.</h2><p>Turn a business goal into a reviewable plan. MailMyPDF can analyze documents, prepare correspondence, schedule work, and keep permanent proof.</p><div className="command-input-wrap"><Wand2 size={17}/><input value={prompt} onChange={e=>{setPrompt(e.target.value);setSubmitted(false)}} onKeyDown={e=>{if(e.key==='Enter'&&prompt.trim())setSubmitted(true)}} placeholder="e.g. Send overdue customers a reminder next Tuesday"/><button className="primary" disabled={!prompt.trim()} onClick={()=>setSubmitted(true)}>Plan</button></div><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>setPrompt(s)}>{s}<ArrowUpRight size={12}/></button>)}</div>{submitted&&<div className="plan-card"><div className="plan-head"><div><div className="card-kicker">Proposed plan</div><div className="card-title">{prompt}</div></div><span className="badge">Review required</span></div><div className="plan-steps"><div><span>01</span>Find qualifying business records</div><div><span>02</span>Prepare correspondence from approved templates</div><div><span>03</span>Validate recipients, documents, and policy</div><div><span>04</span>Request approval before sending</div><div><span>05</span>Schedule, track, and archive proof</div></div><div className="action-row"><button className="primary" onClick={onCreateMailing}>Start with a mailing</button><button className="secondary">Review plan</button></div></div>}</div><div className="command-grid"><div className="mini-card"><CalendarClock size={17}/><strong>Upcoming</strong><span>8 scheduled mailings</span></div><div className="mini-card"><FileText size={17}/><strong>Needs review</strong><span>8 approval requests</span></div><div className="mini-card"><Sparkles size={17}/><strong>AI skills</strong><span>Draft · Analyze · Recommend</span></div></div></div>
}
