export type InsuranceWorkflowRisk = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type InsuranceWorkflowId =
  | 'new-claim'
  | 'denied-claim'
  | 'underpaid-claim'
  | 'claim-dispute'
  | 'coverage-denial'
  | 'water-damage-claim'
  | 'roof-damage-claim'
  | 'fire-smoke-claim'
  | 'property-damage-claim'
  | 'auto-claim'
  | 'auto-claim-denial'
  | 'theft-vandalism-claim'
  | 'commercial-property-claim'
  | 'life-insurance-denial'
  | 'health-medical-denial'
  | 'disability-claim-denial'

export interface InsuranceWorkflowDefinition {
  id: InsuranceWorkflowId
  name: string
  description: string
  risk: InsuranceWorkflowRisk
  requiresReview: boolean
  primaryKeyword: string
  monthlySearches: number
  cpc: number
  competition: string
  supportingKeywords: readonly string[]
  intake: readonly string[]
  requiredEvidence: readonly string[]
  outputs: readonly string[]
  guardrails: readonly string[]
}

const SHARED_GUARDRAILS = [
  'Never invent coverage, policy terms, claim entitlement, causation, amounts, or legal conclusions.',
  'Separate policy text, insurer statements, user-provided facts, extracted facts, and generated suggestions.',
  'Preserve source references for material assertions.',
  'Require human review before any consequential mailing.',
] as const

export const INSURANCE_WORKFLOWS: readonly InsuranceWorkflowDefinition[] = [
  { id:'new-claim', name:'Prepare an Insurance Claim', description:'Organize a new insurance claim and prepare a factual submission package.', risk:'MEDIUM', requiresReview:true, primaryKeyword:'insurance claims', monthlySearches:12100, cpc:49.829989, competition:'LOW', supportingKeywords:['file a claim','state farm file a claim','insurance claim'], intake:['insurer','policy number','claim number','loss date','loss type','loss location','parties','estimated loss'], requiredEvidence:['policy/coverage documents','photos or records','estimates/invoices','prior correspondence'], outputs:['claim fact sheet','source-linked timeline','document checklist','claim submission draft'], guardrails:SHARED_GUARDRAILS },
  { id:'denied-claim', name:'Respond to a Denied Insurance Claim', description:'Analyze a denial and build a source-supported response or appeal.', risk:'HIGH', requiresReview:true, primaryKeyword:'insurance claim denied', monthlySearches:1300, cpc:47.028575, competition:'LOW', supportingKeywords:['denied claim','claim was denied','appealing insurance denial','insurance company denied claim'], intake:['denial letter','claim number','denial date','stated reason','policy provision cited','appeal instructions','deadline'], requiredEvidence:['denial letter','policy excerpts','claim records','supporting photos/reports','prior correspondence'], outputs:['denial X-Ray','issue list','evidence gaps','response/appeal draft','mail-ready packet'], guardrails:SHARED_GUARDRAILS },
  { id:'underpaid-claim', name:'Dispute an Underpaid Insurance Claim', description:'Compare an insurer payment or estimate against documented loss evidence and prepare a factual dispute.', risk:'HIGH', requiresReview:true, primaryKeyword:'underpaid insurance claim', monthlySearches:30, cpc:0, competition:'LOW', supportingKeywords:['underpaid claim','insurance company underpaid claim','insurance underpayment'], intake:['claim number','insurer estimate','payment amount','loss estimate','line-item differences','policy references'], requiredEvidence:['insurer estimate','contractor/appraiser estimate','receipts','photos','repair invoices','policy excerpts'], outputs:['valuation comparison','unexplained differences','missing support list','supplement/reconsideration letter'], guardrails:SHARED_GUARDRAILS },
  { id:'claim-dispute', name:'Dispute an Insurance Claim', description:'Build a structured dispute when the insurer position conflicts with documented facts or evidence.', risk:'HIGH', requiresReview:true, primaryKeyword:'dispute insurance claim', monthlySearches:210, cpc:35.86275, competition:'LOW', supportingKeywords:['dispute insurance','disputing insurance claims','insurance claim response'], intake:['claim position','disputed facts','claim communications','requested outcome','deadline'], requiredEvidence:['claim correspondence','policy excerpts','photos/reports','estimates','third-party records'], outputs:['dispute map','contradiction list','evidence matrix','response letter'], guardrails:SHARED_GUARDRAILS },
  { id:'coverage-denial', name:'Respond to a Coverage Denial', description:'Organize a response to a stated denial of insurance coverage without making unsupported coverage conclusions.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'denial of coverage', monthlySearches:170, cpc:0, competition:'LOW', supportingKeywords:['coverage denial','denied coverage','insurance company denied claim'], intake:['policy','coverage denial','exclusion/condition cited','claim facts','deadline'], requiredEvidence:['policy text','denial letter','loss evidence','prior correspondence'], outputs:['coverage issue matrix','policy-source map','fact/evidence gaps','review-ready response'], guardrails:SHARED_GUARDRAILS },
  { id:'water-damage-claim', name:'Prepare a Water Damage Insurance Claim', description:'Build a documented water-loss claim from the loss event through response and proof.', risk:'HIGH', requiresReview:true, primaryKeyword:'water damage insurance claim', monthlySearches:1000, cpc:7.29838, competition:'LOW', supportingKeywords:['water damage claim','water leak insurance claim','burst pipe insurance claim','water damage claim process','homeowners insurance claim for water damage'], intake:['loss date','source of water','affected areas','mitigation actions','claim number','insurer','estimated damage'], requiredEvidence:['photos/videos','plumber report','mitigation invoices','repair estimates','inventory','policy/correspondence'], outputs:['water-loss timeline','damage inventory','evidence checklist','claim or supplemental letter'], guardrails:SHARED_GUARDRAILS },
  { id:'roof-damage-claim', name:'Prepare a Roof Damage Insurance Claim', description:'Organize storm, hail, wind, or roof-leak evidence and prepare a documented claim or appeal.', risk:'HIGH', requiresReview:true, primaryKeyword:'roof insurance claim', monthlySearches:1900, cpc:28.637222, competition:'LOW', supportingKeywords:['roof damage insurance claim','hail damage roof insurance claim','roof leak insurance claim','roof insurance claim denied','storm damage roof insurance claim'], intake:['loss date','storm event','roof age','damage description','inspection findings','estimate','insurer position'], requiredEvidence:['roof inspection','photos','weather/event records','contractor estimate','insurer estimate','policy/claim letters'], outputs:['roof damage timeline','estimate comparison','evidence gaps','claim/supplemental/appeal letter'], guardrails:SHARED_GUARDRAILS },
  { id:'fire-smoke-claim', name:'Prepare a Fire or Smoke Damage Claim', description:'Document structural, contents, smoke, soot, and displacement losses for a review-ready claim.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'fire damage insurance claim', monthlySearches:210, cpc:15.541418, competition:'LOW', supportingKeywords:['smoke damage insurance claims','fire damage claims','total loss fire claim','soot damage insurance claim'], intake:['loss date','fire cause as reported','property status','contents loss','temporary housing','claim number'], requiredEvidence:['fire report','photos','contents inventory','estimates','receipts','temporary housing records','insurer correspondence'], outputs:['fire-loss packet','contents inventory','timeline','claim/supplemental letter'], guardrails:SHARED_GUARDRAILS },
  { id:'property-damage-claim', name:'Prepare a Property Damage Claim', description:'Document a property loss and organize the claim evidence, valuation, and response.', risk:'HIGH', requiresReview:true, primaryKeyword:'property damage insurance claim', monthlySearches:260, cpc:0, competition:'LOW', supportingKeywords:['property damage insurance','damage claim','home damage','property damage adjuster'], intake:['property','loss type','loss date','claim number','damage scope','estimate'], requiredEvidence:['photos','inspection reports','estimates','invoices','policy/claim correspondence'], outputs:['damage inventory','timeline','valuation comparison','response/supplement letter'], guardrails:SHARED_GUARDRAILS },
  { id:'auto-claim', name:'Prepare an Auto Insurance Claim', description:'Organize an auto accident, collision, comprehensive, or property-damage claim.', risk:'HIGH', requiresReview:true, primaryKeyword:'car insurance claim', monthlySearches:5400, cpc:23.672786, competition:'LOW', supportingKeywords:['auto insurance claim','car accident claim','accident claim','auto adjuster'], intake:['accident date','vehicles','drivers','insurer','claim number','damage','liability position'], requiredEvidence:['photos','police report','repair estimate','vehicle records','witness information','insurer correspondence'], outputs:['accident timeline','damage/evidence matrix','claim response','supplement letter'], guardrails:SHARED_GUARDRAILS },
  { id:'auto-claim-denial', name:'Respond to a Denied Auto Insurance Claim', description:'Analyze an auto claim denial and prepare a factual response or appeal.', risk:'HIGH', requiresReview:true, primaryKeyword:'car insurance claim denied', monthlySearches:90, cpc:255.00054, competition:'LOW', supportingKeywords:['auto insurance claim denied','denied car insurance claim','car insurance denied claim what to do','car insurance refusing to pay claim'], intake:['denial letter','claim facts','liability/coverage reason','deadline','requested outcome'], requiredEvidence:['denial letter','policy','accident report','photos','repair estimates','prior communications'], outputs:['denial analysis','fact/evidence matrix','appeal response'], guardrails:SHARED_GUARDRAILS },
  { id:'theft-vandalism-claim', name:'Prepare a Theft or Vandalism Claim', description:'Document theft or vandalism losses and build a factual insurance submission or dispute.', risk:'HIGH', requiresReview:true, primaryKeyword:'auto theft claim denied', monthlySearches:10, cpc:10.381855, competition:'MEDIUM', supportingKeywords:['stolen car insurance claim denied','car vandalism claim denied','stolen car claim denied'], intake:['incident date','property stolen/damaged','police report','claim number','insurer position'], requiredEvidence:['police report','photos','ownership records','receipts','keys/access records','insurer correspondence'], outputs:['loss inventory','timeline','evidence checklist','claim/response letter'], guardrails:SHARED_GUARDRAILS },
  { id:'commercial-property-claim', name:'Prepare a Commercial Property Claim', description:'Organize business property loss, supporting records, and an insurer response or supplemental claim.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'business property damage insurance', monthlySearches:1000, cpc:1.772208, competition:'HIGH', supportingKeywords:['commercial property damage claim','commercial property damage','commercial insurance claims'], intake:['business','policy','claim number','loss date','property affected','business interruption context'], requiredEvidence:['policy','photos','repair estimates','invoices','asset records','business records','insurer correspondence'], outputs:['commercial loss inventory','timeline','valuation/evidence matrix','review-ready claim response'], guardrails:SHARED_GUARDRAILS },
  { id:'life-insurance-denial', name:'Respond to a Denied Life Insurance Claim', description:'Organize a life-insurance denial and prepare a source-supported response for human review.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'life insurance claim denied', monthlySearches:210, cpc:18.278813, competition:'LOW', supportingKeywords:['life insurance denied','life insurance policy denial','life insurance payout denied','life insurance rejection reasons'], intake:['policy','claimant/beneficiary role','denial letter','policy provision cited','deadline'], requiredEvidence:['policy','death/claim records as applicable','denial letter','insurer communications','supporting records'], outputs:['denial analysis','source map','evidence checklist','review-ready response'], guardrails:SHARED_GUARDRAILS },
  { id:'health-medical-denial', name:'Respond to a Health or Medical Insurance Denial', description:'Organize a medical claim or coverage denial and prepare a documented appeal package.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'medical insurance claim denial', monthlySearches:320, cpc:0.1527, competition:'LOW', supportingKeywords:['health insurance denial','medical insurance denial','appealing medical insurance denials','health insurance appeal process'], intake:['member/claim number','service/date','denial reason','code/reason cited','appeal deadline'], requiredEvidence:['denial/EOB','policy or plan materials','provider records','bills','supporting documentation'], outputs:['denial X-Ray','evidence matrix','appeal checklist','review-ready appeal letter'], guardrails:SHARED_GUARDRAILS },
  { id:'disability-claim-denial', name:'Respond to a Disability Insurance Denial', description:'Organize a short- or long-term disability denial and prepare a documented appeal for review.', risk:'CRITICAL', requiresReview:true, primaryKeyword:'disability insurance denied', monthlySearches:110, cpc:22.135665, competition:'MEDIUM', supportingKeywords:['short term disability denied','long term disability denial','reasons short term disability can be denied','denied long term disability coverage'], intake:['claim type','policy/certificate','denial letter','claimed limitation as stated by user','deadline','appeal instructions'], requiredEvidence:['denial letter','policy/certificate','user-provided records','insurer correspondence'], outputs:['denial analysis','document checklist','appeal draft'], guardrails:SHARED_GUARDRAILS },
]

export const insuranceWorkflowMap = Object.fromEntries(INSURANCE_WORKFLOWS.map(w => [w.id, w])) as Record<InsuranceWorkflowId, InsuranceWorkflowDefinition>
export const insuranceWorkflowCount = INSURANCE_WORKFLOWS.length
