/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RespondToAGovernmentNoticeRouteImport } from './routes/respond-to-a-government-notice'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsAgencyActionRouteImport } from './routes/workflows/agency-action'
import { Route as WorkflowsAnalyzeRouteImport } from './routes/workflows/analyze'
import { Route as WorkflowsCourtSummonsRouteImport } from './routes/workflows/court-summons'
import { Route as WorkflowsCp14ResponseRouteImport } from './routes/workflows/cp14-response'
import { Route as WorkflowsCp2000ResponseRouteImport } from './routes/workflows/cp2000-response'
import { Route as WorkflowsCp504ResponseRouteImport } from './routes/workflows/cp504-response'
import { Route as WorkflowsEquifaxDisputeRouteImport } from './routes/workflows/equifax-dispute'
import { Route as WorkflowsExperianDisputeRouteImport } from './routes/workflows/experian-dispute'
import { Route as WorkflowsFileAppealRouteImport } from './routes/workflows/file-appeal'
import { Route as WorkflowsIrsNoticeRouteImport } from './routes/workflows/irs-notice'
import { Route as WorkflowsRespondToABenefitsNoticeRouteImport } from './routes/workflows/respond-to-a-benefits-notice'
import { Route as WorkflowsRespondToACourtSummonsRouteImport } from './routes/workflows/respond-to-a-court-summons'
import { Route as WorkflowsRespondToADmvNoticeRouteImport } from './routes/workflows/respond-to-a-dmv-notice'
import { Route as WorkflowsRespondToAPermitCorrectionNoticeRouteImport } from './routes/workflows/respond-to-a-permit-correction-notice'
import { Route as WorkflowsRespondToATaxNoticeRouteImport } from './routes/workflows/respond-to-a-tax-notice'
import { Route as WorkflowsRespondToAUscisNoticeRouteImport } from './routes/workflows/respond-to-a-uscis-notice'
import { Route as WorkflowsRespondToAnAgencyActionRouteImport } from './routes/workflows/respond-to-an-agency-action'
import { Route as WorkflowsRespondToAnIrsNoticeRouteImport } from './routes/workflows/respond-to-an-irs-notice'
import { Route as WorkflowsRespondToAnSsaNoticeRouteImport } from './routes/workflows/respond-to-an-ssa-notice'
import { Route as WorkflowsRespondToCodeEnforcementNoticeRouteImport } from './routes/workflows/respond-to-code-enforcement-notice'
import { Route as WorkflowsRespondToCp14NoticeRouteImport } from './routes/workflows/respond-to-cp14-notice'
import { Route as WorkflowsRespondToCp2000NoticeRouteImport } from './routes/workflows/respond-to-cp2000-notice'
import { Route as WorkflowsTransunionDisputeRouteImport } from './routes/workflows/transunion-dispute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondToAGovernmentNoticeRoute =
  RespondToAGovernmentNoticeRouteImport.update({
    id: '/respond-to-a-government-notice',
    path: '/respond-to-a-government-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsAgencyActionRoute = WorkflowsAgencyActionRouteImport.update({
  id: '/workflows/agency-action',
  path: '/workflows/agency-action',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsAnalyzeRoute = WorkflowsAnalyzeRouteImport.update({
  id: '/workflows/analyze',
  path: '/workflows/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCourtSummonsRoute = WorkflowsCourtSummonsRouteImport.update({
  id: '/workflows/court-summons',
  path: '/workflows/court-summons',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp14ResponseRoute = WorkflowsCp14ResponseRouteImport.update({
  id: '/workflows/cp14-response',
  path: '/workflows/cp14-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp2000ResponseRoute = WorkflowsCp2000ResponseRouteImport.update({
  id: '/workflows/cp2000-response',
  path: '/workflows/cp2000-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp504ResponseRoute = WorkflowsCp504ResponseRouteImport.update({
  id: '/workflows/cp504-response',
  path: '/workflows/cp504-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsEquifaxDisputeRoute = WorkflowsEquifaxDisputeRouteImport.update({
  id: '/workflows/equifax-dispute',
  path: '/workflows/equifax-dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExperianDisputeRoute =
  WorkflowsExperianDisputeRouteImport.update({
    id: '/workflows/experian-dispute',
    path: '/workflows/experian-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsFileAppealRoute = WorkflowsFileAppealRouteImport.update({
  id: '/workflows/file-appeal',
  path: '/workflows/file-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIrsNoticeRoute = WorkflowsIrsNoticeRouteImport.update({
  id: '/workflows/irs-notice',
  path: '/workflows/irs-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRespondToABenefitsNoticeRoute =
  WorkflowsRespondToABenefitsNoticeRouteImport.update({
    id: '/workflows/respond-to-a-benefits-notice',
    path: '/workflows/respond-to-a-benefits-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToACourtSummonsRoute =
  WorkflowsRespondToACourtSummonsRouteImport.update({
    id: '/workflows/respond-to-a-court-summons',
    path: '/workflows/respond-to-a-court-summons',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToADmvNoticeRoute =
  WorkflowsRespondToADmvNoticeRouteImport.update({
    id: '/workflows/respond-to-a-dmv-notice',
    path: '/workflows/respond-to-a-dmv-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAPermitCorrectionNoticeRoute =
  WorkflowsRespondToAPermitCorrectionNoticeRouteImport.update({
    id: '/workflows/respond-to-a-permit-correction-notice',
    path: '/workflows/respond-to-a-permit-correction-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToATaxNoticeRoute =
  WorkflowsRespondToATaxNoticeRouteImport.update({
    id: '/workflows/respond-to-a-tax-notice',
    path: '/workflows/respond-to-a-tax-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAUscisNoticeRoute =
  WorkflowsRespondToAUscisNoticeRouteImport.update({
    id: '/workflows/respond-to-a-uscis-notice',
    path: '/workflows/respond-to-a-uscis-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnAgencyActionRoute =
  WorkflowsRespondToAnAgencyActionRouteImport.update({
    id: '/workflows/respond-to-an-agency-action',
    path: '/workflows/respond-to-an-agency-action',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnIrsNoticeRoute =
  WorkflowsRespondToAnIrsNoticeRouteImport.update({
    id: '/workflows/respond-to-an-irs-notice',
    path: '/workflows/respond-to-an-irs-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnSsaNoticeRoute =
  WorkflowsRespondToAnSsaNoticeRouteImport.update({
    id: '/workflows/respond-to-an-ssa-notice',
    path: '/workflows/respond-to-an-ssa-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCodeEnforcementNoticeRoute =
  WorkflowsRespondToCodeEnforcementNoticeRouteImport.update({
    id: '/workflows/respond-to-code-enforcement-notice',
    path: '/workflows/respond-to-code-enforcement-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCp14NoticeRoute =
  WorkflowsRespondToCp14NoticeRouteImport.update({
    id: '/workflows/respond-to-cp14-notice',
    path: '/workflows/respond-to-cp14-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCp2000NoticeRoute =
  WorkflowsRespondToCp2000NoticeRouteImport.update({
    id: '/workflows/respond-to-cp2000-notice',
    path: '/workflows/respond-to-cp2000-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsTransunionDisputeRoute =
  WorkflowsTransunionDisputeRouteImport.update({
    id: '/workflows/transunion-dispute',
    path: '/workflows/transunion-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/respond-to-a-government-notice'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/transunion-dispute'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/respond-to-a-government-notice'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/transunion-dispute'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/respond-to-a-government-notice'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/transunion-dispute'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RespondToAGovernmentNoticeRoute: typeof RespondToAGovernmentNoticeRoute
  TermsRoute: typeof TermsRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  WorkflowsAgencyActionRoute: typeof WorkflowsAgencyActionRoute
  WorkflowsAnalyzeRoute: typeof WorkflowsAnalyzeRoute
  WorkflowsCourtSummonsRoute: typeof WorkflowsCourtSummonsRoute
  WorkflowsCp14ResponseRoute: typeof WorkflowsCp14ResponseRoute
  WorkflowsCp2000ResponseRoute: typeof WorkflowsCp2000ResponseRoute
  WorkflowsCp504ResponseRoute: typeof WorkflowsCp504ResponseRoute
  WorkflowsEquifaxDisputeRoute: typeof WorkflowsEquifaxDisputeRoute
  WorkflowsExperianDisputeRoute: typeof WorkflowsExperianDisputeRoute
  WorkflowsFileAppealRoute: typeof WorkflowsFileAppealRoute
  WorkflowsIrsNoticeRoute: typeof WorkflowsIrsNoticeRoute
  WorkflowsRespondToABenefitsNoticeRoute: typeof WorkflowsRespondToABenefitsNoticeRoute
  WorkflowsRespondToACourtSummonsRoute: typeof WorkflowsRespondToACourtSummonsRoute
  WorkflowsRespondToADmvNoticeRoute: typeof WorkflowsRespondToADmvNoticeRoute
  WorkflowsRespondToAPermitCorrectionNoticeRoute: typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  WorkflowsRespondToATaxNoticeRoute: typeof WorkflowsRespondToATaxNoticeRoute
  WorkflowsRespondToAUscisNoticeRoute: typeof WorkflowsRespondToAUscisNoticeRoute
  WorkflowsRespondToAnAgencyActionRoute: typeof WorkflowsRespondToAnAgencyActionRoute
  WorkflowsRespondToAnIrsNoticeRoute: typeof WorkflowsRespondToAnIrsNoticeRoute
  WorkflowsRespondToAnSsaNoticeRoute: typeof WorkflowsRespondToAnSsaNoticeRoute
  WorkflowsRespondToCodeEnforcementNoticeRoute: typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  WorkflowsRespondToCp14NoticeRoute: typeof WorkflowsRespondToCp14NoticeRoute
  WorkflowsRespondToCp2000NoticeRoute: typeof WorkflowsRespondToCp2000NoticeRoute
  WorkflowsTransunionDisputeRoute: typeof WorkflowsTransunionDisputeRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respond-to-a-government-notice': {
      id: '/respond-to-a-government-notice'
      path: '/respond-to-a-government-notice'
      fullPath: '/respond-to-a-government-notice'
      preLoaderRoute: typeof RespondToAGovernmentNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/agency-action': {
      id: '/workflows/agency-action'
      path: '/workflows/agency-action'
      fullPath: '/workflows/agency-action'
      preLoaderRoute: typeof WorkflowsAgencyActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/analyze': {
      id: '/workflows/analyze'
      path: '/workflows/analyze'
      fullPath: '/workflows/analyze'
      preLoaderRoute: typeof WorkflowsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/court-summons': {
      id: '/workflows/court-summons'
      path: '/workflows/court-summons'
      fullPath: '/workflows/court-summons'
      preLoaderRoute: typeof WorkflowsCourtSummonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp14-response': {
      id: '/workflows/cp14-response'
      path: '/workflows/cp14-response'
      fullPath: '/workflows/cp14-response'
      preLoaderRoute: typeof WorkflowsCp14ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp2000-response': {
      id: '/workflows/cp2000-response'
      path: '/workflows/cp2000-response'
      fullPath: '/workflows/cp2000-response'
      preLoaderRoute: typeof WorkflowsCp2000ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp504-response': {
      id: '/workflows/cp504-response'
      path: '/workflows/cp504-response'
      fullPath: '/workflows/cp504-response'
      preLoaderRoute: typeof WorkflowsCp504ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/equifax-dispute': {
      id: '/workflows/equifax-dispute'
      path: '/workflows/equifax-dispute'
      fullPath: '/workflows/equifax-dispute'
      preLoaderRoute: typeof WorkflowsEquifaxDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/experian-dispute': {
      id: '/workflows/experian-dispute'
      path: '/workflows/experian-dispute'
      fullPath: '/workflows/experian-dispute'
      preLoaderRoute: typeof WorkflowsExperianDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/file-appeal': {
      id: '/workflows/file-appeal'
      path: '/workflows/file-appeal'
      fullPath: '/workflows/file-appeal'
      preLoaderRoute: typeof WorkflowsFileAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/irs-notice': {
      id: '/workflows/irs-notice'
      path: '/workflows/irs-notice'
      fullPath: '/workflows/irs-notice'
      preLoaderRoute: typeof WorkflowsIrsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-benefits-notice': {
      id: '/workflows/respond-to-a-benefits-notice'
      path: '/workflows/respond-to-a-benefits-notice'
      fullPath: '/workflows/respond-to-a-benefits-notice'
      preLoaderRoute: typeof WorkflowsRespondToABenefitsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-court-summons': {
      id: '/workflows/respond-to-a-court-summons'
      path: '/workflows/respond-to-a-court-summons'
      fullPath: '/workflows/respond-to-a-court-summons'
      preLoaderRoute: typeof WorkflowsRespondToACourtSummonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-dmv-notice': {
      id: '/workflows/respond-to-a-dmv-notice'
      path: '/workflows/respond-to-a-dmv-notice'
      fullPath: '/workflows/respond-to-a-dmv-notice'
      preLoaderRoute: typeof WorkflowsRespondToADmvNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-permit-correction-notice': {
      id: '/workflows/respond-to-a-permit-correction-notice'
      path: '/workflows/respond-to-a-permit-correction-notice'
      fullPath: '/workflows/respond-to-a-permit-correction-notice'
      preLoaderRoute: typeof WorkflowsRespondToAPermitCorrectionNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-tax-notice': {
      id: '/workflows/respond-to-a-tax-notice'
      path: '/workflows/respond-to-a-tax-notice'
      fullPath: '/workflows/respond-to-a-tax-notice'
      preLoaderRoute: typeof WorkflowsRespondToATaxNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-uscis-notice': {
      id: '/workflows/respond-to-a-uscis-notice'
      path: '/workflows/respond-to-a-uscis-notice'
      fullPath: '/workflows/respond-to-a-uscis-notice'
      preLoaderRoute: typeof WorkflowsRespondToAUscisNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-agency-action': {
      id: '/workflows/respond-to-an-agency-action'
      path: '/workflows/respond-to-an-agency-action'
      fullPath: '/workflows/respond-to-an-agency-action'
      preLoaderRoute: typeof WorkflowsRespondToAnAgencyActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-irs-notice': {
      id: '/workflows/respond-to-an-irs-notice'
      path: '/workflows/respond-to-an-irs-notice'
      fullPath: '/workflows/respond-to-an-irs-notice'
      preLoaderRoute: typeof WorkflowsRespondToAnIrsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-ssa-notice': {
      id: '/workflows/respond-to-an-ssa-notice'
      path: '/workflows/respond-to-an-ssa-notice'
      fullPath: '/workflows/respond-to-an-ssa-notice'
      preLoaderRoute: typeof WorkflowsRespondToAnSsaNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-code-enforcement-notice': {
      id: '/workflows/respond-to-code-enforcement-notice'
      path: '/workflows/respond-to-code-enforcement-notice'
      fullPath: '/workflows/respond-to-code-enforcement-notice'
      preLoaderRoute: typeof WorkflowsRespondToCodeEnforcementNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-cp14-notice': {
      id: '/workflows/respond-to-cp14-notice'
      path: '/workflows/respond-to-cp14-notice'
      fullPath: '/workflows/respond-to-cp14-notice'
      preLoaderRoute: typeof WorkflowsRespondToCp14NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-cp2000-notice': {
      id: '/workflows/respond-to-cp2000-notice'
      path: '/workflows/respond-to-cp2000-notice'
      fullPath: '/workflows/respond-to-cp2000-notice'
      preLoaderRoute: typeof WorkflowsRespondToCp2000NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/transunion-dispute': {
      id: '/workflows/transunion-dispute'
      path: '/workflows/transunion-dispute'
      fullPath: '/workflows/transunion-dispute'
      preLoaderRoute: typeof WorkflowsTransunionDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RespondToAGovernmentNoticeRoute: RespondToAGovernmentNoticeRoute,
  TermsRoute: TermsRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  WorkflowsAgencyActionRoute: WorkflowsAgencyActionRoute,
  WorkflowsAnalyzeRoute: WorkflowsAnalyzeRoute,
  WorkflowsCourtSummonsRoute: WorkflowsCourtSummonsRoute,
  WorkflowsCp14ResponseRoute: WorkflowsCp14ResponseRoute,
  WorkflowsCp2000ResponseRoute: WorkflowsCp2000ResponseRoute,
  WorkflowsCp504ResponseRoute: WorkflowsCp504ResponseRoute,
  WorkflowsEquifaxDisputeRoute: WorkflowsEquifaxDisputeRoute,
  WorkflowsExperianDisputeRoute: WorkflowsExperianDisputeRoute,
  WorkflowsFileAppealRoute: WorkflowsFileAppealRoute,
  WorkflowsIrsNoticeRoute: WorkflowsIrsNoticeRoute,
  WorkflowsRespondToABenefitsNoticeRoute:
    WorkflowsRespondToABenefitsNoticeRoute,
  WorkflowsRespondToACourtSummonsRoute: WorkflowsRespondToACourtSummonsRoute,
  WorkflowsRespondToADmvNoticeRoute: WorkflowsRespondToADmvNoticeRoute,
  WorkflowsRespondToAPermitCorrectionNoticeRoute:
    WorkflowsRespondToAPermitCorrectionNoticeRoute,
  WorkflowsRespondToATaxNoticeRoute: WorkflowsRespondToATaxNoticeRoute,
  WorkflowsRespondToAUscisNoticeRoute: WorkflowsRespondToAUscisNoticeRoute,
  WorkflowsRespondToAnAgencyActionRoute: WorkflowsRespondToAnAgencyActionRoute,
  WorkflowsRespondToAnIrsNoticeRoute: WorkflowsRespondToAnIrsNoticeRoute,
  WorkflowsRespondToAnSsaNoticeRoute: WorkflowsRespondToAnSsaNoticeRoute,
  WorkflowsRespondToCodeEnforcementNoticeRoute:
    WorkflowsRespondToCodeEnforcementNoticeRoute,
  WorkflowsRespondToCp14NoticeRoute: WorkflowsRespondToCp14NoticeRoute,
  WorkflowsRespondToCp2000NoticeRoute: WorkflowsRespondToCp2000NoticeRoute,
  WorkflowsTransunionDisputeRoute: WorkflowsTransunionDisputeRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
