/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsAgencyActionRouteImport } from './routes/workflows/agency-action'
import { Route as WorkflowsCourtSummonsRouteImport } from './routes/workflows/court-summons'
import { Route as WorkflowsFileAppealRouteImport } from './routes/workflows/file-appeal'
import { Route as WorkflowsIrsNoticeRouteImport } from './routes/workflows/irs-notice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsAgencyActionRoute = WorkflowsAgencyActionRouteImport.update({
  id: '/workflows/agency-action',
  path: '/workflows/agency-action',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCourtSummonsRoute = WorkflowsCourtSummonsRouteImport.update({
  id: '/workflows/court-summons',
  path: '/workflows/court-summons',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsFileAppealRoute = WorkflowsFileAppealRouteImport.update({
  id: '/workflows/file-appeal',
  path: '/workflows/file-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIrsNoticeRoute = WorkflowsIrsNoticeRouteImport.update({
  id: '/workflows/irs-notice',
  path: '/workflows/irs-notice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/court-summons'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/court-summons'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/court-summons'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  WorkflowsAgencyActionRoute: typeof WorkflowsAgencyActionRoute
  WorkflowsCourtSummonsRoute: typeof WorkflowsCourtSummonsRoute
  WorkflowsFileAppealRoute: typeof WorkflowsFileAppealRoute
  WorkflowsIrsNoticeRoute: typeof WorkflowsIrsNoticeRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/agency-action': {
      id: '/workflows/agency-action'
      path: '/workflows/agency-action'
      fullPath: '/workflows/agency-action'
      preLoaderRoute: typeof WorkflowsAgencyActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/court-summons': {
      id: '/workflows/court-summons'
      path: '/workflows/court-summons'
      fullPath: '/workflows/court-summons'
      preLoaderRoute: typeof WorkflowsCourtSummonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/file-appeal': {
      id: '/workflows/file-appeal'
      path: '/workflows/file-appeal'
      fullPath: '/workflows/file-appeal'
      preLoaderRoute: typeof WorkflowsFileAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/irs-notice': {
      id: '/workflows/irs-notice'
      path: '/workflows/irs-notice'
      fullPath: '/workflows/irs-notice'
      preLoaderRoute: typeof WorkflowsIrsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  WorkflowsAgencyActionRoute: WorkflowsAgencyActionRoute,
  WorkflowsCourtSummonsRoute: WorkflowsCourtSummonsRoute,
  WorkflowsFileAppealRoute: WorkflowsFileAppealRoute,
  WorkflowsIrsNoticeRoute: WorkflowsIrsNoticeRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
