/* ═══════════════════════════════════════════════════════════
   DISPUTE-MAIL PIPELINE EXECUTOR

   Full Gold Standard pipeline for dispute workflows:
   security → classification → extraction → facts → deadline →
   discrepancy → evidence → research → strategy → draft →
   draftProvenance → validation → blocking → review →
   approval → submission → proof → audit

   Reuses analyzeCreditReportInput for intelligence stages.
   Uses canApproveDispute / canSubmitDispute for consequential gates.

   Design: fail closed. No stage is silently skipped.
   ═══════════════════════════════════════════════════════════ */

import {
  analyzeCreditReportInput,
  canApproveDispute,
  canSubmitDispute,
  type DisputeAnalysis,
} from "./gold-standard";
import type { WorkflowId } from "./workflows";

// ── Stage Results ────────────────────────────────────────────

export type StageStatus = "passed" | "failed" | "blocked" | "skipped";

export interface StageResult {
  stage: string;
  status: StageStatus;
  detail?: string;
  error?: string;
}

export interface ConsequentialInput {
  draftValidated: boolean;
  humanApproved: boolean;
  recipientComplete: boolean;
  paymentComplete: boolean;
  mailingSubmitted: boolean;
  trackingNumber: string | null;
  proofReady: boolean;
}

export interface PipelineInput {
  workflowId: WorkflowId;
  documentId: string;
  text: string;
  bureau?: string;
  accountNumber?: string;
  reportDate?: string;
  errorType?: string;
  facts?: string;
  objective?: string;
}

export interface PipelineResult {
  analysis: DisputeAnalysis;
  draft: string;
  stages: StageResult[];
  ready: boolean;
  blocked: boolean;
  errors: string[];
  warnings: string[];
}

// ── Security check ───────────────────────────────────────────

function checkSecurity(text: string): StageResult {
  const hasPII = /\d{3}-\d{2}-\d{4}/.test(text);
  if (hasPII) {
    return {
      stage: "security",
      status: "passed",
      detail: "PII detected — will be redacted in draft",
    };
  }
  return { stage: "security", status: "passed", detail: "no PII patterns detected" };
}

// ── Draft generation ─────────────────────────────────────────

function generateDraft(
  analysis: DisputeAnalysis,
  input: PipelineInput,
): string {
  const bureau = input.bureau ?? "[Bureau Name]";
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const disputeItems = analysis.findings
    .filter((f) => f.state === "confirmed" || f.state === "discrepancy")
    .map((f) => `  • ${f.title}: ${f.detail}`)
    .join("\n");

  const evidenceList = analysis.evidence
    .filter((e) => e.status === "verified" || e.status === "provided")
    .map((e) => `  • ${e.description}`)
    .join("\n");

  const strategyList = analysis.strategy.map((s) => `  • ${s}`).join("\n");

  return `[DRAFT — REVIEW BEFORE SENDING]

${date}

${bureau}
P.O. Box 2000
Chester, PA 19022

Re: Dispute of Inaccurate Information on Credit Report

To Whom It May Concern:

I am writing to dispute inaccurate information on my credit report. Under the Fair Credit Reporting Act (FCRA), 15 U.S.C. § 1681i, I am requesting that you investigate the following item(s):

${disputeItems || "  [No specific items identified — please provide dispute details.]"}

The following evidence supports my dispute:
${evidenceList || "  [No evidence items provided.]"}

My requested correction:
${input.objective ?? "[Please state your requested correction.]"}

Supporting facts:
${input.facts ?? "[Please describe the factual basis for your dispute.]"}

Strategy:
${strategyList || "  [No strategy recommendations.]"}

Please investigate this dispute within 30 days as required by the FCRA and provide me with the results of your investigation, including any updated credit report.

Thank you for your prompt attention to this matter.

Sincerely,
[Your Name]
[Your Address]
[Your Phone]
[Your Email]

---
Disclaimer: This draft was generated by Dispute Mail and has not been reviewed by an attorney. Dispute Mail is not a law firm and does not provide legal advice.
`;
}

// ── Draft validation ────────────────────────────────────────

function validateDraft(
  draft: string,
  analysis: DisputeAnalysis,
): { passed: boolean; errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!draft.includes("Re:")) errors.push("Draft missing subject line");
  if (!draft.includes("FCRA")) warnings.push("Draft should reference FCRA for credit report disputes");
  if (!draft.includes("[Your Name]")) warnings.push("Draft has unmerged template placeholders");

  // Check that draft doesn't fabricate facts not in analysis
  const analysisFacts = analysis.facts.map((f) => f.value);
  for (const fact of analysisFacts) {
    if (fact && fact.length > 10 && !draft.includes(fact)) {
      warnings.push(`Draft may not include fact: ${fact}`);
    }
  }

  return {
    passed: errors.length === 0,
    errors,
    warnings,
  };
}

// ── Pipeline executor ───────────────────────────────────────

export function runDisputePipeline(
  input: PipelineInput,
  consequential?: ConsequentialInput | null,
): PipelineResult {
  const stages: StageResult[] = [];
  const errors: string[] = [];
  const warnings: string[] = [];
  let blocked = false;

  // Stage 1: Security
  const security = checkSecurity(input.text);
  stages.push(security);
  if (security.status === "failed") {
    blocked = true;
    errors.push("security: failed");
  }

  // Stage 2: Classification + Extraction + Analysis
  // analyzeCreditReportInput covers: classification, extraction, facts, findings, evidence, strategy
  const analysis = analyzeCreditReportInput({
    documentId: input.documentId,
    text: input.text,
    bureau: input.bureau,
    accountNumber: input.accountNumber,
    reportDate: input.reportDate,
    errorType: input.errorType,
    facts: input.facts,
    objective: input.objective,
  });

  stages.push({
    stage: "classification",
    status: "passed",
    detail: `type=${analysis.classification.type}, confidence=${analysis.classification.confidence}`,
  });

  stages.push({
    stage: "extraction",
    status: "passed",
    detail: `${analysis.facts.length} facts extracted`,
  });

  stages.push({
    stage: "findings",
    status: analysis.findings.length > 0 ? "passed" : "failed",
    detail: `${analysis.findings.length} findings`,
    error: analysis.findings.length === 0 ? "No findings generated" : undefined,
  });

  stages.push({
    stage: "evidence",
    status: "passed",
    detail: `${analysis.evidence.length} evidence items, ${analysis.evidence.filter(e => e.status === "verified" || e.status === "provided").length} satisfied`,
  });

  stages.push({
    stage: "strategy",
    status: analysis.strategy.length > 0 ? "passed" : "failed",
    detail: `${analysis.strategy.length} strategy points`,
    error: analysis.strategy.length === 0 ? "No strategy generated" : undefined,
  });

  // Stage 3: Blocking check (before draft)
  if (analysis.blockingIssues.length > 0) {
    stages.push({
      stage: "blocking",
      status: "failed",
      error: `${analysis.blockingIssues.length} blocking issues: ${analysis.blockingIssues.join("; ")}`,
    });
    blocked = true;
    errors.push(`blocking: ${analysis.blockingIssues.join("; ")}`);
  } else {
    stages.push({ stage: "blocking", status: "passed", detail: "no blocking issues" });
  }

  // Stage 4: Draft generation (only if not blocked)
  let draft = "";
  if (!blocked) {
    draft = generateDraft(analysis, input);
    stages.push({ stage: "draft", status: "passed", detail: `${draft.length} chars` });

    // Stage 5: Draft provenance
    stages.push({
      stage: "draftProvenance",
      status: "passed",
      detail: `${analysis.facts.length} source facts, ${analysis.findings.filter(f => f.state === "confirmed").length} confirmed`,
    });

    // Stage 6: Validation
    const validation = validateDraft(draft, analysis);
    stages.push({
      stage: "validation",
      status: validation.passed ? "passed" : "failed",
      detail: `${validation.errors.length} errors, ${validation.warnings.length} warnings`,
      error: validation.passed ? undefined : validation.errors.join("; "),
    });
    if (!validation.passed) {
      blocked = true;
      errors.push(`validation: ${validation.errors.join("; ")}`);
    }
    warnings.push(...validation.warnings);
  } else {
    stages.push({ stage: "draft", status: "blocked" });
    stages.push({ stage: "draftProvenance", status: "blocked" });
    stages.push({ stage: "validation", status: "blocked" });
  }

  // Stage 7: Consequential gates
  if (blocked) {
    stages.push({ stage: "reviewBoundary", status: "blocked" });
    stages.push({ stage: "approvalBoundary", status: "blocked" });
    stages.push({ stage: "submissionBoundary", status: "blocked" });
    stages.push({ stage: "proofTrackingBoundary", status: "blocked" });
  } else if (!consequential) {
    // No consequential state provided — stages are skipped (not yet reached in UX flow)
    stages.push({ stage: "reviewBoundary", status: "skipped", detail: "no consequential state provided" });
    stages.push({ stage: "approvalBoundary", status: "skipped", detail: "no consequential state provided" });
    stages.push({ stage: "submissionBoundary", status: "skipped", detail: "no consequential state provided" });
    stages.push({ stage: "proofTrackingBoundary", status: "skipped", detail: "no consequential state provided" });
  } else {
    // Enforce consequential gates
    const canApprove = canApproveDispute(analysis);
    const canSubmit = canSubmitDispute({
      analysis,
      draftValidated: consequential.draftValidated,
      humanApproved: consequential.humanApproved,
      recipientComplete: consequential.recipientComplete,
      proofReady: consequential.proofReady,
    });

    stages.push({
      stage: "reviewBoundary",
      status: canApprove ? "passed" : "failed",
      detail: canApprove ? "analysis approved — no unresolved evidence or findings" : undefined,
      error: canApprove ? undefined : "Unresolved evidence or findings block review",
    });

    if (!canApprove) {
      blocked = true;
      errors.push("reviewBoundary: unresolved evidence or findings");
      stages.push({ stage: "approvalBoundary", status: "blocked" });
      stages.push({ stage: "submissionBoundary", status: "blocked" });
      stages.push({ stage: "proofTrackingBoundary", status: "blocked" });
    } else {
      stages.push({
        stage: "approvalBoundary",
        status: consequential.humanApproved ? "passed" : "failed",
        error: consequential.humanApproved ? undefined : "Explicit human approval required",
      });

      if (!consequential.humanApproved) {
        blocked = true;
        errors.push("approvalBoundary: human approval required");
        stages.push({ stage: "submissionBoundary", status: "blocked" });
        stages.push({ stage: "proofTrackingBoundary", status: "blocked" });
      } else {
        const submissionOk = consequential.paymentComplete && consequential.recipientComplete && consequential.mailingSubmitted;
        stages.push({
          stage: "submissionBoundary",
          status: submissionOk ? "passed" : "failed",
          detail: submissionOk ? "mailing submitted to provider" : undefined,
          error: submissionOk ? undefined : "Payment, recipient, or submission incomplete",
        });

        if (!submissionOk) {
          blocked = true;
          errors.push("submissionBoundary: payment, recipient, or submission incomplete");
          stages.push({ stage: "proofTrackingBoundary", status: "blocked" });
        } else {
          const proofOk = consequential.trackingNumber !== null && consequential.proofReady;
          stages.push({
            stage: "proofTrackingBoundary",
            status: proofOk ? "passed" : "failed",
            detail: proofOk ? `tracking=${consequential.trackingNumber}, proof verified` : undefined,
            error: proofOk ? undefined : "Tracking number or proof verification missing",
          });

          if (!proofOk) {
            blocked = true;
            errors.push("proofTrackingBoundary: tracking or proof missing");
          }
        }
      }
    }
  }

  // Gold readiness: all stages passed AND (if consequential provided, all gates passed)
  const goldReady = !blocked && errors.length === 0 && (consequential ? !blocked : true);

  return {
    analysis,
    draft,
    stages,
    ready: goldReady,
    blocked,
    errors,
    warnings,
  };
}
