import type { WorkflowId } from "./workflows";

export interface WorkflowProfile {
  id: WorkflowId;
  slug: string;
  primaryKeyword: string;
  supportingKeywords: string[];
  searchIntent: "transactional" | "commercial" | "problem";
  problem: string;
  outcome: string;
  recipientRole: string;
  requiredFacts: string[];
  evidenceRequirements: string[];
  deadlinePolicy: string;
  objectivePrompt: string;
  draftSubject: string;
  disclaimer: string;
}

const commonDisclaimer =
  "Dispute Mail provides document preparation and mailing assistance. It is not a law firm and does not provide legal advice. Do not use a workflow as a substitute for required bank, issuer, regulator, or creditor reporting procedures.";

export const workflowProfiles: Record<WorkflowId, WorkflowProfile> = {
  "debt-collection-dispute": {
    id: "debt-collection-dispute",
    slug: "debt-collection-dispute",
    primaryKeyword: "debt collection dispute",
    supportingKeywords: ["dispute collection", "disputing a debt in collections", "dispute letter for collections"],
    searchIntent: "transactional",
    problem: "A debt collector is pursuing an account the customer believes is inaccurate, unsupported, or otherwise disputed.",
    outcome: "Create a factual dispute record identifying the account, the disputed facts, requested correction, and supporting evidence.",
    recipientRole: "debt collector or collection agency",
    requiredFacts: ["collector name", "account/reference number", "why the account is disputed", "requested resolution"],
    evidenceRequirements: ["collection notice or account statement", "documents supporting the disputed facts", "payment or account records when relevant"],
    deadlinePolicy: "Capture the date of the collector's notice/contact and any stated response deadline; do not invent a deadline.",
    objectivePrompt: "What specific correction, investigation, documentation, or other resolution are you requesting from the collector?",
    draftSubject: "Dispute of Debt Collection Account",
    disclaimer: commonDisclaimer,
  },
  "dispute-collection-agency": {
    id: "dispute-collection-agency",
    slug: "dispute-collection-agency",
    primaryKeyword: "dispute collection agency",
    supportingKeywords: ["dispute letter to collection agency", "dispute letter for collections", "debt dispute letter"],
    searchIntent: "transactional",
    problem: "A collection agency is contacting the customer and the customer needs a documented written dispute.",
    outcome: "Prepare a targeted written dispute addressed to the correct collection agency with an evidence-backed factual record.",
    recipientRole: "collection agency",
    requiredFacts: ["agency name", "account/reference number", "basis for dispute", "requested action"],
    evidenceRequirements: ["agency notice", "account documentation", "supporting correspondence"],
    deadlinePolicy: "Preserve and evaluate any date stated in the collection notice or correspondence; never infer a deadline from a missing notice.",
    objectivePrompt: "What do you want the collection agency to investigate, correct, document, or stop doing?",
    draftSubject: "Written Dispute of Collection Account",
    disclaimer: commonDisclaimer,
  },
  "debt-dispute": {
    id: "debt-dispute",
    slug: "debt-dispute-letter",
    primaryKeyword: "debt dispute letter",
    supportingKeywords: ["debt dispute", "dispute debt", "debt account dispute"],
    searchIntent: "transactional",
    problem: "The customer disputes the accuracy, ownership, balance, or reporting of a debt account.",
    outcome: "Build a clear account-level dispute supported by specific facts and documentary evidence.",
    recipientRole: "creditor, servicer, or collector",
    requiredFacts: ["account identity", "claimed balance or account issue", "factual basis", "requested resolution"],
    evidenceRequirements: ["account statement or notice", "payment records", "contracts or correspondence when relevant"],
    deadlinePolicy: "Capture all dates visible in the source documents and flag any stated deadline for review.",
    objectivePrompt: "Which account facts do you dispute and what correction or investigation are you requesting?",
    draftSubject: "Dispute of Debt Account",
    disclaimer: commonDisclaimer,
  },
  "debt-validation": {
    id: "debt-validation",
    slug: "debt-validation-letter",
    primaryKeyword: "debt validation letter",
    supportingKeywords: ["debt verification letter", "debt validation request", "request for verification of debt"],
    searchIntent: "transactional",
    problem: "The customer wants to request documentation supporting a debt claim from a collector.",
    outcome: "Prepare a focused validation request grounded in the collection notice and the customer's stated facts.",
    recipientRole: "debt collector or collection agency",
    requiredFacts: ["collector identity", "account/reference number", "date of first contact when known", "validation request objective"],
    evidenceRequirements: ["collection notice", "account correspondence", "prior collector communications"],
    deadlinePolicy: "Record the first-contact date and any notice date; identify potential timing issues for human review rather than asserting legal conclusions.",
    objectivePrompt: "What documentation or information do you want the collector to provide to substantiate the debt?",
    draftSubject: "Request for Debt Validation",
    disclaimer: commonDisclaimer,
  },
  "credit-report": {
    id: "credit-report",
    slug: "credit-report-dispute-letter",
    primaryKeyword: "credit dispute letter",
    supportingKeywords: ["dispute credit report letter", "credit bureau dispute letter", "credit report dispute letter template"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate, incomplete, or unverifiable information on a credit report.",
    outcome: "Prepare a bureau-specific factual dispute identifying the tradeline, supporting evidence, and requested correction.",
    recipientRole: "credit bureau",
    requiredFacts: ["credit bureau", "account/reference number", "reporting error", "requested correction"],
    evidenceRequirements: ["credit report page or excerpt", "identity/address support when relevant", "documents establishing the correct information"],
    deadlinePolicy: "Capture report date and any relevant notice dates. Do not promise an investigation outcome or fixed completion date.",
    objectivePrompt: "What specific item is inaccurate and what exact correction or investigation are you requesting?",
    draftSubject: "Dispute of Inaccurate Credit Report Information",
    disclaimer: "Dispute Mail provides document preparation and mailing assistance. It is not a law firm and does not provide legal advice. Do not represent that a dispute will necessarily remove or change an account.",
  },
  "credit-report-collections": {
    id: "credit-report-collections",
    slug: "dispute-collections-on-credit-report",
    primaryKeyword: "dispute collections on credit report",
    supportingKeywords: ["collection-account credit dispute", "dispute collection on credit report", "credit report collections dispute"],
    searchIntent: "transactional",
    problem: "A collection account appears on the customer's credit report and the customer disputes its accuracy, ownership, balance, or status.",
    outcome: "Connect the credit-report entry to supporting account evidence and prepare a bureau dispute focused on the specific inaccuracies.",
    recipientRole: "credit bureau and, when appropriate, data furnisher",
    requiredFacts: ["bureau", "collection account identity", "specific reporting error", "requested correction"],
    evidenceRequirements: ["credit report entry", "collector documents", "payment/account records"],
    deadlinePolicy: "Record report and collection-notice dates; surface timing facts for review instead of inventing statutory conclusions.",
    objectivePrompt: "Which collection-reporting fields are wrong and what correction should be investigated?",
    draftSubject: "Dispute of Collection Account Reporting",
    disclaimer: commonDisclaimer,
  },
  "hard-inquiry": {
    id: "hard-inquiry",
    slug: "hard-inquiry-removal-letter",
    primaryKeyword: "hard inquiry removal letter",
    supportingKeywords: ["dispute hard inquiry", "hard inquiry dispute", "credit inquiry dispute letter"],
    searchIntent: "transactional",
    problem: "The customer does not recognize or disputes a hard inquiry listed on a credit report.",
    outcome: "Prepare a documented inquiry dispute that distinguishes an unrecognized inquiry from one the customer actually authorized.",
    recipientRole: "credit bureau and potentially inquiry furnisher",
    requiredFacts: ["bureau", "inquiry date", "inquirer name", "why inquiry is disputed", "requested resolution"],
    evidenceRequirements: ["credit report excerpt", "identity or account records", "correspondence regarding the inquiry when available"],
    deadlinePolicy: "Capture inquiry date and report date; flag identity/fraud concerns for separate human action when indicated.",
    objectivePrompt: "Why do you believe this hard inquiry is inaccurate or unauthorized, and what should be investigated?",
    draftSubject: "Dispute of Hard Credit Inquiry",
    disclaimer: commonDisclaimer,
  },
  "charge-off": {
    id: "charge-off",
    slug: "charge-off-dispute",
    primaryKeyword: "charge off dispute letter",
    supportingKeywords: ["charge-off dispute", "charge off removal letter", "credit charge-off dispute"],
    searchIntent: "transactional",
    problem: "A charge-off is reported inaccurately or the customer disputes the balance, status, dates, or underlying account information.",
    outcome: "Document the exact charge-off fields in dispute and assemble evidence supporting the requested investigation or correction.",
    recipientRole: "credit bureau and data furnisher",
    requiredFacts: ["bureau", "account identity", "charge-off field disputed", "factual basis", "requested correction"],
    evidenceRequirements: ["credit report", "account statements", "payment history", "correspondence"],
    deadlinePolicy: "Capture the reporting dates and account timeline; flag contradictions instead of asserting that a charge-off must be deleted.",
    objectivePrompt: "Which charge-off facts are inaccurate, and what correction or investigation are you asking for?",
    draftSubject: "Dispute of Charge-Off Reporting",
    disclaimer: commonDisclaimer,
  },
  "medical-collections": {
    id: "medical-collections",
    slug: "medical-collections-dispute",
    primaryKeyword: "dispute medical collections",
    supportingKeywords: ["dispute medical bill collections", "medical debt dispute", "medical collections dispute letter"],
    searchIntent: "transactional",
    problem: "The customer disputes a medical collection or the underlying medical billing information.",
    outcome: "Separate billing facts from collection reporting and build a documented dispute supported by statements, insurer records, and correspondence.",
    recipientRole: "medical provider, billing department, collector, or credit bureau depending on the issue",
    requiredFacts: ["provider or collector", "account identity", "billing issue", "insurance/payment facts", "requested correction"],
    evidenceRequirements: ["medical bill", "EOB/insurance records when applicable", "payment receipts", "collection notice"],
    deadlinePolicy: "Record bill, EOB, collection, and report dates. Surface conflicting dates for review.",
    objectivePrompt: "What medical charge, insurance/payment fact, or collection reporting do you dispute?",
    draftSubject: "Dispute of Medical Billing or Collection Information",
    disclaimer: commonDisclaimer,
  },
  "student-loan": {
    id: "student-loan",
    slug: "student-loan-dispute-letter",
    primaryKeyword: "student loan dispute letter",
    supportingKeywords: ["dispute letter for student loans", "student loan dispute", "student loan account dispute"],
    searchIntent: "transactional",
    problem: "The customer disputes a student-loan account, servicing record, payment history, balance, or related reporting.",
    outcome: "Create a factual servicer or credit-report dispute grounded in account records and the customer's requested correction.",
    recipientRole: "student loan servicer, lender, or credit bureau",
    requiredFacts: ["servicer/lender", "loan or account identity", "disputed fact", "payment history context", "requested correction"],
    evidenceRequirements: ["servicer statement", "payment records", "loan correspondence", "credit report when reporting is disputed"],
    deadlinePolicy: "Capture statement, correspondence, and report dates and preserve any stated response window.",
    objectivePrompt: "What student-loan account information is wrong and what correction or investigation should occur?",
    draftSubject: "Dispute of Student Loan Account Information",
    disclaimer: commonDisclaimer,
  },
  "credit-card-billing": {
    id: "credit-card-billing",
    slug: "credit-card-billing-dispute",
    primaryKeyword: "credit card dispute letter",
    supportingKeywords: ["credit card billing dispute", "credit card charge dispute letter", "billing error credit card"],
    searchIntent: "transactional",
    problem: "A customer disputes a credit-card billing item and wants a documented written record to the issuer.",
    outcome: "Prepare a focused billing dispute that identifies the transaction, factual basis, supporting records, and requested correction.",
    recipientRole: "credit-card issuer",
    requiredFacts: ["issuer", "account reference", "transaction/date", "dispute reason", "requested resolution"],
    evidenceRequirements: ["statement excerpt", "receipt/order record", "merchant correspondence", "other supporting records"],
    deadlinePolicy: "Capture statement and transaction dates and prominently flag any issuer-provided dispute deadline for review.",
    objectivePrompt: "Which transaction is disputed, why is it wrong, and what correction or investigation do you request?",
    draftSubject: "Written Credit Card Billing Dispute",
    disclaimer: "Dispute Mail provides document preparation and mailing assistance. It is not a law firm and does not provide legal advice. Follow your issuer's required dispute or fraud process in addition to any mailed correspondence.",
  },
  "unauthorized-charge": {
    id: "unauthorized-charge",
    slug: "unauthorized-charge-dispute",
    primaryKeyword: "unauthorized charge dispute",
    supportingKeywords: ["fraudulent charge dispute", "unauthorized payment dispute", "dispute unauthorized transaction"],
    searchIntent: "transactional",
    problem: "The customer does not recognize or did not authorize a payment transaction.",
    outcome: "Create a written factual record for the issuer or bank while clearly directing the customer to complete the issuer's fraud process.",
    recipientRole: "bank, card issuer, or payment provider",
    requiredFacts: ["institution", "transaction/date", "amount", "why unauthorized", "requested action"],
    evidenceRequirements: ["statement/transaction record", "identity confirmation", "merchant communications when available"],
    deadlinePolicy: "Capture transaction date and institution notice/reporting dates; flag urgency without inventing a universal deadline.",
    objectivePrompt: "What transaction do you say was unauthorized, and what investigation or correction are you requesting?",
    draftSubject: "Notice of Unauthorized Transaction",
    disclaimer: "Written correspondence does not replace required fraud reporting, account freezes, or issuer procedures. Dispute Mail is not a law firm and does not provide legal advice.",
  },
  "billing-error": {
    id: "billing-error",
    slug: "billing-dispute-letter",
    primaryKeyword: "billing dispute letter",
    supportingKeywords: ["dispute billing error", "billing error letter", "incorrect bill dispute"],
    searchIntent: "transactional",
    problem: "A customer believes a provider's bill, invoice, statement, or service charge is incorrect.",
    outcome: "Prepare a provider-facing billing dispute with a line-item factual comparison and requested correction.",
    recipientRole: "billing department, service provider, or merchant",
    requiredFacts: ["provider", "invoice/account identity", "line item or charge disputed", "factual basis", "requested correction"],
    evidenceRequirements: ["invoice/statement", "contract/order", "payment records", "provider correspondence"],
    deadlinePolicy: "Capture invoice, statement, and contract dates and any stated dispute window.",
    objectivePrompt: "Which line item or charge is wrong, why is it wrong, and what correction do you want?",
    draftSubject: "Billing Dispute and Request for Correction",
    disclaimer: commonDisclaimer,
  },
  "subscription-billing": {
    id: "subscription-billing",
    slug: "subscription-billing-dispute",
    primaryKeyword: "subscription billing dispute",
    supportingKeywords: ["recurring charge dispute", "subscription charge dispute", "cancelled subscription charge"],
    searchIntent: "transactional",
    problem: "A recurring subscription charge is disputed because of cancellation, duplicate billing, pricing, or service issues.",
    outcome: "Build a dated billing record showing signup, cancellation, charges, communications, and requested correction.",
    recipientRole: "merchant, subscription provider, or billing department",
    requiredFacts: ["merchant/provider", "subscription identity", "charge dates/amounts", "cancellation or billing event", "requested resolution"],
    evidenceRequirements: ["billing statement", "cancellation confirmation", "terms/order record", "support correspondence"],
    deadlinePolicy: "Record charge and cancellation dates and any merchant or issuer dispute deadlines.",
    objectivePrompt: "Which recurring charges are disputed and what correction or refund are you requesting?",
    draftSubject: "Subscription Billing Dispute",
    disclaimer: commonDisclaimer,
  },
  "service-contract": {
    id: "service-contract",
    slug: "service-contract-dispute",
    primaryKeyword: "service contract dispute letter",
    supportingKeywords: ["contract billing dispute", "service agreement dispute", "dispute service contract charge"],
    searchIntent: "transactional",
    problem: "A customer disputes a service provider's performance, billing, cancellation, or contract-related charge.",
    outcome: "Compare the contract terms against what was billed or performed and document the requested resolution.",
    recipientRole: "service provider or contract administrator",
    requiredFacts: ["provider", "contract/order identity", "relevant term", "actual event", "requested resolution"],
    evidenceRequirements: ["service contract", "invoice", "work order", "communications", "proof of performance/nonperformance"],
    deadlinePolicy: "Capture contract dates, service dates, invoice dates, and any contractual notice deadline.",
    objectivePrompt: "Which contract promise or charge is disputed, what happened, and what remedy are you requesting?",
    draftSubject: "Service Contract Dispute and Request for Resolution",
    disclaimer: commonDisclaimer,
  },
  "insurance-billing": {
    id: "insurance-billing",
    slug: "insurance-billing-dispute",
    primaryKeyword: "insurance billing dispute letter",
    supportingKeywords: ["insurance claim billing dispute", "insurance payment dispute", "dispute insurance bill"],
    searchIntent: "transactional",
    problem: "A customer disputes an insurance-related bill, payment, benefit calculation, or claim-related charge.",
    outcome: "Build a claim/payment timeline with source documents and identify the exact billing or payment discrepancy.",
    recipientRole: "insurer, claims administrator, provider billing department, or plan administrator",
    requiredFacts: ["insurer/administrator", "claim or account number", "date of service/claim", "payment or billing discrepancy", "requested resolution"],
    evidenceRequirements: ["EOB/claim statement", "invoice", "policy/plan correspondence", "payment records"],
    deadlinePolicy: "Capture claim, EOB, invoice, and appeal/grievance dates visible in the documents.",
    objectivePrompt: "What payment, benefit, or billing result is disputed and what correction or review are you requesting?",
    draftSubject: "Insurance Billing or Payment Dispute",
    disclaimer: commonDisclaimer,
  },
  "follow-up-no-response": {
    id: "follow-up-no-response",
    slug: "dispute-follow-up-no-response",
    primaryKeyword: "follow up dispute letter no response",
    supportingKeywords: ["follow up dispute letter", "credit dispute no response", "collection dispute follow up"],
    searchIntent: "problem",
    problem: "The customer already sent a dispute and has not received a response or acknowledgement.",
    outcome: "Create a follow-up record tying the new letter to the original submission, date, proof, and unresolved issue.",
    recipientRole: "original dispute recipient",
    requiredFacts: ["original recipient", "original dispute date", "original tracking/proof when available", "unresolved issue", "requested response"],
    evidenceRequirements: ["original dispute", "mailing proof/tracking", "supporting documents", "any acknowledgement received"],
    deadlinePolicy: "Use the original submission date and documented response window if one exists; flag missing proof.",
    objectivePrompt: "What response or action is still missing from your original dispute?",
    draftSubject: "Follow-Up Regarding Previously Submitted Dispute",
    disclaimer: commonDisclaimer,
  },
  "inadequate-response": {
    id: "inadequate-response",
    slug: "dispute-response-escalation",
    primaryKeyword: "dispute escalation letter",
    supportingKeywords: ["dispute response inadequate", "follow up credit dispute", "escalate billing dispute"],
    searchIntent: "problem",
    problem: "The customer received a response to a dispute but believes the response did not address the identified issue.",
    outcome: "Compare the original dispute to the response, identify what remains unresolved, and prepare a documented escalation.",
    recipientRole: "original recipient, supervisor, complaints team, or escalation department",
    requiredFacts: ["original dispute", "response received", "remaining unresolved issue", "requested next action"],
    evidenceRequirements: ["original dispute", "response", "proof of delivery", "supporting evidence"],
    deadlinePolicy: "Capture original submission and response dates plus any stated escalation deadline.",
    objectivePrompt: "Which parts of the response did not resolve your original dispute, and what should happen next?",
    draftSubject: "Escalation of Unresolved Dispute",
    disclaimer: commonDisclaimer,
  },
  "cease-contact": {
    id: "cease-contact",
    slug: "cease-contact-correspondence",
    primaryKeyword: "cease contact letter debt collector",
    supportingKeywords: ["stop debt collection calls letter", "cease communication letter collector", "collection contact letter"],
    searchIntent: "transactional",
    problem: "The customer wants documented written communication about future contact from a collector or other recipient.",
    outcome: "Prepare a narrow correspondence record based on the customer's stated communications preference and circumstances.",
    recipientRole: "debt collector or collection agency",
    requiredFacts: ["collector identity", "account/reference number when known", "contact issue", "requested communication preference"],
    evidenceRequirements: ["recent collection communications", "call/message records when relevant", "prior written correspondence"],
    deadlinePolicy: "Capture recent contact dates and any notice dates. Do not promise that sending a letter resolves all legal obligations or contact.",
    objectivePrompt: "What future contact or communication do you want the recipient to change or stop?",
    draftSubject: "Written Communication Request Regarding Collection Contact",
    disclaimer: "Dispute Mail provides document preparation and mailing assistance and is not a law firm. Legal effects of a communication request vary by circumstance; do not assume a letter changes underlying obligations.",
  },

  "transunion-dispute": {
    id: "transunion-dispute",
    slug: "transunion-dispute",
    primaryKeyword: "transunion dispute",
    supportingKeywords: ["transunion credit dispute", "dispute transunion report", "transunion credit report dispute letter"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate, incomplete, or unverifiable information on a TransUnion credit report.",
    outcome: "Prepare a TransUnion-specific factual dispute identifying the tradeline, supporting evidence, and requested correction.",
    recipientRole: "TransUnion",
    requiredFacts: ["TransUnion report reference", "account/reference number", "reporting error", "requested correction"],
    evidenceRequirements: ["TransUnion credit report page or excerpt", "identity/address support", "documents establishing correct information"],
    deadlinePolicy: "Capture report date and any relevant notice dates. Do not promise an investigation outcome or fixed completion date.",
    objectivePrompt: "What specific item is inaccurate on your TransUnion report and what correction are you requesting?",
    draftSubject: "Dispute of Inaccurate TransUnion Credit Report Information",
    disclaimer: commonDisclaimer,
  },
  "experian-dispute": {
    id: "experian-dispute",
    slug: "experian-dispute",
    primaryKeyword: "experian dispute",
    supportingKeywords: ["experian credit dispute", "dispute experian report", "experian credit report dispute letter"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate, incomplete, or unverifiable information on an Experian credit report.",
    outcome: "Prepare an Experian-specific factual dispute identifying the tradeline, supporting evidence, and requested correction.",
    recipientRole: "Experian",
    requiredFacts: ["Experian report reference", "account/reference number", "reporting error", "requested correction"],
    evidenceRequirements: ["Experian credit report page or excerpt", "identity/address support", "documents establishing correct information"],
    deadlinePolicy: "Capture report date and any relevant notice dates. Do not promise an investigation outcome or fixed completion date.",
    objectivePrompt: "What specific item is inaccurate on your Experian report and what correction are you requesting?",
    draftSubject: "Dispute of Inaccurate Experian Credit Report Information",
    disclaimer: commonDisclaimer,
  },
  "equifax-dispute": {
    id: "equifax-dispute",
    slug: "equifax-dispute",
    primaryKeyword: "equifax dispute",
    supportingKeywords: ["equifax credit dispute", "dispute equifax report", "equifax credit report dispute letter"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate, incomplete, or unverifiable information on an Equifax credit report.",
    outcome: "Prepare an Equifax-specific factual dispute identifying the tradeline, supporting evidence, and requested correction.",
    recipientRole: "Equifax",
    requiredFacts: ["Equifax report reference", "account/reference number", "reporting error", "requested correction"],
    evidenceRequirements: ["Equifax credit report page or excerpt", "identity/address support", "documents establishing correct information"],
    deadlinePolicy: "Capture report date and any relevant notice dates. Do not promise an investigation outcome or fixed completion date.",
    objectivePrompt: "What specific item is inaccurate on your Equifax report and what correction are you requesting?",
    draftSubject: "Dispute of Inaccurate Equifax Credit Report Information",
    disclaimer: commonDisclaimer,
  },
  "lexisnexis-dispute": {
    id: "lexisnexis-dispute",
    slug: "lexisnexis-dispute",
    primaryKeyword: "lexisnexis dispute",
    supportingKeywords: ["lexisnexis consumer dispute", "dispute lexisnexis report", "lexisnexis accuracy dispute"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate or unverifiable information in a LexisNexis consumer report.",
    outcome: "Prepare a LexisNexis-specific factual dispute identifying the inaccurate information and requested correction.",
    recipientRole: "LexisNexis",
    requiredFacts: ["LexisNexis file/reference number", "inaccurate information", "requested correction"],
    evidenceRequirements: ["LexisNexis report excerpt", "identity verification documents", "supporting records"],
    deadlinePolicy: "Capture report date. LexisNexis must investigate within a reasonable period under FCRA.",
    objectivePrompt: "What information in your LexisNexis report is inaccurate and what correction are you requesting?",
    draftSubject: "Dispute of Inaccurate LexisNexis Consumer Report Information",
    disclaimer: commonDisclaimer,
  },
  "fcra-dispute": {
    id: "fcra-dispute",
    slug: "fcra-dispute-letter",
    primaryKeyword: "fcra dispute letter",
    supportingKeywords: ["fair credit reporting act dispute", "FCRA credit dispute", "FCRA violation dispute"],
    searchIntent: "transactional",
    problem: "The customer identifies inaccurate credit reporting and wants to dispute it under the Fair Credit Reporting Act.",
    outcome: "Prepare an FCRA-based dispute citing the statutory framework and identifying the specific reporting violations.",
    recipientRole: "credit bureau and/or data furnisher",
    requiredFacts: ["bureau or furnisher", "account/reference number", "specific reporting violation", "requested investigation or correction"],
    evidenceRequirements: ["credit report excerpt", "account documentation", "correspondence showing the dispute history"],
    deadlinePolicy: "Capture report date, dispute date, and any response. FCRA sets investigation timelines for bureaus and furnishers.",
    objectivePrompt: "Which FCRA provisions do you believe were violated and what correction or investigation are you requesting?",
    draftSubject: "FCRA Dispute of Inaccurate Credit Reporting",
    disclaimer: commonDisclaimer,
  },
  "fdcpa-dispute": {
    id: "fdcpa-dispute",
    slug: "fdcpa-dispute-letter",
    primaryKeyword: "fdcpa dispute letter",
    supportingKeywords: ["fair debt collection practices act dispute", "FDCPA violation dispute", "debt collector violation letter"],
    searchIntent: "transactional",
    problem: "The customer identifies unfair, deceptive, or harassing debt collection practices and wants to document a dispute under the FDCPA.",
    outcome: "Prepare an FDCPA-based dispute documenting the specific collection practices at issue and requesting corrective action.",
    recipientRole: "debt collector or collection agency",
    requiredFacts: ["collector identity", "account/reference number", "specific practice at issue", "requested corrective action"],
    evidenceRequirements: ["collection notices or correspondence", "call logs or message records", "account documentation"],
    deadlinePolicy: "Capture dates of the challenged practices. The FDCPA has limitations periods for private actions.",
    objectivePrompt: "Which specific collection practices do you believe violated the FDCPA and what action are you requesting?",
    draftSubject: "FDCPA Dispute of Debt Collection Practices",
    disclaimer: commonDisclaimer,
  },
  "debt-lawsuit-response": {
    id: "debt-lawsuit-response",
    slug: "debt-lawsuit-response",
    primaryKeyword: "debt lawsuit response",
    supportingKeywords: ["respond to debt lawsuit", "answer debt collection lawsuit", "debt collection summons response"],
    searchIntent: "problem",
    problem: "The customer has been served with a debt collection lawsuit or court summons and needs to prepare a documented response.",
    outcome: "Prepare a factual response document identifying the claim, the disputed facts, supporting evidence, and the customer's position.",
    recipientRole: "court and/or plaintiff's attorney",
    requiredFacts: ["court name", "case number", "plaintiff", "amount claimed", "factual basis for dispute"],
    evidenceRequirements: ["summons and complaint", "account documentation", "collection correspondence", "evidence supporting defenses"],
    deadlinePolicy: "Court deadlines are strict. Capture the response deadline from the summons. Do not miss filing deadlines.",
    objectivePrompt: "What facts do you dispute in the lawsuit and what response or position are you presenting to the court?",
    draftSubject: "Response to Debt Collection Complaint",
    disclaimer: "Dispute Mail provides document preparation and mailing assistance. It is not a law firm and does not provide legal advice. Court filings have strict deadlines and procedural requirements that may require licensed attorney assistance.",
  },
};

export function getWorkflowProfile(id: WorkflowId): WorkflowProfile {
  return workflowProfiles[id];
}
